// source: Buttons.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global =
    (typeof globalThis !== 'undefined' && globalThis) ||
    (typeof window !== 'undefined' && window) ||
    (typeof global !== 'undefined' && global) ||
    (typeof self !== 'undefined' && self) ||
    (function () { return this; }).call(null) ||
    Function('return this')();

var GPIO_pb = require('./GPIO_pb.js');
goog.object.extend(proto, GPIO_pb);
var nanopb_pb = require('./nanopb_pb.js');
goog.object.extend(proto, nanopb_pb);
goog.exportSymbol('proto.sys.Button', null, global);
goog.exportSymbol('proto.sys.ButtonAction', null, global);
goog.exportSymbol('proto.sys.ButtonActionChoice', null, global);
goog.exportSymbol('proto.sys.ButtonActionChoice.ActiontypeCase', null, global);
goog.exportSymbol('proto.sys.ButtonActions', null, global);
goog.exportSymbol('proto.sys.ButtonProfile', null, global);
goog.exportSymbol('proto.sys.KnobOnly', null, global);
goog.exportSymbol('proto.sys.Rotary', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.sys.ButtonActionChoice = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.sys.ButtonActionChoice.oneofGroups_);
};
goog.inherits(proto.sys.ButtonActionChoice, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.sys.ButtonActionChoice.displayName = 'proto.sys.ButtonActionChoice';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.sys.ButtonActions = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.sys.ButtonActions, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.sys.ButtonActions.displayName = 'proto.sys.ButtonActions';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.sys.Button = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.sys.Button, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.sys.Button.displayName = 'proto.sys.Button';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.sys.ButtonProfile = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.sys.ButtonProfile.repeatedFields_, null);
};
goog.inherits(proto.sys.ButtonProfile, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.sys.ButtonProfile.displayName = 'proto.sys.ButtonProfile';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.sys.KnobOnly = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.sys.KnobOnly, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.sys.KnobOnly.displayName = 'proto.sys.KnobOnly';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.sys.Rotary = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.sys.Rotary, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.sys.Rotary.displayName = 'proto.sys.Rotary';
}

/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.sys.ButtonActionChoice.oneofGroups_ = [[1,2]];

/**
 * @enum {number}
 */
proto.sys.ButtonActionChoice.ActiontypeCase = {
  ACTIONTYPE_NOT_SET: 0,
  ACTION: 1,
  PROFILE_NAME: 2
};

/**
 * @return {proto.sys.ButtonActionChoice.ActiontypeCase}
 */
proto.sys.ButtonActionChoice.prototype.getActiontypeCase = function() {
  return /** @type {proto.sys.ButtonActionChoice.ActiontypeCase} */(jspb.Message.computeOneofCase(this, proto.sys.ButtonActionChoice.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.sys.ButtonActionChoice.prototype.toObject = function(opt_includeInstance) {
  return proto.sys.ButtonActionChoice.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.sys.ButtonActionChoice} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sys.ButtonActionChoice.toObject = function(includeInstance, msg) {
  var f, obj = {
    action: jspb.Message.getFieldWithDefault(msg, 1, 0),
    profileName: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.sys.ButtonActionChoice}
 */
proto.sys.ButtonActionChoice.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.sys.ButtonActionChoice;
  return proto.sys.ButtonActionChoice.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.sys.ButtonActionChoice} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.sys.ButtonActionChoice}
 */
proto.sys.ButtonActionChoice.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.sys.ButtonAction} */ (reader.readEnum());
      msg.setAction(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setProfileName(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.sys.ButtonActionChoice.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.sys.ButtonActionChoice.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.sys.ButtonActionChoice} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sys.ButtonActionChoice.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = /** @type {!proto.sys.ButtonAction} */ (jspb.Message.getField(message, 1));
  if (f != null) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 2));
  if (f != null) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional ButtonAction action = 1;
 * @return {!proto.sys.ButtonAction}
 */
proto.sys.ButtonActionChoice.prototype.getAction = function() {
  return /** @type {!proto.sys.ButtonAction} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {!proto.sys.ButtonAction} value
 * @return {!proto.sys.ButtonActionChoice} returns this
 */
proto.sys.ButtonActionChoice.prototype.setAction = function(value) {
  return jspb.Message.setOneofField(this, 1, proto.sys.ButtonActionChoice.oneofGroups_[0], value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.sys.ButtonActionChoice} returns this
 */
proto.sys.ButtonActionChoice.prototype.clearAction = function() {
  return jspb.Message.setOneofField(this, 1, proto.sys.ButtonActionChoice.oneofGroups_[0], undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sys.ButtonActionChoice.prototype.hasAction = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional string profile_name = 2;
 * @return {string}
 */
proto.sys.ButtonActionChoice.prototype.getProfileName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.sys.ButtonActionChoice} returns this
 */
proto.sys.ButtonActionChoice.prototype.setProfileName = function(value) {
  return jspb.Message.setOneofField(this, 2, proto.sys.ButtonActionChoice.oneofGroups_[0], value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.sys.ButtonActionChoice} returns this
 */
proto.sys.ButtonActionChoice.prototype.clearProfileName = function() {
  return jspb.Message.setOneofField(this, 2, proto.sys.ButtonActionChoice.oneofGroups_[0], undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sys.ButtonActionChoice.prototype.hasProfileName = function() {
  return jspb.Message.getField(this, 2) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.sys.ButtonActions.prototype.toObject = function(opt_includeInstance) {
  return proto.sys.ButtonActions.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.sys.ButtonActions} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sys.ButtonActions.toObject = function(includeInstance, msg) {
  var f, obj = {
    normal: (f = msg.getNormal()) && proto.sys.ButtonActionChoice.toObject(includeInstance, f),
    longpress: (f = msg.getLongpress()) && proto.sys.ButtonActionChoice.toObject(includeInstance, f),
    shifted: (f = msg.getShifted()) && proto.sys.ButtonActionChoice.toObject(includeInstance, f),
    longshifted: (f = msg.getLongshifted()) && proto.sys.ButtonActionChoice.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.sys.ButtonActions}
 */
proto.sys.ButtonActions.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.sys.ButtonActions;
  return proto.sys.ButtonActions.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.sys.ButtonActions} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.sys.ButtonActions}
 */
proto.sys.ButtonActions.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.sys.ButtonActionChoice;
      reader.readMessage(value,proto.sys.ButtonActionChoice.deserializeBinaryFromReader);
      msg.setNormal(value);
      break;
    case 2:
      var value = new proto.sys.ButtonActionChoice;
      reader.readMessage(value,proto.sys.ButtonActionChoice.deserializeBinaryFromReader);
      msg.setLongpress(value);
      break;
    case 3:
      var value = new proto.sys.ButtonActionChoice;
      reader.readMessage(value,proto.sys.ButtonActionChoice.deserializeBinaryFromReader);
      msg.setShifted(value);
      break;
    case 4:
      var value = new proto.sys.ButtonActionChoice;
      reader.readMessage(value,proto.sys.ButtonActionChoice.deserializeBinaryFromReader);
      msg.setLongshifted(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.sys.ButtonActions.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.sys.ButtonActions.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.sys.ButtonActions} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sys.ButtonActions.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getNormal();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.sys.ButtonActionChoice.serializeBinaryToWriter
    );
  }
  f = message.getLongpress();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.sys.ButtonActionChoice.serializeBinaryToWriter
    );
  }
  f = message.getShifted();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.sys.ButtonActionChoice.serializeBinaryToWriter
    );
  }
  f = message.getLongshifted();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      proto.sys.ButtonActionChoice.serializeBinaryToWriter
    );
  }
};


/**
 * optional ButtonActionChoice normal = 1;
 * @return {?proto.sys.ButtonActionChoice}
 */
proto.sys.ButtonActions.prototype.getNormal = function() {
  return /** @type{?proto.sys.ButtonActionChoice} */ (
    jspb.Message.getWrapperField(this, proto.sys.ButtonActionChoice, 1));
};


/**
 * @param {?proto.sys.ButtonActionChoice|undefined} value
 * @return {!proto.sys.ButtonActions} returns this
*/
proto.sys.ButtonActions.prototype.setNormal = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.sys.ButtonActions} returns this
 */
proto.sys.ButtonActions.prototype.clearNormal = function() {
  return this.setNormal(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sys.ButtonActions.prototype.hasNormal = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional ButtonActionChoice longpress = 2;
 * @return {?proto.sys.ButtonActionChoice}
 */
proto.sys.ButtonActions.prototype.getLongpress = function() {
  return /** @type{?proto.sys.ButtonActionChoice} */ (
    jspb.Message.getWrapperField(this, proto.sys.ButtonActionChoice, 2));
};


/**
 * @param {?proto.sys.ButtonActionChoice|undefined} value
 * @return {!proto.sys.ButtonActions} returns this
*/
proto.sys.ButtonActions.prototype.setLongpress = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.sys.ButtonActions} returns this
 */
proto.sys.ButtonActions.prototype.clearLongpress = function() {
  return this.setLongpress(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sys.ButtonActions.prototype.hasLongpress = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional ButtonActionChoice shifted = 3;
 * @return {?proto.sys.ButtonActionChoice}
 */
proto.sys.ButtonActions.prototype.getShifted = function() {
  return /** @type{?proto.sys.ButtonActionChoice} */ (
    jspb.Message.getWrapperField(this, proto.sys.ButtonActionChoice, 3));
};


/**
 * @param {?proto.sys.ButtonActionChoice|undefined} value
 * @return {!proto.sys.ButtonActions} returns this
*/
proto.sys.ButtonActions.prototype.setShifted = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.sys.ButtonActions} returns this
 */
proto.sys.ButtonActions.prototype.clearShifted = function() {
  return this.setShifted(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sys.ButtonActions.prototype.hasShifted = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional ButtonActionChoice longshifted = 4;
 * @return {?proto.sys.ButtonActionChoice}
 */
proto.sys.ButtonActions.prototype.getLongshifted = function() {
  return /** @type{?proto.sys.ButtonActionChoice} */ (
    jspb.Message.getWrapperField(this, proto.sys.ButtonActionChoice, 4));
};


/**
 * @param {?proto.sys.ButtonActionChoice|undefined} value
 * @return {!proto.sys.ButtonActions} returns this
*/
proto.sys.ButtonActions.prototype.setLongshifted = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.sys.ButtonActions} returns this
 */
proto.sys.ButtonActions.prototype.clearLongshifted = function() {
  return this.setLongshifted(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sys.ButtonActions.prototype.hasLongshifted = function() {
  return jspb.Message.getField(this, 4) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.sys.Button.prototype.toObject = function(opt_includeInstance) {
  return proto.sys.Button.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.sys.Button} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sys.Button.toObject = function(includeInstance, msg) {
  var f, obj = {
    gpio: (f = msg.getGpio()) && GPIO_pb.GPIO.toObject(includeInstance, f),
    pull: jspb.Message.getBooleanFieldWithDefault(msg, 2, false),
    debounce: jspb.Message.getFieldWithDefault(msg, 3, 0),
    shifter: (f = msg.getShifter()) && GPIO_pb.GPIO.toObject(includeInstance, f),
    longduration: jspb.Message.getFieldWithDefault(msg, 5, 0),
    pressed: (f = msg.getPressed()) && proto.sys.ButtonActions.toObject(includeInstance, f),
    released: (f = msg.getReleased()) && proto.sys.ButtonActions.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.sys.Button}
 */
proto.sys.Button.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.sys.Button;
  return proto.sys.Button.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.sys.Button} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.sys.Button}
 */
proto.sys.Button.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new GPIO_pb.GPIO;
      reader.readMessage(value,GPIO_pb.GPIO.deserializeBinaryFromReader);
      msg.setGpio(value);
      break;
    case 2:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setPull(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setDebounce(value);
      break;
    case 4:
      var value = new GPIO_pb.GPIO;
      reader.readMessage(value,GPIO_pb.GPIO.deserializeBinaryFromReader);
      msg.setShifter(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setLongduration(value);
      break;
    case 6:
      var value = new proto.sys.ButtonActions;
      reader.readMessage(value,proto.sys.ButtonActions.deserializeBinaryFromReader);
      msg.setPressed(value);
      break;
    case 7:
      var value = new proto.sys.ButtonActions;
      reader.readMessage(value,proto.sys.ButtonActions.deserializeBinaryFromReader);
      msg.setReleased(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.sys.Button.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.sys.Button.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.sys.Button} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sys.Button.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getGpio();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      GPIO_pb.GPIO.serializeBinaryToWriter
    );
  }
  f = message.getPull();
  if (f) {
    writer.writeBool(
      2,
      f
    );
  }
  f = message.getDebounce();
  if (f !== 0) {
    writer.writeInt32(
      3,
      f
    );
  }
  f = message.getShifter();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      GPIO_pb.GPIO.serializeBinaryToWriter
    );
  }
  f = message.getLongduration();
  if (f !== 0) {
    writer.writeInt32(
      5,
      f
    );
  }
  f = message.getPressed();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      proto.sys.ButtonActions.serializeBinaryToWriter
    );
  }
  f = message.getReleased();
  if (f != null) {
    writer.writeMessage(
      7,
      f,
      proto.sys.ButtonActions.serializeBinaryToWriter
    );
  }
};


/**
 * optional GPIO gpio = 1;
 * @return {?proto.sys.GPIO}
 */
proto.sys.Button.prototype.getGpio = function() {
  return /** @type{?proto.sys.GPIO} */ (
    jspb.Message.getWrapperField(this, GPIO_pb.GPIO, 1));
};


/**
 * @param {?proto.sys.GPIO|undefined} value
 * @return {!proto.sys.Button} returns this
*/
proto.sys.Button.prototype.setGpio = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.sys.Button} returns this
 */
proto.sys.Button.prototype.clearGpio = function() {
  return this.setGpio(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sys.Button.prototype.hasGpio = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional bool pull = 2;
 * @return {boolean}
 */
proto.sys.Button.prototype.getPull = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 2, false));
};


/**
 * @param {boolean} value
 * @return {!proto.sys.Button} returns this
 */
proto.sys.Button.prototype.setPull = function(value) {
  return jspb.Message.setProto3BooleanField(this, 2, value);
};


/**
 * optional int32 debounce = 3;
 * @return {number}
 */
proto.sys.Button.prototype.getDebounce = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.sys.Button} returns this
 */
proto.sys.Button.prototype.setDebounce = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional GPIO shifter = 4;
 * @return {?proto.sys.GPIO}
 */
proto.sys.Button.prototype.getShifter = function() {
  return /** @type{?proto.sys.GPIO} */ (
    jspb.Message.getWrapperField(this, GPIO_pb.GPIO, 4));
};


/**
 * @param {?proto.sys.GPIO|undefined} value
 * @return {!proto.sys.Button} returns this
*/
proto.sys.Button.prototype.setShifter = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.sys.Button} returns this
 */
proto.sys.Button.prototype.clearShifter = function() {
  return this.setShifter(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sys.Button.prototype.hasShifter = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional int32 longduration = 5;
 * @return {number}
 */
proto.sys.Button.prototype.getLongduration = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.sys.Button} returns this
 */
proto.sys.Button.prototype.setLongduration = function(value) {
  return jspb.Message.setProto3IntField(this, 5, value);
};


/**
 * optional ButtonActions pressed = 6;
 * @return {?proto.sys.ButtonActions}
 */
proto.sys.Button.prototype.getPressed = function() {
  return /** @type{?proto.sys.ButtonActions} */ (
    jspb.Message.getWrapperField(this, proto.sys.ButtonActions, 6));
};


/**
 * @param {?proto.sys.ButtonActions|undefined} value
 * @return {!proto.sys.Button} returns this
*/
proto.sys.Button.prototype.setPressed = function(value) {
  return jspb.Message.setWrapperField(this, 6, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.sys.Button} returns this
 */
proto.sys.Button.prototype.clearPressed = function() {
  return this.setPressed(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sys.Button.prototype.hasPressed = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * optional ButtonActions released = 7;
 * @return {?proto.sys.ButtonActions}
 */
proto.sys.Button.prototype.getReleased = function() {
  return /** @type{?proto.sys.ButtonActions} */ (
    jspb.Message.getWrapperField(this, proto.sys.ButtonActions, 7));
};


/**
 * @param {?proto.sys.ButtonActions|undefined} value
 * @return {!proto.sys.Button} returns this
*/
proto.sys.Button.prototype.setReleased = function(value) {
  return jspb.Message.setWrapperField(this, 7, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.sys.Button} returns this
 */
proto.sys.Button.prototype.clearReleased = function() {
  return this.setReleased(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sys.Button.prototype.hasReleased = function() {
  return jspb.Message.getField(this, 7) != null;
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.sys.ButtonProfile.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.sys.ButtonProfile.prototype.toObject = function(opt_includeInstance) {
  return proto.sys.ButtonProfile.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.sys.ButtonProfile} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sys.ButtonProfile.toObject = function(includeInstance, msg) {
  var f, obj = {
    profileName: jspb.Message.getFieldWithDefault(msg, 1, ""),
    buttonList: jspb.Message.toObjectList(msg.getButtonList(),
    proto.sys.Button.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.sys.ButtonProfile}
 */
proto.sys.ButtonProfile.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.sys.ButtonProfile;
  return proto.sys.ButtonProfile.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.sys.ButtonProfile} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.sys.ButtonProfile}
 */
proto.sys.ButtonProfile.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setProfileName(value);
      break;
    case 2:
      var value = new proto.sys.Button;
      reader.readMessage(value,proto.sys.Button.deserializeBinaryFromReader);
      msg.addButton(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.sys.ButtonProfile.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.sys.ButtonProfile.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.sys.ButtonProfile} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sys.ButtonProfile.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getProfileName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getButtonList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      proto.sys.Button.serializeBinaryToWriter
    );
  }
};


/**
 * optional string profile_name = 1;
 * @return {string}
 */
proto.sys.ButtonProfile.prototype.getProfileName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.sys.ButtonProfile} returns this
 */
proto.sys.ButtonProfile.prototype.setProfileName = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * repeated Button button = 2;
 * @return {!Array<!proto.sys.Button>}
 */
proto.sys.ButtonProfile.prototype.getButtonList = function() {
  return /** @type{!Array<!proto.sys.Button>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.sys.Button, 2));
};


/**
 * @param {!Array<!proto.sys.Button>} value
 * @return {!proto.sys.ButtonProfile} returns this
*/
proto.sys.ButtonProfile.prototype.setButtonList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.sys.Button=} opt_value
 * @param {number=} opt_index
 * @return {!proto.sys.Button}
 */
proto.sys.ButtonProfile.prototype.addButton = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.sys.Button, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.sys.ButtonProfile} returns this
 */
proto.sys.ButtonProfile.prototype.clearButtonList = function() {
  return this.setButtonList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.sys.KnobOnly.prototype.toObject = function(opt_includeInstance) {
  return proto.sys.KnobOnly.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.sys.KnobOnly} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sys.KnobOnly.toObject = function(includeInstance, msg) {
  var f, obj = {
    enable: jspb.Message.getBooleanFieldWithDefault(msg, 1, false),
    delayMs: jspb.Message.getFieldWithDefault(msg, 2, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.sys.KnobOnly}
 */
proto.sys.KnobOnly.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.sys.KnobOnly;
  return proto.sys.KnobOnly.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.sys.KnobOnly} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.sys.KnobOnly}
 */
proto.sys.KnobOnly.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setEnable(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setDelayMs(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.sys.KnobOnly.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.sys.KnobOnly.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.sys.KnobOnly} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sys.KnobOnly.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getEnable();
  if (f) {
    writer.writeBool(
      1,
      f
    );
  }
  f = message.getDelayMs();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
};


/**
 * optional bool enable = 1;
 * @return {boolean}
 */
proto.sys.KnobOnly.prototype.getEnable = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 1, false));
};


/**
 * @param {boolean} value
 * @return {!proto.sys.KnobOnly} returns this
 */
proto.sys.KnobOnly.prototype.setEnable = function(value) {
  return jspb.Message.setProto3BooleanField(this, 1, value);
};


/**
 * optional int32 delay_ms = 2;
 * @return {number}
 */
proto.sys.KnobOnly.prototype.getDelayMs = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.sys.KnobOnly} returns this
 */
proto.sys.KnobOnly.prototype.setDelayMs = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.sys.Rotary.prototype.toObject = function(opt_includeInstance) {
  return proto.sys.Rotary.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.sys.Rotary} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sys.Rotary.toObject = function(includeInstance, msg) {
  var f, obj = {
    a: (f = msg.getA()) && GPIO_pb.GPIO.toObject(includeInstance, f),
    b: (f = msg.getB()) && GPIO_pb.GPIO.toObject(includeInstance, f),
    sw: (f = msg.getSw()) && GPIO_pb.GPIO.toObject(includeInstance, f),
    knobonly: (f = msg.getKnobonly()) && proto.sys.KnobOnly.toObject(includeInstance, f),
    volume: jspb.Message.getBooleanFieldWithDefault(msg, 5, false),
    longpress: jspb.Message.getBooleanFieldWithDefault(msg, 6, false)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.sys.Rotary}
 */
proto.sys.Rotary.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.sys.Rotary;
  return proto.sys.Rotary.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.sys.Rotary} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.sys.Rotary}
 */
proto.sys.Rotary.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new GPIO_pb.GPIO;
      reader.readMessage(value,GPIO_pb.GPIO.deserializeBinaryFromReader);
      msg.setA(value);
      break;
    case 2:
      var value = new GPIO_pb.GPIO;
      reader.readMessage(value,GPIO_pb.GPIO.deserializeBinaryFromReader);
      msg.setB(value);
      break;
    case 3:
      var value = new GPIO_pb.GPIO;
      reader.readMessage(value,GPIO_pb.GPIO.deserializeBinaryFromReader);
      msg.setSw(value);
      break;
    case 4:
      var value = new proto.sys.KnobOnly;
      reader.readMessage(value,proto.sys.KnobOnly.deserializeBinaryFromReader);
      msg.setKnobonly(value);
      break;
    case 5:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setVolume(value);
      break;
    case 6:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setLongpress(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.sys.Rotary.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.sys.Rotary.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.sys.Rotary} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sys.Rotary.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getA();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      GPIO_pb.GPIO.serializeBinaryToWriter
    );
  }
  f = message.getB();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      GPIO_pb.GPIO.serializeBinaryToWriter
    );
  }
  f = message.getSw();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      GPIO_pb.GPIO.serializeBinaryToWriter
    );
  }
  f = message.getKnobonly();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      proto.sys.KnobOnly.serializeBinaryToWriter
    );
  }
  f = message.getVolume();
  if (f) {
    writer.writeBool(
      5,
      f
    );
  }
  f = message.getLongpress();
  if (f) {
    writer.writeBool(
      6,
      f
    );
  }
};


/**
 * optional GPIO A = 1;
 * @return {?proto.sys.GPIO}
 */
proto.sys.Rotary.prototype.getA = function() {
  return /** @type{?proto.sys.GPIO} */ (
    jspb.Message.getWrapperField(this, GPIO_pb.GPIO, 1));
};


/**
 * @param {?proto.sys.GPIO|undefined} value
 * @return {!proto.sys.Rotary} returns this
*/
proto.sys.Rotary.prototype.setA = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.sys.Rotary} returns this
 */
proto.sys.Rotary.prototype.clearA = function() {
  return this.setA(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sys.Rotary.prototype.hasA = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional GPIO B = 2;
 * @return {?proto.sys.GPIO}
 */
proto.sys.Rotary.prototype.getB = function() {
  return /** @type{?proto.sys.GPIO} */ (
    jspb.Message.getWrapperField(this, GPIO_pb.GPIO, 2));
};


/**
 * @param {?proto.sys.GPIO|undefined} value
 * @return {!proto.sys.Rotary} returns this
*/
proto.sys.Rotary.prototype.setB = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.sys.Rotary} returns this
 */
proto.sys.Rotary.prototype.clearB = function() {
  return this.setB(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sys.Rotary.prototype.hasB = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional GPIO SW = 3;
 * @return {?proto.sys.GPIO}
 */
proto.sys.Rotary.prototype.getSw = function() {
  return /** @type{?proto.sys.GPIO} */ (
    jspb.Message.getWrapperField(this, GPIO_pb.GPIO, 3));
};


/**
 * @param {?proto.sys.GPIO|undefined} value
 * @return {!proto.sys.Rotary} returns this
*/
proto.sys.Rotary.prototype.setSw = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.sys.Rotary} returns this
 */
proto.sys.Rotary.prototype.clearSw = function() {
  return this.setSw(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sys.Rotary.prototype.hasSw = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional KnobOnly knobonly = 4;
 * @return {?proto.sys.KnobOnly}
 */
proto.sys.Rotary.prototype.getKnobonly = function() {
  return /** @type{?proto.sys.KnobOnly} */ (
    jspb.Message.getWrapperField(this, proto.sys.KnobOnly, 4));
};


/**
 * @param {?proto.sys.KnobOnly|undefined} value
 * @return {!proto.sys.Rotary} returns this
*/
proto.sys.Rotary.prototype.setKnobonly = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.sys.Rotary} returns this
 */
proto.sys.Rotary.prototype.clearKnobonly = function() {
  return this.setKnobonly(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sys.Rotary.prototype.hasKnobonly = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional bool volume = 5;
 * @return {boolean}
 */
proto.sys.Rotary.prototype.getVolume = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 5, false));
};


/**
 * @param {boolean} value
 * @return {!proto.sys.Rotary} returns this
 */
proto.sys.Rotary.prototype.setVolume = function(value) {
  return jspb.Message.setProto3BooleanField(this, 5, value);
};


/**
 * optional bool longpress = 6;
 * @return {boolean}
 */
proto.sys.Rotary.prototype.getLongpress = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 6, false));
};


/**
 * @param {boolean} value
 * @return {!proto.sys.Rotary} returns this
 */
proto.sys.Rotary.prototype.setLongpress = function(value) {
  return jspb.Message.setProto3BooleanField(this, 6, value);
};


/**
 * @enum {number}
 */
proto.sys.ButtonAction = {
  ACTRLS_NONE: 0,
  ACTRLS_POWER: 1,
  ACTRLS_VOLUP: 2,
  ACTRLS_VOLDOWN: 3,
  ACTRLS_TOGGLE: 4,
  ACTRLS_PLAY: 5,
  ACTRLS_PAUSE: 6,
  ACTRLS_STOP: 7,
  ACTRLS_REW: 8,
  ACTRLS_FWD: 9,
  ACTRLS_PREV: 10,
  ACTRLS_NEXT: 11,
  BCTRLS_UP: 12,
  BCTRLS_DOWN: 13,
  BCTRLS_LEFT: 14,
  BCTRLS_RIGHT: 15,
  BCTRLS_PS1: 16,
  BCTRLS_PS2: 17,
  BCTRLS_PS3: 18,
  BCTRLS_PS4: 19,
  BCTRLS_PS5: 20,
  BCTRLS_PS6: 21,
  BCTRLS_PS7: 22,
  BCTRLS_PS8: 23,
  BCTRLS_PS9: 24,
  BCTRLS_PS10: 25,
  KNOB_LEFT: 26,
  KNOB_RIGHT: 27,
  KNOB_PUSH: 28,
  ACTRLS_SLEEP: 29
};

goog.object.extend(exports, proto.sys);
