// source: configuration.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global =
    (typeof globalThis !== 'undefined' && globalThis) ||
    (typeof window !== 'undefined' && window) ||
    (typeof global !== 'undefined' && global) ||
    (typeof self !== 'undefined' && self) ||
    (function () { return this; }).call(null) ||
    Function('return this')();

var Services_pb = require('./Services_pb.js');
goog.object.extend(proto, Services_pb);
var GPIO_pb = require('./GPIO_pb.js');
goog.object.extend(proto, GPIO_pb);
var Devices_pb = require('./Devices_pb.js');
goog.object.extend(proto, Devices_pb);
var Names_pb = require('./Names_pb.js');
goog.object.extend(proto, Names_pb);
var Network_pb = require('./Network_pb.js');
goog.object.extend(proto, Network_pb);
var customoptions_pb = require('./customoptions_pb.js');
goog.object.extend(proto, customoptions_pb);
var nanopb_pb = require('./nanopb_pb.js');
goog.object.extend(proto, nanopb_pb);
goog.exportSymbol('proto.sys.Config', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.sys.Config = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.sys.Config, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.sys.Config.displayName = 'proto.sys.Config';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.sys.Config.prototype.toObject = function(opt_includeInstance) {
  return proto.sys.Config.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.sys.Config} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sys.Config.toObject = function(includeInstance, msg) {
  var f, obj = {
    gpios: (f = msg.getGpios()) && GPIO_pb.Gpios.toObject(includeInstance, f),
    dev: (f = msg.getDev()) && Devices_pb.Dev.toObject(includeInstance, f),
    services: (f = msg.getServices()) && Services_pb.Services.toObject(includeInstance, f),
    names: (f = msg.getNames()) && Names_pb.Names.toObject(includeInstance, f),
    target: jspb.Message.getFieldWithDefault(msg, 5, ""),
    net: (f = msg.getNet()) && Network_pb.NetworkConfig.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.sys.Config}
 */
proto.sys.Config.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.sys.Config;
  return proto.sys.Config.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.sys.Config} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.sys.Config}
 */
proto.sys.Config.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new GPIO_pb.Gpios;
      reader.readMessage(value,GPIO_pb.Gpios.deserializeBinaryFromReader);
      msg.setGpios(value);
      break;
    case 2:
      var value = new Devices_pb.Dev;
      reader.readMessage(value,Devices_pb.Dev.deserializeBinaryFromReader);
      msg.setDev(value);
      break;
    case 3:
      var value = new Services_pb.Services;
      reader.readMessage(value,Services_pb.Services.deserializeBinaryFromReader);
      msg.setServices(value);
      break;
    case 4:
      var value = new Names_pb.Names;
      reader.readMessage(value,Names_pb.Names.deserializeBinaryFromReader);
      msg.setNames(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setTarget(value);
      break;
    case 6:
      var value = new Network_pb.NetworkConfig;
      reader.readMessage(value,Network_pb.NetworkConfig.deserializeBinaryFromReader);
      msg.setNet(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.sys.Config.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.sys.Config.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.sys.Config} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sys.Config.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getGpios();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      GPIO_pb.Gpios.serializeBinaryToWriter
    );
  }
  f = message.getDev();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      Devices_pb.Dev.serializeBinaryToWriter
    );
  }
  f = message.getServices();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      Services_pb.Services.serializeBinaryToWriter
    );
  }
  f = message.getNames();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      Names_pb.Names.serializeBinaryToWriter
    );
  }
  f = message.getTarget();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getNet();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      Network_pb.NetworkConfig.serializeBinaryToWriter
    );
  }
};


/**
 * optional Gpios gpios = 1;
 * @return {?proto.sys.Gpios}
 */
proto.sys.Config.prototype.getGpios = function() {
  return /** @type{?proto.sys.Gpios} */ (
    jspb.Message.getWrapperField(this, GPIO_pb.Gpios, 1));
};


/**
 * @param {?proto.sys.Gpios|undefined} value
 * @return {!proto.sys.Config} returns this
*/
proto.sys.Config.prototype.setGpios = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.sys.Config} returns this
 */
proto.sys.Config.prototype.clearGpios = function() {
  return this.setGpios(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sys.Config.prototype.hasGpios = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional Dev dev = 2;
 * @return {?proto.sys.Dev}
 */
proto.sys.Config.prototype.getDev = function() {
  return /** @type{?proto.sys.Dev} */ (
    jspb.Message.getWrapperField(this, Devices_pb.Dev, 2));
};


/**
 * @param {?proto.sys.Dev|undefined} value
 * @return {!proto.sys.Config} returns this
*/
proto.sys.Config.prototype.setDev = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.sys.Config} returns this
 */
proto.sys.Config.prototype.clearDev = function() {
  return this.setDev(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sys.Config.prototype.hasDev = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional Services services = 3;
 * @return {?proto.sys.Services}
 */
proto.sys.Config.prototype.getServices = function() {
  return /** @type{?proto.sys.Services} */ (
    jspb.Message.getWrapperField(this, Services_pb.Services, 3));
};


/**
 * @param {?proto.sys.Services|undefined} value
 * @return {!proto.sys.Config} returns this
*/
proto.sys.Config.prototype.setServices = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.sys.Config} returns this
 */
proto.sys.Config.prototype.clearServices = function() {
  return this.setServices(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sys.Config.prototype.hasServices = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional Names names = 4;
 * @return {?proto.sys.Names}
 */
proto.sys.Config.prototype.getNames = function() {
  return /** @type{?proto.sys.Names} */ (
    jspb.Message.getWrapperField(this, Names_pb.Names, 4));
};


/**
 * @param {?proto.sys.Names|undefined} value
 * @return {!proto.sys.Config} returns this
*/
proto.sys.Config.prototype.setNames = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.sys.Config} returns this
 */
proto.sys.Config.prototype.clearNames = function() {
  return this.setNames(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sys.Config.prototype.hasNames = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional string target = 5;
 * @return {string}
 */
proto.sys.Config.prototype.getTarget = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.sys.Config} returns this
 */
proto.sys.Config.prototype.setTarget = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional NetworkConfig net = 6;
 * @return {?proto.sys.NetworkConfig}
 */
proto.sys.Config.prototype.getNet = function() {
  return /** @type{?proto.sys.NetworkConfig} */ (
    jspb.Message.getWrapperField(this, Network_pb.NetworkConfig, 6));
};


/**
 * @param {?proto.sys.NetworkConfig|undefined} value
 * @return {!proto.sys.Config} returns this
*/
proto.sys.Config.prototype.setNet = function(value) {
  return jspb.Message.setWrapperField(this, 6, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.sys.Config} returns this
 */
proto.sys.Config.prototype.clearNet = function() {
  return this.setNet(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sys.Config.prototype.hasNet = function() {
  return jspb.Message.getField(this, 6) != null;
};


goog.object.extend(exports, proto.sys);
