// source: customoptions.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global =
    (typeof globalThis !== 'undefined' && globalThis) ||
    (typeof window !== 'undefined' && window) ||
    (typeof global !== 'undefined' && global) ||
    (typeof self !== 'undefined' && self) ||
    (function () { return this; }).call(null) ||
    Function('return this')();

var google_protobuf_descriptor_pb = require('google-protobuf/google/protobuf/descriptor_pb.js');
goog.object.extend(proto, google_protobuf_descriptor_pb);
var nanopb_pb = require('./nanopb_pb.js');
goog.object.extend(proto, nanopb_pb);
goog.exportSymbol('proto.CustomOptions', null, global);
goog.exportSymbol('proto.CustomOptions.DefaultValueCase', null, global);
goog.exportSymbol('proto.custEnum', null, global);
goog.exportSymbol('proto.custField', null, global);
goog.exportSymbol('proto.custFile', null, global);
goog.exportSymbol('proto.custMsg', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.CustomOptions = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, 500, null, proto.CustomOptions.oneofGroups_);
};
goog.inherits(proto.CustomOptions, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.CustomOptions.displayName = 'proto.CustomOptions';
}

/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.CustomOptions.oneofGroups_ = [[50050,50051,50052,50053,50054,50055,50056,50057,50058,50059,50060]];

/**
 * @enum {number}
 */
proto.CustomOptions.DefaultValueCase = {
  DEFAULT_VALUE_NOT_SET: 0,
  V_STRING: 50050,
  V_UINT32: 50051,
  V_INT32: 50052,
  V_UINT64: 50053,
  V_INT64: 50054,
  V_DOUBLE: 50055,
  V_FLOAT: 50056,
  V_BOOL: 50057,
  V_ENUM: 50058,
  V_BYTES: 50059,
  V_MSG: 50060
};

/**
 * @return {proto.CustomOptions.DefaultValueCase}
 */
proto.CustomOptions.prototype.getDefaultValueCase = function() {
  return /** @type {proto.CustomOptions.DefaultValueCase} */(jspb.Message.computeOneofCase(this, proto.CustomOptions.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.CustomOptions.prototype.toObject = function(opt_includeInstance) {
  return proto.CustomOptions.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.CustomOptions} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.CustomOptions.toObject = function(includeInstance, msg) {
  var f, obj = {
    initFromMac: jspb.Message.getBooleanFieldWithDefault(msg, 50001, false),
    constPrefix: jspb.Message.getFieldWithDefault(msg, 50002, ""),
    readOnly: jspb.Message.getBooleanFieldWithDefault(msg, 50003, false),
    vString: jspb.Message.getFieldWithDefault(msg, 50050, ""),
    vUint32: jspb.Message.getFieldWithDefault(msg, 50051, 0),
    vInt32: jspb.Message.getFieldWithDefault(msg, 50052, 0),
    vUint64: jspb.Message.getFieldWithDefault(msg, 50053, 0),
    vInt64: jspb.Message.getFieldWithDefault(msg, 50054, 0),
    vDouble: jspb.Message.getFloatingPointFieldWithDefault(msg, 50055, 0.0),
    vFloat: jspb.Message.getFloatingPointFieldWithDefault(msg, 50056, 0.0),
    vBool: jspb.Message.getBooleanFieldWithDefault(msg, 50057, false),
    vEnum: jspb.Message.getFieldWithDefault(msg, 50058, ""),
    vBytes: msg.getVBytes_asB64(),
    vMsg: msg.getVMsg_asB64(),
    globalName: jspb.Message.getFieldWithDefault(msg, 50005, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.CustomOptions}
 */
proto.CustomOptions.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.CustomOptions;
  return proto.CustomOptions.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.CustomOptions} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.CustomOptions}
 */
proto.CustomOptions.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 50001:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setInitFromMac(value);
      break;
    case 50002:
      var value = /** @type {string} */ (reader.readString());
      msg.setConstPrefix(value);
      break;
    case 50003:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setReadOnly(value);
      break;
    case 50050:
      var value = /** @type {string} */ (reader.readString());
      msg.setVString(value);
      break;
    case 50051:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setVUint32(value);
      break;
    case 50052:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setVInt32(value);
      break;
    case 50053:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setVUint64(value);
      break;
    case 50054:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setVInt64(value);
      break;
    case 50055:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setVDouble(value);
      break;
    case 50056:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setVFloat(value);
      break;
    case 50057:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setVBool(value);
      break;
    case 50058:
      var value = /** @type {string} */ (reader.readString());
      msg.setVEnum(value);
      break;
    case 50059:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setVBytes(value);
      break;
    case 50060:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setVMsg(value);
      break;
    case 50005:
      var value = /** @type {string} */ (reader.readString());
      msg.setGlobalName(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.CustomOptions.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.CustomOptions.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.CustomOptions} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.CustomOptions.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getInitFromMac();
  if (f) {
    writer.writeBool(
      50001,
      f
    );
  }
  f = message.getConstPrefix();
  if (f.length > 0) {
    writer.writeString(
      50002,
      f
    );
  }
  f = message.getReadOnly();
  if (f) {
    writer.writeBool(
      50003,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 50050));
  if (f != null) {
    writer.writeString(
      50050,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 50051));
  if (f != null) {
    writer.writeUint32(
      50051,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 50052));
  if (f != null) {
    writer.writeInt32(
      50052,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 50053));
  if (f != null) {
    writer.writeUint64(
      50053,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 50054));
  if (f != null) {
    writer.writeInt64(
      50054,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 50055));
  if (f != null) {
    writer.writeDouble(
      50055,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 50056));
  if (f != null) {
    writer.writeFloat(
      50056,
      f
    );
  }
  f = /** @type {boolean} */ (jspb.Message.getField(message, 50057));
  if (f != null) {
    writer.writeBool(
      50057,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 50058));
  if (f != null) {
    writer.writeString(
      50058,
      f
    );
  }
  f = /** @type {!(string|Uint8Array)} */ (jspb.Message.getField(message, 50059));
  if (f != null) {
    writer.writeBytes(
      50059,
      f
    );
  }
  f = /** @type {!(string|Uint8Array)} */ (jspb.Message.getField(message, 50060));
  if (f != null) {
    writer.writeBytes(
      50060,
      f
    );
  }
  f = message.getGlobalName();
  if (f.length > 0) {
    writer.writeString(
      50005,
      f
    );
  }
};


/**
 * optional bool init_from_mac = 50001;
 * @return {boolean}
 */
proto.CustomOptions.prototype.getInitFromMac = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 50001, false));
};


/**
 * @param {boolean} value
 * @return {!proto.CustomOptions} returns this
 */
proto.CustomOptions.prototype.setInitFromMac = function(value) {
  return jspb.Message.setProto3BooleanField(this, 50001, value);
};


/**
 * optional string const_prefix = 50002;
 * @return {string}
 */
proto.CustomOptions.prototype.getConstPrefix = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 50002, ""));
};


/**
 * @param {string} value
 * @return {!proto.CustomOptions} returns this
 */
proto.CustomOptions.prototype.setConstPrefix = function(value) {
  return jspb.Message.setProto3StringField(this, 50002, value);
};


/**
 * optional bool read_only = 50003;
 * @return {boolean}
 */
proto.CustomOptions.prototype.getReadOnly = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 50003, false));
};


/**
 * @param {boolean} value
 * @return {!proto.CustomOptions} returns this
 */
proto.CustomOptions.prototype.setReadOnly = function(value) {
  return jspb.Message.setProto3BooleanField(this, 50003, value);
};


/**
 * optional string v_string = 50050;
 * @return {string}
 */
proto.CustomOptions.prototype.getVString = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 50050, ""));
};


/**
 * @param {string} value
 * @return {!proto.CustomOptions} returns this
 */
proto.CustomOptions.prototype.setVString = function(value) {
  return jspb.Message.setOneofField(this, 50050, proto.CustomOptions.oneofGroups_[0], value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.CustomOptions} returns this
 */
proto.CustomOptions.prototype.clearVString = function() {
  return jspb.Message.setOneofField(this, 50050, proto.CustomOptions.oneofGroups_[0], undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.CustomOptions.prototype.hasVString = function() {
  return jspb.Message.getField(this, 50050) != null;
};


/**
 * optional uint32 v_uint32 = 50051;
 * @return {number}
 */
proto.CustomOptions.prototype.getVUint32 = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 50051, 0));
};


/**
 * @param {number} value
 * @return {!proto.CustomOptions} returns this
 */
proto.CustomOptions.prototype.setVUint32 = function(value) {
  return jspb.Message.setOneofField(this, 50051, proto.CustomOptions.oneofGroups_[0], value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.CustomOptions} returns this
 */
proto.CustomOptions.prototype.clearVUint32 = function() {
  return jspb.Message.setOneofField(this, 50051, proto.CustomOptions.oneofGroups_[0], undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.CustomOptions.prototype.hasVUint32 = function() {
  return jspb.Message.getField(this, 50051) != null;
};


/**
 * optional int32 v_int32 = 50052;
 * @return {number}
 */
proto.CustomOptions.prototype.getVInt32 = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 50052, 0));
};


/**
 * @param {number} value
 * @return {!proto.CustomOptions} returns this
 */
proto.CustomOptions.prototype.setVInt32 = function(value) {
  return jspb.Message.setOneofField(this, 50052, proto.CustomOptions.oneofGroups_[0], value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.CustomOptions} returns this
 */
proto.CustomOptions.prototype.clearVInt32 = function() {
  return jspb.Message.setOneofField(this, 50052, proto.CustomOptions.oneofGroups_[0], undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.CustomOptions.prototype.hasVInt32 = function() {
  return jspb.Message.getField(this, 50052) != null;
};


/**
 * optional uint64 v_uint64 = 50053;
 * @return {number}
 */
proto.CustomOptions.prototype.getVUint64 = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 50053, 0));
};


/**
 * @param {number} value
 * @return {!proto.CustomOptions} returns this
 */
proto.CustomOptions.prototype.setVUint64 = function(value) {
  return jspb.Message.setOneofField(this, 50053, proto.CustomOptions.oneofGroups_[0], value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.CustomOptions} returns this
 */
proto.CustomOptions.prototype.clearVUint64 = function() {
  return jspb.Message.setOneofField(this, 50053, proto.CustomOptions.oneofGroups_[0], undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.CustomOptions.prototype.hasVUint64 = function() {
  return jspb.Message.getField(this, 50053) != null;
};


/**
 * optional int64 v_int64 = 50054;
 * @return {number}
 */
proto.CustomOptions.prototype.getVInt64 = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 50054, 0));
};


/**
 * @param {number} value
 * @return {!proto.CustomOptions} returns this
 */
proto.CustomOptions.prototype.setVInt64 = function(value) {
  return jspb.Message.setOneofField(this, 50054, proto.CustomOptions.oneofGroups_[0], value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.CustomOptions} returns this
 */
proto.CustomOptions.prototype.clearVInt64 = function() {
  return jspb.Message.setOneofField(this, 50054, proto.CustomOptions.oneofGroups_[0], undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.CustomOptions.prototype.hasVInt64 = function() {
  return jspb.Message.getField(this, 50054) != null;
};


/**
 * optional double v_double = 50055;
 * @return {number}
 */
proto.CustomOptions.prototype.getVDouble = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 50055, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.CustomOptions} returns this
 */
proto.CustomOptions.prototype.setVDouble = function(value) {
  return jspb.Message.setOneofField(this, 50055, proto.CustomOptions.oneofGroups_[0], value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.CustomOptions} returns this
 */
proto.CustomOptions.prototype.clearVDouble = function() {
  return jspb.Message.setOneofField(this, 50055, proto.CustomOptions.oneofGroups_[0], undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.CustomOptions.prototype.hasVDouble = function() {
  return jspb.Message.getField(this, 50055) != null;
};


/**
 * optional float v_float = 50056;
 * @return {number}
 */
proto.CustomOptions.prototype.getVFloat = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 50056, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.CustomOptions} returns this
 */
proto.CustomOptions.prototype.setVFloat = function(value) {
  return jspb.Message.setOneofField(this, 50056, proto.CustomOptions.oneofGroups_[0], value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.CustomOptions} returns this
 */
proto.CustomOptions.prototype.clearVFloat = function() {
  return jspb.Message.setOneofField(this, 50056, proto.CustomOptions.oneofGroups_[0], undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.CustomOptions.prototype.hasVFloat = function() {
  return jspb.Message.getField(this, 50056) != null;
};


/**
 * optional bool v_bool = 50057;
 * @return {boolean}
 */
proto.CustomOptions.prototype.getVBool = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 50057, false));
};


/**
 * @param {boolean} value
 * @return {!proto.CustomOptions} returns this
 */
proto.CustomOptions.prototype.setVBool = function(value) {
  return jspb.Message.setOneofField(this, 50057, proto.CustomOptions.oneofGroups_[0], value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.CustomOptions} returns this
 */
proto.CustomOptions.prototype.clearVBool = function() {
  return jspb.Message.setOneofField(this, 50057, proto.CustomOptions.oneofGroups_[0], undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.CustomOptions.prototype.hasVBool = function() {
  return jspb.Message.getField(this, 50057) != null;
};


/**
 * optional string v_enum = 50058;
 * @return {string}
 */
proto.CustomOptions.prototype.getVEnum = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 50058, ""));
};


/**
 * @param {string} value
 * @return {!proto.CustomOptions} returns this
 */
proto.CustomOptions.prototype.setVEnum = function(value) {
  return jspb.Message.setOneofField(this, 50058, proto.CustomOptions.oneofGroups_[0], value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.CustomOptions} returns this
 */
proto.CustomOptions.prototype.clearVEnum = function() {
  return jspb.Message.setOneofField(this, 50058, proto.CustomOptions.oneofGroups_[0], undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.CustomOptions.prototype.hasVEnum = function() {
  return jspb.Message.getField(this, 50058) != null;
};


/**
 * optional bytes v_bytes = 50059;
 * @return {!(string|Uint8Array)}
 */
proto.CustomOptions.prototype.getVBytes = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 50059, ""));
};


/**
 * optional bytes v_bytes = 50059;
 * This is a type-conversion wrapper around `getVBytes()`
 * @return {string}
 */
proto.CustomOptions.prototype.getVBytes_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getVBytes()));
};


/**
 * optional bytes v_bytes = 50059;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getVBytes()`
 * @return {!Uint8Array}
 */
proto.CustomOptions.prototype.getVBytes_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getVBytes()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.CustomOptions} returns this
 */
proto.CustomOptions.prototype.setVBytes = function(value) {
  return jspb.Message.setOneofField(this, 50059, proto.CustomOptions.oneofGroups_[0], value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.CustomOptions} returns this
 */
proto.CustomOptions.prototype.clearVBytes = function() {
  return jspb.Message.setOneofField(this, 50059, proto.CustomOptions.oneofGroups_[0], undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.CustomOptions.prototype.hasVBytes = function() {
  return jspb.Message.getField(this, 50059) != null;
};


/**
 * optional bytes v_msg = 50060;
 * @return {!(string|Uint8Array)}
 */
proto.CustomOptions.prototype.getVMsg = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 50060, ""));
};


/**
 * optional bytes v_msg = 50060;
 * This is a type-conversion wrapper around `getVMsg()`
 * @return {string}
 */
proto.CustomOptions.prototype.getVMsg_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getVMsg()));
};


/**
 * optional bytes v_msg = 50060;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getVMsg()`
 * @return {!Uint8Array}
 */
proto.CustomOptions.prototype.getVMsg_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getVMsg()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.CustomOptions} returns this
 */
proto.CustomOptions.prototype.setVMsg = function(value) {
  return jspb.Message.setOneofField(this, 50060, proto.CustomOptions.oneofGroups_[0], value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.CustomOptions} returns this
 */
proto.CustomOptions.prototype.clearVMsg = function() {
  return jspb.Message.setOneofField(this, 50060, proto.CustomOptions.oneofGroups_[0], undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.CustomOptions.prototype.hasVMsg = function() {
  return jspb.Message.getField(this, 50060) != null;
};


/**
 * optional string global_name = 50005;
 * @return {string}
 */
proto.CustomOptions.prototype.getGlobalName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 50005, ""));
};


/**
 * @param {string} value
 * @return {!proto.CustomOptions} returns this
 */
proto.CustomOptions.prototype.setGlobalName = function(value) {
  return jspb.Message.setProto3StringField(this, 50005, value);
};



/**
 * A tuple of {field number, class constructor} for the extension
 * field named `custFile`.
 * @type {!jspb.ExtensionFieldInfo<!proto.CustomOptions>}
 */
proto.custFile = new jspb.ExtensionFieldInfo(
    2010,
    {custFile: 0},
    proto.CustomOptions,
     /** @type {?function((boolean|undefined),!jspb.Message=): !Object} */ (
         proto.CustomOptions.toObject),
    0);

google_protobuf_descriptor_pb.FileOptions.extensionsBinary[2010] = new jspb.ExtensionFieldBinaryInfo(
    proto.custFile,
    jspb.BinaryReader.prototype.readMessage,
    jspb.BinaryWriter.prototype.writeMessage,
    proto.CustomOptions.serializeBinaryToWriter,
    proto.CustomOptions.deserializeBinaryFromReader,
    false);
// This registers the extension field with the extended class, so that
// toObject() will function correctly.
google_protobuf_descriptor_pb.FileOptions.extensions[2010] = proto.custFile;


/**
 * A tuple of {field number, class constructor} for the extension
 * field named `custMsg`.
 * @type {!jspb.ExtensionFieldInfo<!proto.CustomOptions>}
 */
proto.custMsg = new jspb.ExtensionFieldInfo(
    2010,
    {custMsg: 0},
    proto.CustomOptions,
     /** @type {?function((boolean|undefined),!jspb.Message=): !Object} */ (
         proto.CustomOptions.toObject),
    0);

google_protobuf_descriptor_pb.MessageOptions.extensionsBinary[2010] = new jspb.ExtensionFieldBinaryInfo(
    proto.custMsg,
    jspb.BinaryReader.prototype.readMessage,
    jspb.BinaryWriter.prototype.writeMessage,
    proto.CustomOptions.serializeBinaryToWriter,
    proto.CustomOptions.deserializeBinaryFromReader,
    false);
// This registers the extension field with the extended class, so that
// toObject() will function correctly.
google_protobuf_descriptor_pb.MessageOptions.extensions[2010] = proto.custMsg;


/**
 * A tuple of {field number, class constructor} for the extension
 * field named `custEnum`.
 * @type {!jspb.ExtensionFieldInfo<!proto.CustomOptions>}
 */
proto.custEnum = new jspb.ExtensionFieldInfo(
    2010,
    {custEnum: 0},
    proto.CustomOptions,
     /** @type {?function((boolean|undefined),!jspb.Message=): !Object} */ (
         proto.CustomOptions.toObject),
    0);

google_protobuf_descriptor_pb.EnumOptions.extensionsBinary[2010] = new jspb.ExtensionFieldBinaryInfo(
    proto.custEnum,
    jspb.BinaryReader.prototype.readMessage,
    jspb.BinaryWriter.prototype.writeMessage,
    proto.CustomOptions.serializeBinaryToWriter,
    proto.CustomOptions.deserializeBinaryFromReader,
    false);
// This registers the extension field with the extended class, so that
// toObject() will function correctly.
google_protobuf_descriptor_pb.EnumOptions.extensions[2010] = proto.custEnum;


/**
 * A tuple of {field number, class constructor} for the extension
 * field named `custField`.
 * @type {!jspb.ExtensionFieldInfo<!proto.CustomOptions>}
 */
proto.custField = new jspb.ExtensionFieldInfo(
    2010,
    {custField: 0},
    proto.CustomOptions,
     /** @type {?function((boolean|undefined),!jspb.Message=): !Object} */ (
         proto.CustomOptions.toObject),
    0);

google_protobuf_descriptor_pb.FieldOptions.extensionsBinary[2010] = new jspb.ExtensionFieldBinaryInfo(
    proto.custField,
    jspb.BinaryReader.prototype.readMessage,
    jspb.BinaryWriter.prototype.writeMessage,
    proto.CustomOptions.serializeBinaryToWriter,
    proto.CustomOptions.deserializeBinaryFromReader,
    false);
// This registers the extension field with the extended class, so that
// toObject() will function correctly.
google_protobuf_descriptor_pb.FieldOptions.extensions[2010] = proto.custField;

goog.object.extend(exports, proto);
