// source: DAC.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global =
    (typeof globalThis !== 'undefined' && globalThis) ||
    (typeof window !== 'undefined' && window) ||
    (typeof global !== 'undefined' && global) ||
    (typeof self !== 'undefined' && self) ||
    (function () { return this; }).call(null) ||
    Function('return this')();

var GPIO_pb = require('./GPIO_pb.js');
goog.object.extend(proto, GPIO_pb);
var DacControlSet_pb = require('./DacControlSet_pb.js');
goog.object.extend(proto, DacControlSet_pb);
var I2CBus_pb = require('./I2CBus_pb.js');
goog.object.extend(proto, I2CBus_pb);
var customoptions_pb = require('./customoptions_pb.js');
goog.object.extend(proto, customoptions_pb);
var nanopb_pb = require('./nanopb_pb.js');
goog.object.extend(proto, nanopb_pb);
goog.exportSymbol('proto.sys.DAC', null, global);
goog.exportSymbol('proto.sys.DACModelEnum', null, global);
goog.exportSymbol('proto.sys.MCKEnum', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.sys.DAC = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.sys.DAC, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.sys.DAC.displayName = 'proto.sys.DAC';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.sys.DAC.prototype.toObject = function(opt_includeInstance) {
  return proto.sys.DAC.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.sys.DAC} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sys.DAC.toObject = function(includeInstance, msg) {
  var f, obj = {
    bck: (f = msg.getBck()) && GPIO_pb.GPIO.toObject(includeInstance, f),
    ws: (f = msg.getWs()) && GPIO_pb.GPIO.toObject(includeInstance, f),
    dout: (f = msg.getDout()) && GPIO_pb.GPIO.toObject(includeInstance, f),
    mck: jspb.Message.getFieldWithDefault(msg, 4, 0),
    mute: (f = msg.getMute()) && GPIO_pb.GPIO.toObject(includeInstance, f),
    model: jspb.Message.getFieldWithDefault(msg, 6, 0),
    i2c: (f = msg.getI2c()) && I2CBus_pb.I2CBus.toObject(includeInstance, f),
    daccontrolset: (f = msg.getDaccontrolset()) && DacControlSet_pb.DacControlSet.toObject(includeInstance, f),
    jackMutesAmp: jspb.Message.getBooleanFieldWithDefault(msg, 9, false)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.sys.DAC}
 */
proto.sys.DAC.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.sys.DAC;
  return proto.sys.DAC.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.sys.DAC} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.sys.DAC}
 */
proto.sys.DAC.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new GPIO_pb.GPIO;
      reader.readMessage(value,GPIO_pb.GPIO.deserializeBinaryFromReader);
      msg.setBck(value);
      break;
    case 2:
      var value = new GPIO_pb.GPIO;
      reader.readMessage(value,GPIO_pb.GPIO.deserializeBinaryFromReader);
      msg.setWs(value);
      break;
    case 3:
      var value = new GPIO_pb.GPIO;
      reader.readMessage(value,GPIO_pb.GPIO.deserializeBinaryFromReader);
      msg.setDout(value);
      break;
    case 4:
      var value = /** @type {!proto.sys.MCKEnum} */ (reader.readEnum());
      msg.setMck(value);
      break;
    case 5:
      var value = new GPIO_pb.GPIO;
      reader.readMessage(value,GPIO_pb.GPIO.deserializeBinaryFromReader);
      msg.setMute(value);
      break;
    case 6:
      var value = /** @type {!proto.sys.DACModelEnum} */ (reader.readEnum());
      msg.setModel(value);
      break;
    case 7:
      var value = new I2CBus_pb.I2CBus;
      reader.readMessage(value,I2CBus_pb.I2CBus.deserializeBinaryFromReader);
      msg.setI2c(value);
      break;
    case 8:
      var value = new DacControlSet_pb.DacControlSet;
      reader.readMessage(value,DacControlSet_pb.DacControlSet.deserializeBinaryFromReader);
      msg.setDaccontrolset(value);
      break;
    case 9:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setJackMutesAmp(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.sys.DAC.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.sys.DAC.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.sys.DAC} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sys.DAC.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getBck();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      GPIO_pb.GPIO.serializeBinaryToWriter
    );
  }
  f = message.getWs();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      GPIO_pb.GPIO.serializeBinaryToWriter
    );
  }
  f = message.getDout();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      GPIO_pb.GPIO.serializeBinaryToWriter
    );
  }
  f = message.getMck();
  if (f !== 0.0) {
    writer.writeEnum(
      4,
      f
    );
  }
  f = message.getMute();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      GPIO_pb.GPIO.serializeBinaryToWriter
    );
  }
  f = message.getModel();
  if (f !== 0.0) {
    writer.writeEnum(
      6,
      f
    );
  }
  f = message.getI2c();
  if (f != null) {
    writer.writeMessage(
      7,
      f,
      I2CBus_pb.I2CBus.serializeBinaryToWriter
    );
  }
  f = message.getDaccontrolset();
  if (f != null) {
    writer.writeMessage(
      8,
      f,
      DacControlSet_pb.DacControlSet.serializeBinaryToWriter
    );
  }
  f = message.getJackMutesAmp();
  if (f) {
    writer.writeBool(
      9,
      f
    );
  }
};


/**
 * optional GPIO bck = 1;
 * @return {?proto.sys.GPIO}
 */
proto.sys.DAC.prototype.getBck = function() {
  return /** @type{?proto.sys.GPIO} */ (
    jspb.Message.getWrapperField(this, GPIO_pb.GPIO, 1));
};


/**
 * @param {?proto.sys.GPIO|undefined} value
 * @return {!proto.sys.DAC} returns this
*/
proto.sys.DAC.prototype.setBck = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.sys.DAC} returns this
 */
proto.sys.DAC.prototype.clearBck = function() {
  return this.setBck(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sys.DAC.prototype.hasBck = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional GPIO ws = 2;
 * @return {?proto.sys.GPIO}
 */
proto.sys.DAC.prototype.getWs = function() {
  return /** @type{?proto.sys.GPIO} */ (
    jspb.Message.getWrapperField(this, GPIO_pb.GPIO, 2));
};


/**
 * @param {?proto.sys.GPIO|undefined} value
 * @return {!proto.sys.DAC} returns this
*/
proto.sys.DAC.prototype.setWs = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.sys.DAC} returns this
 */
proto.sys.DAC.prototype.clearWs = function() {
  return this.setWs(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sys.DAC.prototype.hasWs = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional GPIO dout = 3;
 * @return {?proto.sys.GPIO}
 */
proto.sys.DAC.prototype.getDout = function() {
  return /** @type{?proto.sys.GPIO} */ (
    jspb.Message.getWrapperField(this, GPIO_pb.GPIO, 3));
};


/**
 * @param {?proto.sys.GPIO|undefined} value
 * @return {!proto.sys.DAC} returns this
*/
proto.sys.DAC.prototype.setDout = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.sys.DAC} returns this
 */
proto.sys.DAC.prototype.clearDout = function() {
  return this.setDout(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sys.DAC.prototype.hasDout = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional MCKEnum mck = 4;
 * @return {!proto.sys.MCKEnum}
 */
proto.sys.DAC.prototype.getMck = function() {
  return /** @type {!proto.sys.MCKEnum} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {!proto.sys.MCKEnum} value
 * @return {!proto.sys.DAC} returns this
 */
proto.sys.DAC.prototype.setMck = function(value) {
  return jspb.Message.setProto3EnumField(this, 4, value);
};


/**
 * optional GPIO mute = 5;
 * @return {?proto.sys.GPIO}
 */
proto.sys.DAC.prototype.getMute = function() {
  return /** @type{?proto.sys.GPIO} */ (
    jspb.Message.getWrapperField(this, GPIO_pb.GPIO, 5));
};


/**
 * @param {?proto.sys.GPIO|undefined} value
 * @return {!proto.sys.DAC} returns this
*/
proto.sys.DAC.prototype.setMute = function(value) {
  return jspb.Message.setWrapperField(this, 5, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.sys.DAC} returns this
 */
proto.sys.DAC.prototype.clearMute = function() {
  return this.setMute(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sys.DAC.prototype.hasMute = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional DACModelEnum model = 6;
 * @return {!proto.sys.DACModelEnum}
 */
proto.sys.DAC.prototype.getModel = function() {
  return /** @type {!proto.sys.DACModelEnum} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/**
 * @param {!proto.sys.DACModelEnum} value
 * @return {!proto.sys.DAC} returns this
 */
proto.sys.DAC.prototype.setModel = function(value) {
  return jspb.Message.setProto3EnumField(this, 6, value);
};


/**
 * optional I2CBus i2c = 7;
 * @return {?proto.sys.I2CBus}
 */
proto.sys.DAC.prototype.getI2c = function() {
  return /** @type{?proto.sys.I2CBus} */ (
    jspb.Message.getWrapperField(this, I2CBus_pb.I2CBus, 7));
};


/**
 * @param {?proto.sys.I2CBus|undefined} value
 * @return {!proto.sys.DAC} returns this
*/
proto.sys.DAC.prototype.setI2c = function(value) {
  return jspb.Message.setWrapperField(this, 7, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.sys.DAC} returns this
 */
proto.sys.DAC.prototype.clearI2c = function() {
  return this.setI2c(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sys.DAC.prototype.hasI2c = function() {
  return jspb.Message.getField(this, 7) != null;
};


/**
 * optional DacControlSet daccontrolset = 8;
 * @return {?proto.sys.DacControlSet}
 */
proto.sys.DAC.prototype.getDaccontrolset = function() {
  return /** @type{?proto.sys.DacControlSet} */ (
    jspb.Message.getWrapperField(this, DacControlSet_pb.DacControlSet, 8));
};


/**
 * @param {?proto.sys.DacControlSet|undefined} value
 * @return {!proto.sys.DAC} returns this
*/
proto.sys.DAC.prototype.setDaccontrolset = function(value) {
  return jspb.Message.setWrapperField(this, 8, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.sys.DAC} returns this
 */
proto.sys.DAC.prototype.clearDaccontrolset = function() {
  return this.setDaccontrolset(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sys.DAC.prototype.hasDaccontrolset = function() {
  return jspb.Message.getField(this, 8) != null;
};


/**
 * optional bool jack_mutes_amp = 9;
 * @return {boolean}
 */
proto.sys.DAC.prototype.getJackMutesAmp = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 9, false));
};


/**
 * @param {boolean} value
 * @return {!proto.sys.DAC} returns this
 */
proto.sys.DAC.prototype.setJackMutesAmp = function(value) {
  return jspb.Message.setProto3BooleanField(this, 9, value);
};


/**
 * @enum {number}
 */
proto.sys.DACModelEnum = {
  UNSPECIFIED_MODEL: 0,
  TAS57XX: 1,
  TAS5713: 2,
  AC101: 3,
  WM8978: 4,
  ES8388: 5,
  I2S: 6,
  CS4265: 7
};

/**
 * @enum {number}
 */
proto.sys.MCKEnum = {
  UNSPECIFIED_MCK: 0,
  MCK0: 1,
  MCK1: 2,
  MCK2: 3
};

goog.object.extend(exports, proto.sys);
