// source: DataRequest.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global =
    (typeof globalThis !== 'undefined' && globalThis) ||
    (typeof window !== 'undefined' && window) ||
    (typeof global !== 'undefined' && global) ||
    (typeof self !== 'undefined' && self) ||
    (function () { return this; }).call(null) ||
    Function('return this')();

var nanopb_pb = require('./nanopb_pb.js');
goog.object.extend(proto, nanopb_pb);
var configuration_pb = require('./configuration_pb.js');
goog.object.extend(proto, configuration_pb);
goog.exportSymbol('proto.sys.request.Action', null, global);
goog.exportSymbol('proto.sys.request.Payload', null, global);
goog.exportSymbol('proto.sys.request.Payload.DataCase', null, global);
goog.exportSymbol('proto.sys.request.Response', null, global);
goog.exportSymbol('proto.sys.request.Result', null, global);
goog.exportSymbol('proto.sys.request.Type', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.sys.request.Payload = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.sys.request.Payload.oneofGroups_);
};
goog.inherits(proto.sys.request.Payload, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.sys.request.Payload.displayName = 'proto.sys.request.Payload';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.sys.request.Response = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.sys.request.Response, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.sys.request.Response.displayName = 'proto.sys.request.Response';
}

/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.sys.request.Payload.oneofGroups_ = [[3,4]];

/**
 * @enum {number}
 */
proto.sys.request.Payload.DataCase = {
  DATA_NOT_SET: 0,
  CONFIG: 3,
  URL: 4
};

/**
 * @return {proto.sys.request.Payload.DataCase}
 */
proto.sys.request.Payload.prototype.getDataCase = function() {
  return /** @type {proto.sys.request.Payload.DataCase} */(jspb.Message.computeOneofCase(this, proto.sys.request.Payload.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.sys.request.Payload.prototype.toObject = function(opt_includeInstance) {
  return proto.sys.request.Payload.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.sys.request.Payload} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sys.request.Payload.toObject = function(includeInstance, msg) {
  var f, obj = {
    type: jspb.Message.getFieldWithDefault(msg, 1, 0),
    action: jspb.Message.getFieldWithDefault(msg, 2, 0),
    config: (f = msg.getConfig()) && configuration_pb.Config.toObject(includeInstance, f),
    url: jspb.Message.getFieldWithDefault(msg, 4, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.sys.request.Payload}
 */
proto.sys.request.Payload.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.sys.request.Payload;
  return proto.sys.request.Payload.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.sys.request.Payload} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.sys.request.Payload}
 */
proto.sys.request.Payload.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.sys.request.Type} */ (reader.readEnum());
      msg.setType(value);
      break;
    case 2:
      var value = /** @type {!proto.sys.request.Action} */ (reader.readEnum());
      msg.setAction(value);
      break;
    case 3:
      var value = new configuration_pb.Config;
      reader.readMessage(value,configuration_pb.Config.deserializeBinaryFromReader);
      msg.setConfig(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setUrl(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.sys.request.Payload.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.sys.request.Payload.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.sys.request.Payload} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sys.request.Payload.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getType();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getAction();
  if (f !== 0.0) {
    writer.writeEnum(
      2,
      f
    );
  }
  f = message.getConfig();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      configuration_pb.Config.serializeBinaryToWriter
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 4));
  if (f != null) {
    writer.writeString(
      4,
      f
    );
  }
};


/**
 * optional Type type = 1;
 * @return {!proto.sys.request.Type}
 */
proto.sys.request.Payload.prototype.getType = function() {
  return /** @type {!proto.sys.request.Type} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {!proto.sys.request.Type} value
 * @return {!proto.sys.request.Payload} returns this
 */
proto.sys.request.Payload.prototype.setType = function(value) {
  return jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * optional Action action = 2;
 * @return {!proto.sys.request.Action}
 */
proto.sys.request.Payload.prototype.getAction = function() {
  return /** @type {!proto.sys.request.Action} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {!proto.sys.request.Action} value
 * @return {!proto.sys.request.Payload} returns this
 */
proto.sys.request.Payload.prototype.setAction = function(value) {
  return jspb.Message.setProto3EnumField(this, 2, value);
};


/**
 * optional sys.Config config = 3;
 * @return {?proto.sys.Config}
 */
proto.sys.request.Payload.prototype.getConfig = function() {
  return /** @type{?proto.sys.Config} */ (
    jspb.Message.getWrapperField(this, configuration_pb.Config, 3));
};


/**
 * @param {?proto.sys.Config|undefined} value
 * @return {!proto.sys.request.Payload} returns this
*/
proto.sys.request.Payload.prototype.setConfig = function(value) {
  return jspb.Message.setOneofWrapperField(this, 3, proto.sys.request.Payload.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.sys.request.Payload} returns this
 */
proto.sys.request.Payload.prototype.clearConfig = function() {
  return this.setConfig(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sys.request.Payload.prototype.hasConfig = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional string URL = 4;
 * @return {string}
 */
proto.sys.request.Payload.prototype.getUrl = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.sys.request.Payload} returns this
 */
proto.sys.request.Payload.prototype.setUrl = function(value) {
  return jspb.Message.setOneofField(this, 4, proto.sys.request.Payload.oneofGroups_[0], value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.sys.request.Payload} returns this
 */
proto.sys.request.Payload.prototype.clearUrl = function() {
  return jspb.Message.setOneofField(this, 4, proto.sys.request.Payload.oneofGroups_[0], undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sys.request.Payload.prototype.hasUrl = function() {
  return jspb.Message.getField(this, 4) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.sys.request.Response.prototype.toObject = function(opt_includeInstance) {
  return proto.sys.request.Response.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.sys.request.Response} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sys.request.Response.toObject = function(includeInstance, msg) {
  var f, obj = {
    result: jspb.Message.getFieldWithDefault(msg, 1, 0),
    message: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.sys.request.Response}
 */
proto.sys.request.Response.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.sys.request.Response;
  return proto.sys.request.Response.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.sys.request.Response} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.sys.request.Response}
 */
proto.sys.request.Response.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.sys.request.Result} */ (reader.readEnum());
      msg.setResult(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setMessage(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.sys.request.Response.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.sys.request.Response.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.sys.request.Response} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sys.request.Response.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getResult();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getMessage();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional Result result = 1;
 * @return {!proto.sys.request.Result}
 */
proto.sys.request.Response.prototype.getResult = function() {
  return /** @type {!proto.sys.request.Result} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {!proto.sys.request.Result} value
 * @return {!proto.sys.request.Response} returns this
 */
proto.sys.request.Response.prototype.setResult = function(value) {
  return jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * optional string message = 2;
 * @return {string}
 */
proto.sys.request.Response.prototype.getMessage = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.sys.request.Response} returns this
 */
proto.sys.request.Response.prototype.setMessage = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * @enum {number}
 */
proto.sys.request.Type = {
  UNKNOWN: 0,
  CONFIG: 1,
  STATUS: 2,
  MESSAGE: 3,
  RESTART: 4,
  NETWORK: 5,
  OTA: 6,
  SCAN: 7
};

/**
 * @enum {number}
 */
proto.sys.request.Action = {
  UNKNOWN_ACTION: 0,
  SET: 1,
  GET: 2
};

/**
 * @enum {number}
 */
proto.sys.request.Result = {
  UNKNOWN_RESULT: 0,
  SUCCESS: 1,
  ERROR: 2
};

goog.object.extend(exports, proto.sys.request);
