// source: Display.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global =
    (typeof globalThis !== 'undefined' && globalThis) ||
    (typeof window !== 'undefined' && window) ||
    (typeof global !== 'undefined' && global) ||
    (typeof self !== 'undefined' && self) ||
    (function () { return this; }).call(null) ||
    Function('return this')();

var GPIO_pb = require('./GPIO_pb.js');
goog.object.extend(proto, GPIO_pb);
var Common_pb = require('./Common_pb.js');
goog.object.extend(proto, Common_pb);
var nanopb_pb = require('./nanopb_pb.js');
goog.object.extend(proto, nanopb_pb);
goog.exportSymbol('proto.sys.DispCommon', null, global);
goog.exportSymbol('proto.sys.DispOffsets', null, global);
goog.exportSymbol('proto.sys.Display', null, global);
goog.exportSymbol('proto.sys.Display.DisptypeCase', null, global);
goog.exportSymbol('proto.sys.DisplayDriverEnum', null, global);
goog.exportSymbol('proto.sys.I2CDisplay', null, global);
goog.exportSymbol('proto.sys.SPIDisplay', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.sys.DispOffsets = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.sys.DispOffsets, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.sys.DispOffsets.displayName = 'proto.sys.DispOffsets';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.sys.I2CDisplay = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.sys.I2CDisplay, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.sys.I2CDisplay.displayName = 'proto.sys.I2CDisplay';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.sys.SPIDisplay = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.sys.SPIDisplay, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.sys.SPIDisplay.displayName = 'proto.sys.SPIDisplay';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.sys.DispCommon = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.sys.DispCommon, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.sys.DispCommon.displayName = 'proto.sys.DispCommon';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.sys.Display = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.sys.Display.oneofGroups_);
};
goog.inherits(proto.sys.Display, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.sys.Display.displayName = 'proto.sys.Display';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.sys.DispOffsets.prototype.toObject = function(opt_includeInstance) {
  return proto.sys.DispOffsets.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.sys.DispOffsets} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sys.DispOffsets.toObject = function(includeInstance, msg) {
  var f, obj = {
    height: jspb.Message.getFieldWithDefault(msg, 1, 0),
    width: jspb.Message.getFieldWithDefault(msg, 2, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.sys.DispOffsets}
 */
proto.sys.DispOffsets.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.sys.DispOffsets;
  return proto.sys.DispOffsets.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.sys.DispOffsets} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.sys.DispOffsets}
 */
proto.sys.DispOffsets.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setHeight(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setWidth(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.sys.DispOffsets.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.sys.DispOffsets.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.sys.DispOffsets} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sys.DispOffsets.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getHeight();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getWidth();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
};


/**
 * optional int32 height = 1;
 * @return {number}
 */
proto.sys.DispOffsets.prototype.getHeight = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.sys.DispOffsets} returns this
 */
proto.sys.DispOffsets.prototype.setHeight = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional int32 width = 2;
 * @return {number}
 */
proto.sys.DispOffsets.prototype.getWidth = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.sys.DispOffsets} returns this
 */
proto.sys.DispOffsets.prototype.setWidth = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.sys.I2CDisplay.prototype.toObject = function(opt_includeInstance) {
  return proto.sys.I2CDisplay.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.sys.I2CDisplay} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sys.I2CDisplay.toObject = function(includeInstance, msg) {
  var f, obj = {
    address: jspb.Message.getFieldWithDefault(msg, 1, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.sys.I2CDisplay}
 */
proto.sys.I2CDisplay.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.sys.I2CDisplay;
  return proto.sys.I2CDisplay.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.sys.I2CDisplay} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.sys.I2CDisplay}
 */
proto.sys.I2CDisplay.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setAddress(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.sys.I2CDisplay.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.sys.I2CDisplay.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.sys.I2CDisplay} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sys.I2CDisplay.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getAddress();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
};


/**
 * optional int32 address = 1;
 * @return {number}
 */
proto.sys.I2CDisplay.prototype.getAddress = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.sys.I2CDisplay} returns this
 */
proto.sys.I2CDisplay.prototype.setAddress = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.sys.SPIDisplay.prototype.toObject = function(opt_includeInstance) {
  return proto.sys.SPIDisplay.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.sys.SPIDisplay} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sys.SPIDisplay.toObject = function(includeInstance, msg) {
  var f, obj = {
    cs: (f = msg.getCs()) && GPIO_pb.GPIO.toObject(includeInstance, f),
    speed: jspb.Message.getFieldWithDefault(msg, 4, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.sys.SPIDisplay}
 */
proto.sys.SPIDisplay.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.sys.SPIDisplay;
  return proto.sys.SPIDisplay.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.sys.SPIDisplay} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.sys.SPIDisplay}
 */
proto.sys.SPIDisplay.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new GPIO_pb.GPIO;
      reader.readMessage(value,GPIO_pb.GPIO.deserializeBinaryFromReader);
      msg.setCs(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setSpeed(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.sys.SPIDisplay.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.sys.SPIDisplay.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.sys.SPIDisplay} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sys.SPIDisplay.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getCs();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      GPIO_pb.GPIO.serializeBinaryToWriter
    );
  }
  f = message.getSpeed();
  if (f !== 0) {
    writer.writeInt32(
      4,
      f
    );
  }
};


/**
 * optional GPIO cs = 1;
 * @return {?proto.sys.GPIO}
 */
proto.sys.SPIDisplay.prototype.getCs = function() {
  return /** @type{?proto.sys.GPIO} */ (
    jspb.Message.getWrapperField(this, GPIO_pb.GPIO, 1));
};


/**
 * @param {?proto.sys.GPIO|undefined} value
 * @return {!proto.sys.SPIDisplay} returns this
*/
proto.sys.SPIDisplay.prototype.setCs = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.sys.SPIDisplay} returns this
 */
proto.sys.SPIDisplay.prototype.clearCs = function() {
  return this.setCs(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sys.SPIDisplay.prototype.hasCs = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional int32 speed = 4;
 * @return {number}
 */
proto.sys.SPIDisplay.prototype.getSpeed = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.sys.SPIDisplay} returns this
 */
proto.sys.SPIDisplay.prototype.setSpeed = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.sys.DispCommon.prototype.toObject = function(opt_includeInstance) {
  return proto.sys.DispCommon.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.sys.DispCommon} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sys.DispCommon.toObject = function(includeInstance, msg) {
  var f, obj = {
    width: jspb.Message.getFieldWithDefault(msg, 1, 0),
    height: jspb.Message.getFieldWithDefault(msg, 2, 0),
    hflip: jspb.Message.getBooleanFieldWithDefault(msg, 3, false),
    vflip: jspb.Message.getBooleanFieldWithDefault(msg, 4, false),
    driver: jspb.Message.getFieldWithDefault(msg, 5, 0),
    bitdepth: jspb.Message.getFieldWithDefault(msg, 6, 0),
    back: (f = msg.getBack()) && GPIO_pb.GPIO.toObject(includeInstance, f),
    reset: (f = msg.getReset()) && GPIO_pb.GPIO.toObject(includeInstance, f),
    ready: (f = msg.getReady()) && GPIO_pb.GPIO.toObject(includeInstance, f),
    offsets: (f = msg.getOffsets()) && proto.sys.DispOffsets.toObject(includeInstance, f),
    rotate: jspb.Message.getBooleanFieldWithDefault(msg, 11, false),
    invert: jspb.Message.getBooleanFieldWithDefault(msg, 12, false),
    colowSwap: jspb.Message.getBooleanFieldWithDefault(msg, 13, false)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.sys.DispCommon}
 */
proto.sys.DispCommon.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.sys.DispCommon;
  return proto.sys.DispCommon.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.sys.DispCommon} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.sys.DispCommon}
 */
proto.sys.DispCommon.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setWidth(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setHeight(value);
      break;
    case 3:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setHflip(value);
      break;
    case 4:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setVflip(value);
      break;
    case 5:
      var value = /** @type {!proto.sys.DisplayDriverEnum} */ (reader.readEnum());
      msg.setDriver(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setBitdepth(value);
      break;
    case 7:
      var value = new GPIO_pb.GPIO;
      reader.readMessage(value,GPIO_pb.GPIO.deserializeBinaryFromReader);
      msg.setBack(value);
      break;
    case 8:
      var value = new GPIO_pb.GPIO;
      reader.readMessage(value,GPIO_pb.GPIO.deserializeBinaryFromReader);
      msg.setReset(value);
      break;
    case 9:
      var value = new GPIO_pb.GPIO;
      reader.readMessage(value,GPIO_pb.GPIO.deserializeBinaryFromReader);
      msg.setReady(value);
      break;
    case 10:
      var value = new proto.sys.DispOffsets;
      reader.readMessage(value,proto.sys.DispOffsets.deserializeBinaryFromReader);
      msg.setOffsets(value);
      break;
    case 11:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setRotate(value);
      break;
    case 12:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setInvert(value);
      break;
    case 13:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setColowSwap(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.sys.DispCommon.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.sys.DispCommon.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.sys.DispCommon} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sys.DispCommon.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getWidth();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getHeight();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
  f = message.getHflip();
  if (f) {
    writer.writeBool(
      3,
      f
    );
  }
  f = message.getVflip();
  if (f) {
    writer.writeBool(
      4,
      f
    );
  }
  f = message.getDriver();
  if (f !== 0.0) {
    writer.writeEnum(
      5,
      f
    );
  }
  f = message.getBitdepth();
  if (f !== 0) {
    writer.writeInt32(
      6,
      f
    );
  }
  f = message.getBack();
  if (f != null) {
    writer.writeMessage(
      7,
      f,
      GPIO_pb.GPIO.serializeBinaryToWriter
    );
  }
  f = message.getReset();
  if (f != null) {
    writer.writeMessage(
      8,
      f,
      GPIO_pb.GPIO.serializeBinaryToWriter
    );
  }
  f = message.getReady();
  if (f != null) {
    writer.writeMessage(
      9,
      f,
      GPIO_pb.GPIO.serializeBinaryToWriter
    );
  }
  f = message.getOffsets();
  if (f != null) {
    writer.writeMessage(
      10,
      f,
      proto.sys.DispOffsets.serializeBinaryToWriter
    );
  }
  f = message.getRotate();
  if (f) {
    writer.writeBool(
      11,
      f
    );
  }
  f = message.getInvert();
  if (f) {
    writer.writeBool(
      12,
      f
    );
  }
  f = message.getColowSwap();
  if (f) {
    writer.writeBool(
      13,
      f
    );
  }
};


/**
 * optional int32 width = 1;
 * @return {number}
 */
proto.sys.DispCommon.prototype.getWidth = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.sys.DispCommon} returns this
 */
proto.sys.DispCommon.prototype.setWidth = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional int32 height = 2;
 * @return {number}
 */
proto.sys.DispCommon.prototype.getHeight = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.sys.DispCommon} returns this
 */
proto.sys.DispCommon.prototype.setHeight = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional bool HFlip = 3;
 * @return {boolean}
 */
proto.sys.DispCommon.prototype.getHflip = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 3, false));
};


/**
 * @param {boolean} value
 * @return {!proto.sys.DispCommon} returns this
 */
proto.sys.DispCommon.prototype.setHflip = function(value) {
  return jspb.Message.setProto3BooleanField(this, 3, value);
};


/**
 * optional bool VFlip = 4;
 * @return {boolean}
 */
proto.sys.DispCommon.prototype.getVflip = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 4, false));
};


/**
 * @param {boolean} value
 * @return {!proto.sys.DispCommon} returns this
 */
proto.sys.DispCommon.prototype.setVflip = function(value) {
  return jspb.Message.setProto3BooleanField(this, 4, value);
};


/**
 * optional DisplayDriverEnum driver = 5;
 * @return {!proto.sys.DisplayDriverEnum}
 */
proto.sys.DispCommon.prototype.getDriver = function() {
  return /** @type {!proto.sys.DisplayDriverEnum} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {!proto.sys.DisplayDriverEnum} value
 * @return {!proto.sys.DispCommon} returns this
 */
proto.sys.DispCommon.prototype.setDriver = function(value) {
  return jspb.Message.setProto3EnumField(this, 5, value);
};


/**
 * optional int32 bitDepth = 6;
 * @return {number}
 */
proto.sys.DispCommon.prototype.getBitdepth = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/**
 * @param {number} value
 * @return {!proto.sys.DispCommon} returns this
 */
proto.sys.DispCommon.prototype.setBitdepth = function(value) {
  return jspb.Message.setProto3IntField(this, 6, value);
};


/**
 * optional GPIO back = 7;
 * @return {?proto.sys.GPIO}
 */
proto.sys.DispCommon.prototype.getBack = function() {
  return /** @type{?proto.sys.GPIO} */ (
    jspb.Message.getWrapperField(this, GPIO_pb.GPIO, 7));
};


/**
 * @param {?proto.sys.GPIO|undefined} value
 * @return {!proto.sys.DispCommon} returns this
*/
proto.sys.DispCommon.prototype.setBack = function(value) {
  return jspb.Message.setWrapperField(this, 7, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.sys.DispCommon} returns this
 */
proto.sys.DispCommon.prototype.clearBack = function() {
  return this.setBack(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sys.DispCommon.prototype.hasBack = function() {
  return jspb.Message.getField(this, 7) != null;
};


/**
 * optional GPIO reset = 8;
 * @return {?proto.sys.GPIO}
 */
proto.sys.DispCommon.prototype.getReset = function() {
  return /** @type{?proto.sys.GPIO} */ (
    jspb.Message.getWrapperField(this, GPIO_pb.GPIO, 8));
};


/**
 * @param {?proto.sys.GPIO|undefined} value
 * @return {!proto.sys.DispCommon} returns this
*/
proto.sys.DispCommon.prototype.setReset = function(value) {
  return jspb.Message.setWrapperField(this, 8, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.sys.DispCommon} returns this
 */
proto.sys.DispCommon.prototype.clearReset = function() {
  return this.setReset(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sys.DispCommon.prototype.hasReset = function() {
  return jspb.Message.getField(this, 8) != null;
};


/**
 * optional GPIO ready = 9;
 * @return {?proto.sys.GPIO}
 */
proto.sys.DispCommon.prototype.getReady = function() {
  return /** @type{?proto.sys.GPIO} */ (
    jspb.Message.getWrapperField(this, GPIO_pb.GPIO, 9));
};


/**
 * @param {?proto.sys.GPIO|undefined} value
 * @return {!proto.sys.DispCommon} returns this
*/
proto.sys.DispCommon.prototype.setReady = function(value) {
  return jspb.Message.setWrapperField(this, 9, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.sys.DispCommon} returns this
 */
proto.sys.DispCommon.prototype.clearReady = function() {
  return this.setReady(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sys.DispCommon.prototype.hasReady = function() {
  return jspb.Message.getField(this, 9) != null;
};


/**
 * optional DispOffsets offsets = 10;
 * @return {?proto.sys.DispOffsets}
 */
proto.sys.DispCommon.prototype.getOffsets = function() {
  return /** @type{?proto.sys.DispOffsets} */ (
    jspb.Message.getWrapperField(this, proto.sys.DispOffsets, 10));
};


/**
 * @param {?proto.sys.DispOffsets|undefined} value
 * @return {!proto.sys.DispCommon} returns this
*/
proto.sys.DispCommon.prototype.setOffsets = function(value) {
  return jspb.Message.setWrapperField(this, 10, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.sys.DispCommon} returns this
 */
proto.sys.DispCommon.prototype.clearOffsets = function() {
  return this.setOffsets(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sys.DispCommon.prototype.hasOffsets = function() {
  return jspb.Message.getField(this, 10) != null;
};


/**
 * optional bool rotate = 11;
 * @return {boolean}
 */
proto.sys.DispCommon.prototype.getRotate = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 11, false));
};


/**
 * @param {boolean} value
 * @return {!proto.sys.DispCommon} returns this
 */
proto.sys.DispCommon.prototype.setRotate = function(value) {
  return jspb.Message.setProto3BooleanField(this, 11, value);
};


/**
 * optional bool invert = 12;
 * @return {boolean}
 */
proto.sys.DispCommon.prototype.getInvert = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 12, false));
};


/**
 * @param {boolean} value
 * @return {!proto.sys.DispCommon} returns this
 */
proto.sys.DispCommon.prototype.setInvert = function(value) {
  return jspb.Message.setProto3BooleanField(this, 12, value);
};


/**
 * optional bool colow_swap = 13;
 * @return {boolean}
 */
proto.sys.DispCommon.prototype.getColowSwap = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 13, false));
};


/**
 * @param {boolean} value
 * @return {!proto.sys.DispCommon} returns this
 */
proto.sys.DispCommon.prototype.setColowSwap = function(value) {
  return jspb.Message.setProto3BooleanField(this, 13, value);
};



/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.sys.Display.oneofGroups_ = [[3,4]];

/**
 * @enum {number}
 */
proto.sys.Display.DisptypeCase = {
  DISPTYPE_NOT_SET: 0,
  I2C: 3,
  SPI: 4
};

/**
 * @return {proto.sys.Display.DisptypeCase}
 */
proto.sys.Display.prototype.getDisptypeCase = function() {
  return /** @type {proto.sys.Display.DisptypeCase} */(jspb.Message.computeOneofCase(this, proto.sys.Display.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.sys.Display.prototype.toObject = function(opt_includeInstance) {
  return proto.sys.Display.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.sys.Display} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sys.Display.toObject = function(includeInstance, msg) {
  var f, obj = {
    type: jspb.Message.getFieldWithDefault(msg, 1, 0),
    common: (f = msg.getCommon()) && proto.sys.DispCommon.toObject(includeInstance, f),
    i2c: (f = msg.getI2c()) && proto.sys.I2CDisplay.toObject(includeInstance, f),
    spi: (f = msg.getSpi()) && proto.sys.SPIDisplay.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.sys.Display}
 */
proto.sys.Display.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.sys.Display;
  return proto.sys.Display.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.sys.Display} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.sys.Display}
 */
proto.sys.Display.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.sys.DeviceTypeEnum} */ (reader.readEnum());
      msg.setType(value);
      break;
    case 2:
      var value = new proto.sys.DispCommon;
      reader.readMessage(value,proto.sys.DispCommon.deserializeBinaryFromReader);
      msg.setCommon(value);
      break;
    case 3:
      var value = new proto.sys.I2CDisplay;
      reader.readMessage(value,proto.sys.I2CDisplay.deserializeBinaryFromReader);
      msg.setI2c(value);
      break;
    case 4:
      var value = new proto.sys.SPIDisplay;
      reader.readMessage(value,proto.sys.SPIDisplay.deserializeBinaryFromReader);
      msg.setSpi(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.sys.Display.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.sys.Display.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.sys.Display} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sys.Display.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getType();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getCommon();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.sys.DispCommon.serializeBinaryToWriter
    );
  }
  f = message.getI2c();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.sys.I2CDisplay.serializeBinaryToWriter
    );
  }
  f = message.getSpi();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      proto.sys.SPIDisplay.serializeBinaryToWriter
    );
  }
};


/**
 * optional DeviceTypeEnum type = 1;
 * @return {!proto.sys.DeviceTypeEnum}
 */
proto.sys.Display.prototype.getType = function() {
  return /** @type {!proto.sys.DeviceTypeEnum} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {!proto.sys.DeviceTypeEnum} value
 * @return {!proto.sys.Display} returns this
 */
proto.sys.Display.prototype.setType = function(value) {
  return jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * optional DispCommon common = 2;
 * @return {?proto.sys.DispCommon}
 */
proto.sys.Display.prototype.getCommon = function() {
  return /** @type{?proto.sys.DispCommon} */ (
    jspb.Message.getWrapperField(this, proto.sys.DispCommon, 2));
};


/**
 * @param {?proto.sys.DispCommon|undefined} value
 * @return {!proto.sys.Display} returns this
*/
proto.sys.Display.prototype.setCommon = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.sys.Display} returns this
 */
proto.sys.Display.prototype.clearCommon = function() {
  return this.setCommon(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sys.Display.prototype.hasCommon = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional I2CDisplay i2c = 3;
 * @return {?proto.sys.I2CDisplay}
 */
proto.sys.Display.prototype.getI2c = function() {
  return /** @type{?proto.sys.I2CDisplay} */ (
    jspb.Message.getWrapperField(this, proto.sys.I2CDisplay, 3));
};


/**
 * @param {?proto.sys.I2CDisplay|undefined} value
 * @return {!proto.sys.Display} returns this
*/
proto.sys.Display.prototype.setI2c = function(value) {
  return jspb.Message.setOneofWrapperField(this, 3, proto.sys.Display.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.sys.Display} returns this
 */
proto.sys.Display.prototype.clearI2c = function() {
  return this.setI2c(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sys.Display.prototype.hasI2c = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional SPIDisplay spi = 4;
 * @return {?proto.sys.SPIDisplay}
 */
proto.sys.Display.prototype.getSpi = function() {
  return /** @type{?proto.sys.SPIDisplay} */ (
    jspb.Message.getWrapperField(this, proto.sys.SPIDisplay, 4));
};


/**
 * @param {?proto.sys.SPIDisplay|undefined} value
 * @return {!proto.sys.Display} returns this
*/
proto.sys.Display.prototype.setSpi = function(value) {
  return jspb.Message.setOneofWrapperField(this, 4, proto.sys.Display.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.sys.Display} returns this
 */
proto.sys.Display.prototype.clearSpi = function() {
  return this.setSpi(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sys.Display.prototype.hasSpi = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * @enum {number}
 */
proto.sys.DisplayDriverEnum = {
  UNSPECIFIED_DRIVER: 0,
  SSD1306: 1,
  SSD1322: 2,
  SSD1326: 3,
  SSD1327: 4,
  SH1106: 5,
  SSD1675: 6,
  ST7735: 7,
  ST7789: 8,
  ILI9341: 9,
  ILI9341_24: 10,
  SSD1351: 11
};

goog.object.extend(exports, proto.sys);
