// source: Ethernet.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global =
    (typeof globalThis !== 'undefined' && globalThis) ||
    (typeof window !== 'undefined' && window) ||
    (typeof global !== 'undefined' && global) ||
    (typeof self !== 'undefined' && self) ||
    (function () { return this; }).call(null) ||
    Function('return this')();

var Common_pb = require('./Common_pb.js');
goog.object.extend(proto, Common_pb);
var GPIO_pb = require('./GPIO_pb.js');
goog.object.extend(proto, GPIO_pb);
var nanopb_pb = require('./nanopb_pb.js');
goog.object.extend(proto, nanopb_pb);
var customoptions_pb = require('./customoptions_pb.js');
goog.object.extend(proto, customoptions_pb);
goog.exportSymbol('proto.sys.Eth', null, global);
goog.exportSymbol('proto.sys.Eth.EthtypeCase', null, global);
goog.exportSymbol('proto.sys.EthCommon', null, global);
goog.exportSymbol('proto.sys.EthModelEnum', null, global);
goog.exportSymbol('proto.sys.EthRMII', null, global);
goog.exportSymbol('proto.sys.EthSPI', null, global);
goog.exportSymbol('proto.sys.EthType', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.sys.EthCommon = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.sys.EthCommon, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.sys.EthCommon.displayName = 'proto.sys.EthCommon';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.sys.EthSPI = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.sys.EthSPI, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.sys.EthSPI.displayName = 'proto.sys.EthSPI';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.sys.EthRMII = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.sys.EthRMII, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.sys.EthRMII.displayName = 'proto.sys.EthRMII';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.sys.Eth = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.sys.Eth.oneofGroups_);
};
goog.inherits(proto.sys.Eth, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.sys.Eth.displayName = 'proto.sys.Eth';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.sys.EthCommon.prototype.toObject = function(opt_includeInstance) {
  return proto.sys.EthCommon.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.sys.EthCommon} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sys.EthCommon.toObject = function(includeInstance, msg) {
  var f, obj = {
    model: jspb.Message.getFieldWithDefault(msg, 1, 0),
    rst: (f = msg.getRst()) && GPIO_pb.GPIO.toObject(includeInstance, f),
    ethtmoutS: jspb.Message.getFieldWithDefault(msg, 3, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.sys.EthCommon}
 */
proto.sys.EthCommon.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.sys.EthCommon;
  return proto.sys.EthCommon.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.sys.EthCommon} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.sys.EthCommon}
 */
proto.sys.EthCommon.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.sys.EthModelEnum} */ (reader.readEnum());
      msg.setModel(value);
      break;
    case 2:
      var value = new GPIO_pb.GPIO;
      reader.readMessage(value,GPIO_pb.GPIO.deserializeBinaryFromReader);
      msg.setRst(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setEthtmoutS(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.sys.EthCommon.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.sys.EthCommon.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.sys.EthCommon} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sys.EthCommon.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getModel();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getRst();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      GPIO_pb.GPIO.serializeBinaryToWriter
    );
  }
  f = message.getEthtmoutS();
  if (f !== 0) {
    writer.writeUint32(
      3,
      f
    );
  }
};


/**
 * optional EthModelEnum model = 1;
 * @return {!proto.sys.EthModelEnum}
 */
proto.sys.EthCommon.prototype.getModel = function() {
  return /** @type {!proto.sys.EthModelEnum} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {!proto.sys.EthModelEnum} value
 * @return {!proto.sys.EthCommon} returns this
 */
proto.sys.EthCommon.prototype.setModel = function(value) {
  return jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * optional GPIO rst = 2;
 * @return {?proto.sys.GPIO}
 */
proto.sys.EthCommon.prototype.getRst = function() {
  return /** @type{?proto.sys.GPIO} */ (
    jspb.Message.getWrapperField(this, GPIO_pb.GPIO, 2));
};


/**
 * @param {?proto.sys.GPIO|undefined} value
 * @return {!proto.sys.EthCommon} returns this
*/
proto.sys.EthCommon.prototype.setRst = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.sys.EthCommon} returns this
 */
proto.sys.EthCommon.prototype.clearRst = function() {
  return this.setRst(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sys.EthCommon.prototype.hasRst = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional uint32 ethtmout_s = 3;
 * @return {number}
 */
proto.sys.EthCommon.prototype.getEthtmoutS = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.sys.EthCommon} returns this
 */
proto.sys.EthCommon.prototype.setEthtmoutS = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.sys.EthSPI.prototype.toObject = function(opt_includeInstance) {
  return proto.sys.EthSPI.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.sys.EthSPI} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sys.EthSPI.toObject = function(includeInstance, msg) {
  var f, obj = {
    cs: (f = msg.getCs()) && GPIO_pb.GPIO.toObject(includeInstance, f),
    speed: jspb.Message.getFieldWithDefault(msg, 2, 0),
    intr: (f = msg.getIntr()) && GPIO_pb.GPIO.toObject(includeInstance, f),
    host: jspb.Message.getFieldWithDefault(msg, 4, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.sys.EthSPI}
 */
proto.sys.EthSPI.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.sys.EthSPI;
  return proto.sys.EthSPI.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.sys.EthSPI} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.sys.EthSPI}
 */
proto.sys.EthSPI.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new GPIO_pb.GPIO;
      reader.readMessage(value,GPIO_pb.GPIO.deserializeBinaryFromReader);
      msg.setCs(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setSpeed(value);
      break;
    case 3:
      var value = new GPIO_pb.GPIO;
      reader.readMessage(value,GPIO_pb.GPIO.deserializeBinaryFromReader);
      msg.setIntr(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setHost(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.sys.EthSPI.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.sys.EthSPI.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.sys.EthSPI} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sys.EthSPI.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getCs();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      GPIO_pb.GPIO.serializeBinaryToWriter
    );
  }
  f = message.getSpeed();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
  f = message.getIntr();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      GPIO_pb.GPIO.serializeBinaryToWriter
    );
  }
  f = message.getHost();
  if (f !== 0) {
    writer.writeInt32(
      4,
      f
    );
  }
};


/**
 * optional GPIO cs = 1;
 * @return {?proto.sys.GPIO}
 */
proto.sys.EthSPI.prototype.getCs = function() {
  return /** @type{?proto.sys.GPIO} */ (
    jspb.Message.getWrapperField(this, GPIO_pb.GPIO, 1));
};


/**
 * @param {?proto.sys.GPIO|undefined} value
 * @return {!proto.sys.EthSPI} returns this
*/
proto.sys.EthSPI.prototype.setCs = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.sys.EthSPI} returns this
 */
proto.sys.EthSPI.prototype.clearCs = function() {
  return this.setCs(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sys.EthSPI.prototype.hasCs = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional int32 speed = 2;
 * @return {number}
 */
proto.sys.EthSPI.prototype.getSpeed = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.sys.EthSPI} returns this
 */
proto.sys.EthSPI.prototype.setSpeed = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional GPIO intr = 3;
 * @return {?proto.sys.GPIO}
 */
proto.sys.EthSPI.prototype.getIntr = function() {
  return /** @type{?proto.sys.GPIO} */ (
    jspb.Message.getWrapperField(this, GPIO_pb.GPIO, 3));
};


/**
 * @param {?proto.sys.GPIO|undefined} value
 * @return {!proto.sys.EthSPI} returns this
*/
proto.sys.EthSPI.prototype.setIntr = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.sys.EthSPI} returns this
 */
proto.sys.EthSPI.prototype.clearIntr = function() {
  return this.setIntr(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sys.EthSPI.prototype.hasIntr = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional int32 host = 4;
 * @return {number}
 */
proto.sys.EthSPI.prototype.getHost = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.sys.EthSPI} returns this
 */
proto.sys.EthSPI.prototype.setHost = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.sys.EthRMII.prototype.toObject = function(opt_includeInstance) {
  return proto.sys.EthRMII.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.sys.EthRMII} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sys.EthRMII.toObject = function(includeInstance, msg) {
  var f, obj = {
    mdc: (f = msg.getMdc()) && GPIO_pb.GPIO.toObject(includeInstance, f),
    mdio: (f = msg.getMdio()) && GPIO_pb.GPIO.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.sys.EthRMII}
 */
proto.sys.EthRMII.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.sys.EthRMII;
  return proto.sys.EthRMII.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.sys.EthRMII} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.sys.EthRMII}
 */
proto.sys.EthRMII.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new GPIO_pb.GPIO;
      reader.readMessage(value,GPIO_pb.GPIO.deserializeBinaryFromReader);
      msg.setMdc(value);
      break;
    case 2:
      var value = new GPIO_pb.GPIO;
      reader.readMessage(value,GPIO_pb.GPIO.deserializeBinaryFromReader);
      msg.setMdio(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.sys.EthRMII.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.sys.EthRMII.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.sys.EthRMII} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sys.EthRMII.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getMdc();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      GPIO_pb.GPIO.serializeBinaryToWriter
    );
  }
  f = message.getMdio();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      GPIO_pb.GPIO.serializeBinaryToWriter
    );
  }
};


/**
 * optional GPIO mdc = 1;
 * @return {?proto.sys.GPIO}
 */
proto.sys.EthRMII.prototype.getMdc = function() {
  return /** @type{?proto.sys.GPIO} */ (
    jspb.Message.getWrapperField(this, GPIO_pb.GPIO, 1));
};


/**
 * @param {?proto.sys.GPIO|undefined} value
 * @return {!proto.sys.EthRMII} returns this
*/
proto.sys.EthRMII.prototype.setMdc = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.sys.EthRMII} returns this
 */
proto.sys.EthRMII.prototype.clearMdc = function() {
  return this.setMdc(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sys.EthRMII.prototype.hasMdc = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional GPIO mdio = 2;
 * @return {?proto.sys.GPIO}
 */
proto.sys.EthRMII.prototype.getMdio = function() {
  return /** @type{?proto.sys.GPIO} */ (
    jspb.Message.getWrapperField(this, GPIO_pb.GPIO, 2));
};


/**
 * @param {?proto.sys.GPIO|undefined} value
 * @return {!proto.sys.EthRMII} returns this
*/
proto.sys.EthRMII.prototype.setMdio = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.sys.EthRMII} returns this
 */
proto.sys.EthRMII.prototype.clearMdio = function() {
  return this.setMdio(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sys.EthRMII.prototype.hasMdio = function() {
  return jspb.Message.getField(this, 2) != null;
};



/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.sys.Eth.oneofGroups_ = [[3,4]];

/**
 * @enum {number}
 */
proto.sys.Eth.EthtypeCase = {
  ETHTYPE_NOT_SET: 0,
  SPI: 3,
  RMII: 4
};

/**
 * @return {proto.sys.Eth.EthtypeCase}
 */
proto.sys.Eth.prototype.getEthtypeCase = function() {
  return /** @type {proto.sys.Eth.EthtypeCase} */(jspb.Message.computeOneofCase(this, proto.sys.Eth.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.sys.Eth.prototype.toObject = function(opt_includeInstance) {
  return proto.sys.Eth.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.sys.Eth} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sys.Eth.toObject = function(includeInstance, msg) {
  var f, obj = {
    type: jspb.Message.getFieldWithDefault(msg, 1, 0),
    common: (f = msg.getCommon()) && proto.sys.EthCommon.toObject(includeInstance, f),
    spi: (f = msg.getSpi()) && proto.sys.EthSPI.toObject(includeInstance, f),
    rmii: (f = msg.getRmii()) && proto.sys.EthRMII.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.sys.Eth}
 */
proto.sys.Eth.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.sys.Eth;
  return proto.sys.Eth.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.sys.Eth} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.sys.Eth}
 */
proto.sys.Eth.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.sys.DeviceTypeEnum} */ (reader.readEnum());
      msg.setType(value);
      break;
    case 2:
      var value = new proto.sys.EthCommon;
      reader.readMessage(value,proto.sys.EthCommon.deserializeBinaryFromReader);
      msg.setCommon(value);
      break;
    case 3:
      var value = new proto.sys.EthSPI;
      reader.readMessage(value,proto.sys.EthSPI.deserializeBinaryFromReader);
      msg.setSpi(value);
      break;
    case 4:
      var value = new proto.sys.EthRMII;
      reader.readMessage(value,proto.sys.EthRMII.deserializeBinaryFromReader);
      msg.setRmii(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.sys.Eth.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.sys.Eth.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.sys.Eth} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sys.Eth.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getType();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getCommon();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.sys.EthCommon.serializeBinaryToWriter
    );
  }
  f = message.getSpi();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.sys.EthSPI.serializeBinaryToWriter
    );
  }
  f = message.getRmii();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      proto.sys.EthRMII.serializeBinaryToWriter
    );
  }
};


/**
 * optional DeviceTypeEnum type = 1;
 * @return {!proto.sys.DeviceTypeEnum}
 */
proto.sys.Eth.prototype.getType = function() {
  return /** @type {!proto.sys.DeviceTypeEnum} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {!proto.sys.DeviceTypeEnum} value
 * @return {!proto.sys.Eth} returns this
 */
proto.sys.Eth.prototype.setType = function(value) {
  return jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * optional EthCommon common = 2;
 * @return {?proto.sys.EthCommon}
 */
proto.sys.Eth.prototype.getCommon = function() {
  return /** @type{?proto.sys.EthCommon} */ (
    jspb.Message.getWrapperField(this, proto.sys.EthCommon, 2));
};


/**
 * @param {?proto.sys.EthCommon|undefined} value
 * @return {!proto.sys.Eth} returns this
*/
proto.sys.Eth.prototype.setCommon = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.sys.Eth} returns this
 */
proto.sys.Eth.prototype.clearCommon = function() {
  return this.setCommon(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sys.Eth.prototype.hasCommon = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional EthSPI spi = 3;
 * @return {?proto.sys.EthSPI}
 */
proto.sys.Eth.prototype.getSpi = function() {
  return /** @type{?proto.sys.EthSPI} */ (
    jspb.Message.getWrapperField(this, proto.sys.EthSPI, 3));
};


/**
 * @param {?proto.sys.EthSPI|undefined} value
 * @return {!proto.sys.Eth} returns this
*/
proto.sys.Eth.prototype.setSpi = function(value) {
  return jspb.Message.setOneofWrapperField(this, 3, proto.sys.Eth.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.sys.Eth} returns this
 */
proto.sys.Eth.prototype.clearSpi = function() {
  return this.setSpi(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sys.Eth.prototype.hasSpi = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional EthRMII rmii = 4;
 * @return {?proto.sys.EthRMII}
 */
proto.sys.Eth.prototype.getRmii = function() {
  return /** @type{?proto.sys.EthRMII} */ (
    jspb.Message.getWrapperField(this, proto.sys.EthRMII, 4));
};


/**
 * @param {?proto.sys.EthRMII|undefined} value
 * @return {!proto.sys.Eth} returns this
*/
proto.sys.Eth.prototype.setRmii = function(value) {
  return jspb.Message.setOneofWrapperField(this, 4, proto.sys.Eth.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.sys.Eth} returns this
 */
proto.sys.Eth.prototype.clearRmii = function() {
  return this.setRmii(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sys.Eth.prototype.hasRmii = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * @enum {number}
 */
proto.sys.EthModelEnum = {
  UNSPECIFIED_ETHMODEL: 0,
  LAN8720: 1,
  DM9051: 2,
  W5500: 3
};

/**
 * @enum {number}
 */
proto.sys.EthType = {
  UNSPECIFIED_ETH: 0,
  SPI: 1,
  RMII: 2
};

goog.object.extend(exports, proto.sys);
