// source: GPIO.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global =
    (typeof globalThis !== 'undefined' && globalThis) ||
    (typeof window !== 'undefined' && window) ||
    (typeof global !== 'undefined' && global) ||
    (typeof self !== 'undefined' && self) ||
    (function () { return this; }).call(null) ||
    Function('return this')();

var Common_pb = require('./Common_pb.js');
goog.object.extend(proto, Common_pb);
var customoptions_pb = require('./customoptions_pb.js');
goog.object.extend(proto, customoptions_pb);
var nanopb_pb = require('./nanopb_pb.js');
goog.object.extend(proto, nanopb_pb);
goog.exportSymbol('proto.sys.GPIO', null, global);
goog.exportSymbol('proto.sys.GPIOExp', null, global);
goog.exportSymbol('proto.sys.GPIOExp.ExptypeCase', null, global);
goog.exportSymbol('proto.sys.GPIOExpI2C', null, global);
goog.exportSymbol('proto.sys.GPIOExpModelEnum', null, global);
goog.exportSymbol('proto.sys.GPIOExpSPI', null, global);
goog.exportSymbol('proto.sys.Gpios', null, global);
goog.exportSymbol('proto.sys.LED', null, global);
goog.exportSymbol('proto.sys.LedTypesEnum', null, global);
goog.exportSymbol('proto.sys.LevelsEnum', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.sys.GPIO = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.sys.GPIO, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.sys.GPIO.displayName = 'proto.sys.GPIO';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.sys.LED = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.sys.LED, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.sys.LED.displayName = 'proto.sys.LED';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.sys.Gpios = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.sys.Gpios, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.sys.Gpios.displayName = 'proto.sys.Gpios';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.sys.GPIOExpI2C = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.sys.GPIOExpI2C, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.sys.GPIOExpI2C.displayName = 'proto.sys.GPIOExpI2C';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.sys.GPIOExpSPI = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.sys.GPIOExpSPI, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.sys.GPIOExpSPI.displayName = 'proto.sys.GPIOExpSPI';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.sys.GPIOExp = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.sys.GPIOExp.oneofGroups_);
};
goog.inherits(proto.sys.GPIOExp, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.sys.GPIOExp.displayName = 'proto.sys.GPIOExp';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.sys.GPIO.prototype.toObject = function(opt_includeInstance) {
  return proto.sys.GPIO.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.sys.GPIO} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sys.GPIO.toObject = function(includeInstance, msg) {
  var f, obj = {
    pin: jspb.Message.getFieldWithDefault(msg, 1, 0),
    level: jspb.Message.getFieldWithDefault(msg, 2, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.sys.GPIO}
 */
proto.sys.GPIO.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.sys.GPIO;
  return proto.sys.GPIO.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.sys.GPIO} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.sys.GPIO}
 */
proto.sys.GPIO.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setPin(value);
      break;
    case 2:
      var value = /** @type {!proto.sys.LevelsEnum} */ (reader.readEnum());
      msg.setLevel(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.sys.GPIO.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.sys.GPIO.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.sys.GPIO} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sys.GPIO.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPin();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getLevel();
  if (f !== 0.0) {
    writer.writeEnum(
      2,
      f
    );
  }
};


/**
 * optional int32 pin = 1;
 * @return {number}
 */
proto.sys.GPIO.prototype.getPin = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.sys.GPIO} returns this
 */
proto.sys.GPIO.prototype.setPin = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional LevelsEnum level = 2;
 * @return {!proto.sys.LevelsEnum}
 */
proto.sys.GPIO.prototype.getLevel = function() {
  return /** @type {!proto.sys.LevelsEnum} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {!proto.sys.LevelsEnum} value
 * @return {!proto.sys.GPIO} returns this
 */
proto.sys.GPIO.prototype.setLevel = function(value) {
  return jspb.Message.setProto3EnumField(this, 2, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.sys.LED.prototype.toObject = function(opt_includeInstance) {
  return proto.sys.LED.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.sys.LED} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sys.LED.toObject = function(includeInstance, msg) {
  var f, obj = {
    gpio: (f = msg.getGpio()) && proto.sys.GPIO.toObject(includeInstance, f),
    brightness: jspb.Message.getFieldWithDefault(msg, 2, 0),
    ledType: jspb.Message.getFieldWithDefault(msg, 3, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.sys.LED}
 */
proto.sys.LED.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.sys.LED;
  return proto.sys.LED.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.sys.LED} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.sys.LED}
 */
proto.sys.LED.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.sys.GPIO;
      reader.readMessage(value,proto.sys.GPIO.deserializeBinaryFromReader);
      msg.setGpio(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setBrightness(value);
      break;
    case 3:
      var value = /** @type {!proto.sys.LedTypesEnum} */ (reader.readEnum());
      msg.setLedType(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.sys.LED.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.sys.LED.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.sys.LED} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sys.LED.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getGpio();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.sys.GPIO.serializeBinaryToWriter
    );
  }
  f = message.getBrightness();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
  f = message.getLedType();
  if (f !== 0.0) {
    writer.writeEnum(
      3,
      f
    );
  }
};


/**
 * optional GPIO gpio = 1;
 * @return {?proto.sys.GPIO}
 */
proto.sys.LED.prototype.getGpio = function() {
  return /** @type{?proto.sys.GPIO} */ (
    jspb.Message.getWrapperField(this, proto.sys.GPIO, 1));
};


/**
 * @param {?proto.sys.GPIO|undefined} value
 * @return {!proto.sys.LED} returns this
*/
proto.sys.LED.prototype.setGpio = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.sys.LED} returns this
 */
proto.sys.LED.prototype.clearGpio = function() {
  return this.setGpio(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sys.LED.prototype.hasGpio = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional int32 brightness = 2;
 * @return {number}
 */
proto.sys.LED.prototype.getBrightness = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.sys.LED} returns this
 */
proto.sys.LED.prototype.setBrightness = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional LedTypesEnum led_type = 3;
 * @return {!proto.sys.LedTypesEnum}
 */
proto.sys.LED.prototype.getLedType = function() {
  return /** @type {!proto.sys.LedTypesEnum} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {!proto.sys.LedTypesEnum} value
 * @return {!proto.sys.LED} returns this
 */
proto.sys.LED.prototype.setLedType = function(value) {
  return jspb.Message.setProto3EnumField(this, 3, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.sys.Gpios.prototype.toObject = function(opt_includeInstance) {
  return proto.sys.Gpios.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.sys.Gpios} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sys.Gpios.toObject = function(includeInstance, msg) {
  var f, obj = {
    greenled: (f = msg.getGreenled()) && proto.sys.LED.toObject(includeInstance, f),
    redled: (f = msg.getRedled()) && proto.sys.LED.toObject(includeInstance, f),
    audiojack: (f = msg.getAudiojack()) && proto.sys.GPIO.toObject(includeInstance, f),
    amp: (f = msg.getAmp()) && proto.sys.GPIO.toObject(includeInstance, f),
    power: (f = msg.getPower()) && proto.sys.GPIO.toObject(includeInstance, f),
    jack: (f = msg.getJack()) && proto.sys.GPIO.toObject(includeInstance, f),
    spkfault: (f = msg.getSpkfault()) && proto.sys.GPIO.toObject(includeInstance, f),
    vcc: (f = msg.getVcc()) && proto.sys.GPIO.toObject(includeInstance, f),
    gnd: (f = msg.getGnd()) && proto.sys.GPIO.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.sys.Gpios}
 */
proto.sys.Gpios.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.sys.Gpios;
  return proto.sys.Gpios.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.sys.Gpios} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.sys.Gpios}
 */
proto.sys.Gpios.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.sys.LED;
      reader.readMessage(value,proto.sys.LED.deserializeBinaryFromReader);
      msg.setGreenled(value);
      break;
    case 2:
      var value = new proto.sys.LED;
      reader.readMessage(value,proto.sys.LED.deserializeBinaryFromReader);
      msg.setRedled(value);
      break;
    case 3:
      var value = new proto.sys.GPIO;
      reader.readMessage(value,proto.sys.GPIO.deserializeBinaryFromReader);
      msg.setAudiojack(value);
      break;
    case 4:
      var value = new proto.sys.GPIO;
      reader.readMessage(value,proto.sys.GPIO.deserializeBinaryFromReader);
      msg.setAmp(value);
      break;
    case 5:
      var value = new proto.sys.GPIO;
      reader.readMessage(value,proto.sys.GPIO.deserializeBinaryFromReader);
      msg.setPower(value);
      break;
    case 6:
      var value = new proto.sys.GPIO;
      reader.readMessage(value,proto.sys.GPIO.deserializeBinaryFromReader);
      msg.setJack(value);
      break;
    case 7:
      var value = new proto.sys.GPIO;
      reader.readMessage(value,proto.sys.GPIO.deserializeBinaryFromReader);
      msg.setSpkfault(value);
      break;
    case 8:
      var value = new proto.sys.GPIO;
      reader.readMessage(value,proto.sys.GPIO.deserializeBinaryFromReader);
      msg.setVcc(value);
      break;
    case 9:
      var value = new proto.sys.GPIO;
      reader.readMessage(value,proto.sys.GPIO.deserializeBinaryFromReader);
      msg.setGnd(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.sys.Gpios.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.sys.Gpios.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.sys.Gpios} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sys.Gpios.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getGreenled();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.sys.LED.serializeBinaryToWriter
    );
  }
  f = message.getRedled();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.sys.LED.serializeBinaryToWriter
    );
  }
  f = message.getAudiojack();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.sys.GPIO.serializeBinaryToWriter
    );
  }
  f = message.getAmp();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      proto.sys.GPIO.serializeBinaryToWriter
    );
  }
  f = message.getPower();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      proto.sys.GPIO.serializeBinaryToWriter
    );
  }
  f = message.getJack();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      proto.sys.GPIO.serializeBinaryToWriter
    );
  }
  f = message.getSpkfault();
  if (f != null) {
    writer.writeMessage(
      7,
      f,
      proto.sys.GPIO.serializeBinaryToWriter
    );
  }
  f = message.getVcc();
  if (f != null) {
    writer.writeMessage(
      8,
      f,
      proto.sys.GPIO.serializeBinaryToWriter
    );
  }
  f = message.getGnd();
  if (f != null) {
    writer.writeMessage(
      9,
      f,
      proto.sys.GPIO.serializeBinaryToWriter
    );
  }
};


/**
 * optional LED greenLED = 1;
 * @return {?proto.sys.LED}
 */
proto.sys.Gpios.prototype.getGreenled = function() {
  return /** @type{?proto.sys.LED} */ (
    jspb.Message.getWrapperField(this, proto.sys.LED, 1));
};


/**
 * @param {?proto.sys.LED|undefined} value
 * @return {!proto.sys.Gpios} returns this
*/
proto.sys.Gpios.prototype.setGreenled = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.sys.Gpios} returns this
 */
proto.sys.Gpios.prototype.clearGreenled = function() {
  return this.setGreenled(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sys.Gpios.prototype.hasGreenled = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional LED redLED = 2;
 * @return {?proto.sys.LED}
 */
proto.sys.Gpios.prototype.getRedled = function() {
  return /** @type{?proto.sys.LED} */ (
    jspb.Message.getWrapperField(this, proto.sys.LED, 2));
};


/**
 * @param {?proto.sys.LED|undefined} value
 * @return {!proto.sys.Gpios} returns this
*/
proto.sys.Gpios.prototype.setRedled = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.sys.Gpios} returns this
 */
proto.sys.Gpios.prototype.clearRedled = function() {
  return this.setRedled(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sys.Gpios.prototype.hasRedled = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional GPIO audioJack = 3;
 * @return {?proto.sys.GPIO}
 */
proto.sys.Gpios.prototype.getAudiojack = function() {
  return /** @type{?proto.sys.GPIO} */ (
    jspb.Message.getWrapperField(this, proto.sys.GPIO, 3));
};


/**
 * @param {?proto.sys.GPIO|undefined} value
 * @return {!proto.sys.Gpios} returns this
*/
proto.sys.Gpios.prototype.setAudiojack = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.sys.Gpios} returns this
 */
proto.sys.Gpios.prototype.clearAudiojack = function() {
  return this.setAudiojack(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sys.Gpios.prototype.hasAudiojack = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional GPIO amp = 4;
 * @return {?proto.sys.GPIO}
 */
proto.sys.Gpios.prototype.getAmp = function() {
  return /** @type{?proto.sys.GPIO} */ (
    jspb.Message.getWrapperField(this, proto.sys.GPIO, 4));
};


/**
 * @param {?proto.sys.GPIO|undefined} value
 * @return {!proto.sys.Gpios} returns this
*/
proto.sys.Gpios.prototype.setAmp = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.sys.Gpios} returns this
 */
proto.sys.Gpios.prototype.clearAmp = function() {
  return this.setAmp(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sys.Gpios.prototype.hasAmp = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional GPIO power = 5;
 * @return {?proto.sys.GPIO}
 */
proto.sys.Gpios.prototype.getPower = function() {
  return /** @type{?proto.sys.GPIO} */ (
    jspb.Message.getWrapperField(this, proto.sys.GPIO, 5));
};


/**
 * @param {?proto.sys.GPIO|undefined} value
 * @return {!proto.sys.Gpios} returns this
*/
proto.sys.Gpios.prototype.setPower = function(value) {
  return jspb.Message.setWrapperField(this, 5, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.sys.Gpios} returns this
 */
proto.sys.Gpios.prototype.clearPower = function() {
  return this.setPower(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sys.Gpios.prototype.hasPower = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional GPIO jack = 6;
 * @return {?proto.sys.GPIO}
 */
proto.sys.Gpios.prototype.getJack = function() {
  return /** @type{?proto.sys.GPIO} */ (
    jspb.Message.getWrapperField(this, proto.sys.GPIO, 6));
};


/**
 * @param {?proto.sys.GPIO|undefined} value
 * @return {!proto.sys.Gpios} returns this
*/
proto.sys.Gpios.prototype.setJack = function(value) {
  return jspb.Message.setWrapperField(this, 6, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.sys.Gpios} returns this
 */
proto.sys.Gpios.prototype.clearJack = function() {
  return this.setJack(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sys.Gpios.prototype.hasJack = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * optional GPIO spkfault = 7;
 * @return {?proto.sys.GPIO}
 */
proto.sys.Gpios.prototype.getSpkfault = function() {
  return /** @type{?proto.sys.GPIO} */ (
    jspb.Message.getWrapperField(this, proto.sys.GPIO, 7));
};


/**
 * @param {?proto.sys.GPIO|undefined} value
 * @return {!proto.sys.Gpios} returns this
*/
proto.sys.Gpios.prototype.setSpkfault = function(value) {
  return jspb.Message.setWrapperField(this, 7, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.sys.Gpios} returns this
 */
proto.sys.Gpios.prototype.clearSpkfault = function() {
  return this.setSpkfault(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sys.Gpios.prototype.hasSpkfault = function() {
  return jspb.Message.getField(this, 7) != null;
};


/**
 * optional GPIO Vcc = 8;
 * @return {?proto.sys.GPIO}
 */
proto.sys.Gpios.prototype.getVcc = function() {
  return /** @type{?proto.sys.GPIO} */ (
    jspb.Message.getWrapperField(this, proto.sys.GPIO, 8));
};


/**
 * @param {?proto.sys.GPIO|undefined} value
 * @return {!proto.sys.Gpios} returns this
*/
proto.sys.Gpios.prototype.setVcc = function(value) {
  return jspb.Message.setWrapperField(this, 8, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.sys.Gpios} returns this
 */
proto.sys.Gpios.prototype.clearVcc = function() {
  return this.setVcc(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sys.Gpios.prototype.hasVcc = function() {
  return jspb.Message.getField(this, 8) != null;
};


/**
 * optional GPIO GND = 9;
 * @return {?proto.sys.GPIO}
 */
proto.sys.Gpios.prototype.getGnd = function() {
  return /** @type{?proto.sys.GPIO} */ (
    jspb.Message.getWrapperField(this, proto.sys.GPIO, 9));
};


/**
 * @param {?proto.sys.GPIO|undefined} value
 * @return {!proto.sys.Gpios} returns this
*/
proto.sys.Gpios.prototype.setGnd = function(value) {
  return jspb.Message.setWrapperField(this, 9, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.sys.Gpios} returns this
 */
proto.sys.Gpios.prototype.clearGnd = function() {
  return this.setGnd(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sys.Gpios.prototype.hasGnd = function() {
  return jspb.Message.getField(this, 9) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.sys.GPIOExpI2C.prototype.toObject = function(opt_includeInstance) {
  return proto.sys.GPIOExpI2C.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.sys.GPIOExpI2C} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sys.GPIOExpI2C.toObject = function(includeInstance, msg) {
  var f, obj = {
    port: jspb.Message.getFieldWithDefault(msg, 5, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.sys.GPIOExpI2C}
 */
proto.sys.GPIOExpI2C.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.sys.GPIOExpI2C;
  return proto.sys.GPIOExpI2C.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.sys.GPIOExpI2C} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.sys.GPIOExpI2C}
 */
proto.sys.GPIOExpI2C.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 5:
      var value = /** @type {!proto.sys.PortEnum} */ (reader.readEnum());
      msg.setPort(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.sys.GPIOExpI2C.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.sys.GPIOExpI2C.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.sys.GPIOExpI2C} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sys.GPIOExpI2C.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPort();
  if (f !== 0.0) {
    writer.writeEnum(
      5,
      f
    );
  }
};


/**
 * optional PortEnum port = 5;
 * @return {!proto.sys.PortEnum}
 */
proto.sys.GPIOExpI2C.prototype.getPort = function() {
  return /** @type {!proto.sys.PortEnum} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {!proto.sys.PortEnum} value
 * @return {!proto.sys.GPIOExpI2C} returns this
 */
proto.sys.GPIOExpI2C.prototype.setPort = function(value) {
  return jspb.Message.setProto3EnumField(this, 5, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.sys.GPIOExpSPI.prototype.toObject = function(opt_includeInstance) {
  return proto.sys.GPIOExpSPI.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.sys.GPIOExpSPI} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sys.GPIOExpSPI.toObject = function(includeInstance, msg) {
  var f, obj = {
    speed: jspb.Message.getFieldWithDefault(msg, 1, 0),
    host: jspb.Message.getFieldWithDefault(msg, 2, 0),
    cs: (f = msg.getCs()) && proto.sys.GPIO.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.sys.GPIOExpSPI}
 */
proto.sys.GPIOExpSPI.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.sys.GPIOExpSPI;
  return proto.sys.GPIOExpSPI.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.sys.GPIOExpSPI} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.sys.GPIOExpSPI}
 */
proto.sys.GPIOExpSPI.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setSpeed(value);
      break;
    case 2:
      var value = /** @type {!proto.sys.HostEnum} */ (reader.readEnum());
      msg.setHost(value);
      break;
    case 3:
      var value = new proto.sys.GPIO;
      reader.readMessage(value,proto.sys.GPIO.deserializeBinaryFromReader);
      msg.setCs(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.sys.GPIOExpSPI.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.sys.GPIOExpSPI.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.sys.GPIOExpSPI} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sys.GPIOExpSPI.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSpeed();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getHost();
  if (f !== 0.0) {
    writer.writeEnum(
      2,
      f
    );
  }
  f = message.getCs();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.sys.GPIO.serializeBinaryToWriter
    );
  }
};


/**
 * optional int32 speed = 1;
 * @return {number}
 */
proto.sys.GPIOExpSPI.prototype.getSpeed = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.sys.GPIOExpSPI} returns this
 */
proto.sys.GPIOExpSPI.prototype.setSpeed = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional HostEnum host = 2;
 * @return {!proto.sys.HostEnum}
 */
proto.sys.GPIOExpSPI.prototype.getHost = function() {
  return /** @type {!proto.sys.HostEnum} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {!proto.sys.HostEnum} value
 * @return {!proto.sys.GPIOExpSPI} returns this
 */
proto.sys.GPIOExpSPI.prototype.setHost = function(value) {
  return jspb.Message.setProto3EnumField(this, 2, value);
};


/**
 * optional GPIO cs = 3;
 * @return {?proto.sys.GPIO}
 */
proto.sys.GPIOExpSPI.prototype.getCs = function() {
  return /** @type{?proto.sys.GPIO} */ (
    jspb.Message.getWrapperField(this, proto.sys.GPIO, 3));
};


/**
 * @param {?proto.sys.GPIO|undefined} value
 * @return {!proto.sys.GPIOExpSPI} returns this
*/
proto.sys.GPIOExpSPI.prototype.setCs = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.sys.GPIOExpSPI} returns this
 */
proto.sys.GPIOExpSPI.prototype.clearCs = function() {
  return this.setCs(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sys.GPIOExpSPI.prototype.hasCs = function() {
  return jspb.Message.getField(this, 3) != null;
};



/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.sys.GPIOExp.oneofGroups_ = [[3,4]];

/**
 * @enum {number}
 */
proto.sys.GPIOExp.ExptypeCase = {
  EXPTYPE_NOT_SET: 0,
  I2C: 3,
  SPI: 4
};

/**
 * @return {proto.sys.GPIOExp.ExptypeCase}
 */
proto.sys.GPIOExp.prototype.getExptypeCase = function() {
  return /** @type {proto.sys.GPIOExp.ExptypeCase} */(jspb.Message.computeOneofCase(this, proto.sys.GPIOExp.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.sys.GPIOExp.prototype.toObject = function(opt_includeInstance) {
  return proto.sys.GPIOExp.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.sys.GPIOExp} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sys.GPIOExp.toObject = function(includeInstance, msg) {
  var f, obj = {
    model: jspb.Message.getFieldWithDefault(msg, 1, 0),
    addr: jspb.Message.getFieldWithDefault(msg, 2, 0),
    i2c: (f = msg.getI2c()) && proto.sys.GPIOExpI2C.toObject(includeInstance, f),
    spi: (f = msg.getSpi()) && proto.sys.GPIOExpSPI.toObject(includeInstance, f),
    base: jspb.Message.getFieldWithDefault(msg, 5, 0),
    count: jspb.Message.getFieldWithDefault(msg, 6, 0),
    intr: (f = msg.getIntr()) && proto.sys.GPIO.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.sys.GPIOExp}
 */
proto.sys.GPIOExp.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.sys.GPIOExp;
  return proto.sys.GPIOExp.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.sys.GPIOExp} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.sys.GPIOExp}
 */
proto.sys.GPIOExp.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.sys.GPIOExpModelEnum} */ (reader.readEnum());
      msg.setModel(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setAddr(value);
      break;
    case 3:
      var value = new proto.sys.GPIOExpI2C;
      reader.readMessage(value,proto.sys.GPIOExpI2C.deserializeBinaryFromReader);
      msg.setI2c(value);
      break;
    case 4:
      var value = new proto.sys.GPIOExpSPI;
      reader.readMessage(value,proto.sys.GPIOExpSPI.deserializeBinaryFromReader);
      msg.setSpi(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setBase(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setCount(value);
      break;
    case 7:
      var value = new proto.sys.GPIO;
      reader.readMessage(value,proto.sys.GPIO.deserializeBinaryFromReader);
      msg.setIntr(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.sys.GPIOExp.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.sys.GPIOExp.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.sys.GPIOExp} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sys.GPIOExp.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getModel();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getAddr();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
  f = message.getI2c();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.sys.GPIOExpI2C.serializeBinaryToWriter
    );
  }
  f = message.getSpi();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      proto.sys.GPIOExpSPI.serializeBinaryToWriter
    );
  }
  f = message.getBase();
  if (f !== 0) {
    writer.writeInt32(
      5,
      f
    );
  }
  f = message.getCount();
  if (f !== 0) {
    writer.writeInt32(
      6,
      f
    );
  }
  f = message.getIntr();
  if (f != null) {
    writer.writeMessage(
      7,
      f,
      proto.sys.GPIO.serializeBinaryToWriter
    );
  }
};


/**
 * optional GPIOExpModelEnum model = 1;
 * @return {!proto.sys.GPIOExpModelEnum}
 */
proto.sys.GPIOExp.prototype.getModel = function() {
  return /** @type {!proto.sys.GPIOExpModelEnum} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {!proto.sys.GPIOExpModelEnum} value
 * @return {!proto.sys.GPIOExp} returns this
 */
proto.sys.GPIOExp.prototype.setModel = function(value) {
  return jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * optional int32 addr = 2;
 * @return {number}
 */
proto.sys.GPIOExp.prototype.getAddr = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.sys.GPIOExp} returns this
 */
proto.sys.GPIOExp.prototype.setAddr = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional GPIOExpI2C i2c = 3;
 * @return {?proto.sys.GPIOExpI2C}
 */
proto.sys.GPIOExp.prototype.getI2c = function() {
  return /** @type{?proto.sys.GPIOExpI2C} */ (
    jspb.Message.getWrapperField(this, proto.sys.GPIOExpI2C, 3));
};


/**
 * @param {?proto.sys.GPIOExpI2C|undefined} value
 * @return {!proto.sys.GPIOExp} returns this
*/
proto.sys.GPIOExp.prototype.setI2c = function(value) {
  return jspb.Message.setOneofWrapperField(this, 3, proto.sys.GPIOExp.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.sys.GPIOExp} returns this
 */
proto.sys.GPIOExp.prototype.clearI2c = function() {
  return this.setI2c(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sys.GPIOExp.prototype.hasI2c = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional GPIOExpSPI spi = 4;
 * @return {?proto.sys.GPIOExpSPI}
 */
proto.sys.GPIOExp.prototype.getSpi = function() {
  return /** @type{?proto.sys.GPIOExpSPI} */ (
    jspb.Message.getWrapperField(this, proto.sys.GPIOExpSPI, 4));
};


/**
 * @param {?proto.sys.GPIOExpSPI|undefined} value
 * @return {!proto.sys.GPIOExp} returns this
*/
proto.sys.GPIOExp.prototype.setSpi = function(value) {
  return jspb.Message.setOneofWrapperField(this, 4, proto.sys.GPIOExp.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.sys.GPIOExp} returns this
 */
proto.sys.GPIOExp.prototype.clearSpi = function() {
  return this.setSpi(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sys.GPIOExp.prototype.hasSpi = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional int32 base = 5;
 * @return {number}
 */
proto.sys.GPIOExp.prototype.getBase = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.sys.GPIOExp} returns this
 */
proto.sys.GPIOExp.prototype.setBase = function(value) {
  return jspb.Message.setProto3IntField(this, 5, value);
};


/**
 * optional int32 count = 6;
 * @return {number}
 */
proto.sys.GPIOExp.prototype.getCount = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/**
 * @param {number} value
 * @return {!proto.sys.GPIOExp} returns this
 */
proto.sys.GPIOExp.prototype.setCount = function(value) {
  return jspb.Message.setProto3IntField(this, 6, value);
};


/**
 * optional GPIO intr = 7;
 * @return {?proto.sys.GPIO}
 */
proto.sys.GPIOExp.prototype.getIntr = function() {
  return /** @type{?proto.sys.GPIO} */ (
    jspb.Message.getWrapperField(this, proto.sys.GPIO, 7));
};


/**
 * @param {?proto.sys.GPIO|undefined} value
 * @return {!proto.sys.GPIOExp} returns this
*/
proto.sys.GPIOExp.prototype.setIntr = function(value) {
  return jspb.Message.setWrapperField(this, 7, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.sys.GPIOExp} returns this
 */
proto.sys.GPIOExp.prototype.clearIntr = function() {
  return this.setIntr(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sys.GPIOExp.prototype.hasIntr = function() {
  return jspb.Message.getField(this, 7) != null;
};


/**
 * @enum {number}
 */
proto.sys.LevelsEnum = {
  L_LOW: 0,
  L_HIGH: 1
};

/**
 * @enum {number}
 */
proto.sys.LedTypesEnum = {
  UNKNOWN: 0,
  LED_TYPE_GPIO: 1,
  LED_TYPE_WS2812: 2
};

/**
 * @enum {number}
 */
proto.sys.GPIOExpModelEnum = {
  UNSPECIFIED_EXP: 0,
  PCA9535: 1,
  PCA85XX: 2,
  MCP23017: 3,
  MCP23S17: 4
};

goog.object.extend(exports, proto.sys);
