// source: Names.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global =
    (typeof globalThis !== 'undefined' && globalThis) ||
    (typeof window !== 'undefined' && window) ||
    (typeof global !== 'undefined' && global) ||
    (typeof self !== 'undefined' && self) ||
    (function () { return this; }).call(null) ||
    Function('return this')();

var customoptions_pb = require('./customoptions_pb.js');
goog.object.extend(proto, customoptions_pb);
var nanopb_pb = require('./nanopb_pb.js');
goog.object.extend(proto, nanopb_pb);
goog.exportSymbol('proto.sys.Names', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.sys.Names = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.sys.Names, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.sys.Names.displayName = 'proto.sys.Names';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.sys.Names.prototype.toObject = function(opt_includeInstance) {
  return proto.sys.Names.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.sys.Names} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sys.Names.toObject = function(includeInstance, msg) {
  var f, obj = {
    device: jspb.Message.getFieldWithDefault(msg, 1, ""),
    airplay: jspb.Message.getFieldWithDefault(msg, 2, ""),
    spotify: jspb.Message.getFieldWithDefault(msg, 3, ""),
    bluetooth: jspb.Message.getFieldWithDefault(msg, 4, ""),
    squeezelite: jspb.Message.getFieldWithDefault(msg, 5, ""),
    wifiApName: jspb.Message.getFieldWithDefault(msg, 6, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.sys.Names}
 */
proto.sys.Names.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.sys.Names;
  return proto.sys.Names.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.sys.Names} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.sys.Names}
 */
proto.sys.Names.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setDevice(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setAirplay(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setSpotify(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setBluetooth(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setSqueezelite(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setWifiApName(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.sys.Names.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.sys.Names.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.sys.Names} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sys.Names.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getDevice();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getAirplay();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getSpotify();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getBluetooth();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getSqueezelite();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getWifiApName();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
};


/**
 * optional string device = 1;
 * @return {string}
 */
proto.sys.Names.prototype.getDevice = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.sys.Names} returns this
 */
proto.sys.Names.prototype.setDevice = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string airplay = 2;
 * @return {string}
 */
proto.sys.Names.prototype.getAirplay = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.sys.Names} returns this
 */
proto.sys.Names.prototype.setAirplay = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string spotify = 3;
 * @return {string}
 */
proto.sys.Names.prototype.getSpotify = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.sys.Names} returns this
 */
proto.sys.Names.prototype.setSpotify = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string bluetooth = 4;
 * @return {string}
 */
proto.sys.Names.prototype.getBluetooth = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.sys.Names} returns this
 */
proto.sys.Names.prototype.setBluetooth = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string squeezelite = 5;
 * @return {string}
 */
proto.sys.Names.prototype.getSqueezelite = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.sys.Names} returns this
 */
proto.sys.Names.prototype.setSqueezelite = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional string wifi_ap_name = 6;
 * @return {string}
 */
proto.sys.Names.prototype.getWifiApName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.sys.Names} returns this
 */
proto.sys.Names.prototype.setWifiApName = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};


goog.object.extend(exports, proto.sys);
