// source: Network.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global =
    (typeof globalThis !== 'undefined' && globalThis) ||
    (typeof window !== 'undefined' && window) ||
    (typeof global !== 'undefined' && global) ||
    (typeof self !== 'undefined' && self) ||
    (function () { return this; }).call(null) ||
    Function('return this')();

var google_protobuf_timestamp_pb = require('google-protobuf/google/protobuf/timestamp_pb.js');
goog.object.extend(proto, google_protobuf_timestamp_pb);
var customoptions_pb = require('./customoptions_pb.js');
goog.object.extend(proto, customoptions_pb);
var nanopb_pb = require('./nanopb_pb.js');
goog.object.extend(proto, nanopb_pb);
goog.exportSymbol('proto.sys.IP', null, global);
goog.exportSymbol('proto.sys.NetworkConfig', null, global);
goog.exportSymbol('proto.sys.NetworkConfig.PowerSaveTypeEnum', null, global);
goog.exportSymbol('proto.sys.Server', null, global);
goog.exportSymbol('proto.sys.WifiAP', null, global);
goog.exportSymbol('proto.sys.WifiAuthTypeEnum', null, global);
goog.exportSymbol('proto.sys.WifiRadioTypesEnum', null, global);
goog.exportSymbol('proto.sys.WifiSTAEntry', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.sys.IP = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.sys.IP, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.sys.IP.displayName = 'proto.sys.IP';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.sys.WifiSTAEntry = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.sys.WifiSTAEntry, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.sys.WifiSTAEntry.displayName = 'proto.sys.WifiSTAEntry';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.sys.WifiAP = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.sys.WifiAP, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.sys.WifiAP.displayName = 'proto.sys.WifiAP';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.sys.Server = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.sys.Server, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.sys.Server.displayName = 'proto.sys.Server';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.sys.NetworkConfig = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.sys.NetworkConfig.repeatedFields_, null);
};
goog.inherits(proto.sys.NetworkConfig, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.sys.NetworkConfig.displayName = 'proto.sys.NetworkConfig';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.sys.IP.prototype.toObject = function(opt_includeInstance) {
  return proto.sys.IP.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.sys.IP} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sys.IP.toObject = function(includeInstance, msg) {
  var f, obj = {
    ip: jspb.Message.getFieldWithDefault(msg, 14, ""),
    netmask: jspb.Message.getFieldWithDefault(msg, 15, ""),
    gw: jspb.Message.getFieldWithDefault(msg, 16, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.sys.IP}
 */
proto.sys.IP.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.sys.IP;
  return proto.sys.IP.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.sys.IP} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.sys.IP}
 */
proto.sys.IP.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 14:
      var value = /** @type {string} */ (reader.readString());
      msg.setIp(value);
      break;
    case 15:
      var value = /** @type {string} */ (reader.readString());
      msg.setNetmask(value);
      break;
    case 16:
      var value = /** @type {string} */ (reader.readString());
      msg.setGw(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.sys.IP.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.sys.IP.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.sys.IP} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sys.IP.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getIp();
  if (f.length > 0) {
    writer.writeString(
      14,
      f
    );
  }
  f = message.getNetmask();
  if (f.length > 0) {
    writer.writeString(
      15,
      f
    );
  }
  f = message.getGw();
  if (f.length > 0) {
    writer.writeString(
      16,
      f
    );
  }
};


/**
 * optional string ip = 14;
 * @return {string}
 */
proto.sys.IP.prototype.getIp = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 14, ""));
};


/**
 * @param {string} value
 * @return {!proto.sys.IP} returns this
 */
proto.sys.IP.prototype.setIp = function(value) {
  return jspb.Message.setProto3StringField(this, 14, value);
};


/**
 * optional string netmask = 15;
 * @return {string}
 */
proto.sys.IP.prototype.getNetmask = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 15, ""));
};


/**
 * @param {string} value
 * @return {!proto.sys.IP} returns this
 */
proto.sys.IP.prototype.setNetmask = function(value) {
  return jspb.Message.setProto3StringField(this, 15, value);
};


/**
 * optional string gw = 16;
 * @return {string}
 */
proto.sys.IP.prototype.getGw = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 16, ""));
};


/**
 * @param {string} value
 * @return {!proto.sys.IP} returns this
 */
proto.sys.IP.prototype.setGw = function(value) {
  return jspb.Message.setProto3StringField(this, 16, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.sys.WifiSTAEntry.prototype.toObject = function(opt_includeInstance) {
  return proto.sys.WifiSTAEntry.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.sys.WifiSTAEntry} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sys.WifiSTAEntry.toObject = function(includeInstance, msg) {
  var f, obj = {
    ssid: jspb.Message.getFieldWithDefault(msg, 1, ""),
    bssid: jspb.Message.getFieldWithDefault(msg, 2, ""),
    channel: jspb.Message.getFieldWithDefault(msg, 3, 0),
    authType: jspb.Message.getFieldWithDefault(msg, 4, 0),
    radioType: jspb.Message.getFieldWithDefault(msg, 5, 0),
    lastTry: (f = msg.getLastTry()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    lastSeen: (f = msg.getLastSeen()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    connected: jspb.Message.getBooleanFieldWithDefault(msg, 8, false),
    password: jspb.Message.getFieldWithDefault(msg, 9, ""),
    rssi: jspb.Message.getFieldWithDefault(msg, 10, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.sys.WifiSTAEntry}
 */
proto.sys.WifiSTAEntry.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.sys.WifiSTAEntry;
  return proto.sys.WifiSTAEntry.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.sys.WifiSTAEntry} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.sys.WifiSTAEntry}
 */
proto.sys.WifiSTAEntry.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setSsid(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setBssid(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setChannel(value);
      break;
    case 4:
      var value = /** @type {!proto.sys.WifiAuthTypeEnum} */ (reader.readEnum());
      msg.setAuthType(value);
      break;
    case 5:
      var value = /** @type {!proto.sys.WifiRadioTypesEnum} */ (reader.readEnum());
      msg.setRadioType(value);
      break;
    case 6:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setLastTry(value);
      break;
    case 7:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setLastSeen(value);
      break;
    case 8:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setConnected(value);
      break;
    case 9:
      var value = /** @type {string} */ (reader.readString());
      msg.setPassword(value);
      break;
    case 10:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setRssi(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.sys.WifiSTAEntry.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.sys.WifiSTAEntry.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.sys.WifiSTAEntry} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sys.WifiSTAEntry.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSsid();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getBssid();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getChannel();
  if (f !== 0) {
    writer.writeUint32(
      3,
      f
    );
  }
  f = message.getAuthType();
  if (f !== 0.0) {
    writer.writeEnum(
      4,
      f
    );
  }
  f = message.getRadioType();
  if (f !== 0.0) {
    writer.writeEnum(
      5,
      f
    );
  }
  f = message.getLastTry();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getLastSeen();
  if (f != null) {
    writer.writeMessage(
      7,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getConnected();
  if (f) {
    writer.writeBool(
      8,
      f
    );
  }
  f = message.getPassword();
  if (f.length > 0) {
    writer.writeString(
      9,
      f
    );
  }
  f = message.getRssi();
  if (f !== 0) {
    writer.writeUint32(
      10,
      f
    );
  }
};


/**
 * optional string ssid = 1;
 * @return {string}
 */
proto.sys.WifiSTAEntry.prototype.getSsid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.sys.WifiSTAEntry} returns this
 */
proto.sys.WifiSTAEntry.prototype.setSsid = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string bssid = 2;
 * @return {string}
 */
proto.sys.WifiSTAEntry.prototype.getBssid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.sys.WifiSTAEntry} returns this
 */
proto.sys.WifiSTAEntry.prototype.setBssid = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional uint32 channel = 3;
 * @return {number}
 */
proto.sys.WifiSTAEntry.prototype.getChannel = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.sys.WifiSTAEntry} returns this
 */
proto.sys.WifiSTAEntry.prototype.setChannel = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional WifiAuthTypeEnum auth_type = 4;
 * @return {!proto.sys.WifiAuthTypeEnum}
 */
proto.sys.WifiSTAEntry.prototype.getAuthType = function() {
  return /** @type {!proto.sys.WifiAuthTypeEnum} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {!proto.sys.WifiAuthTypeEnum} value
 * @return {!proto.sys.WifiSTAEntry} returns this
 */
proto.sys.WifiSTAEntry.prototype.setAuthType = function(value) {
  return jspb.Message.setProto3EnumField(this, 4, value);
};


/**
 * optional WifiRadioTypesEnum radio_type = 5;
 * @return {!proto.sys.WifiRadioTypesEnum}
 */
proto.sys.WifiSTAEntry.prototype.getRadioType = function() {
  return /** @type {!proto.sys.WifiRadioTypesEnum} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {!proto.sys.WifiRadioTypesEnum} value
 * @return {!proto.sys.WifiSTAEntry} returns this
 */
proto.sys.WifiSTAEntry.prototype.setRadioType = function(value) {
  return jspb.Message.setProto3EnumField(this, 5, value);
};


/**
 * optional google.protobuf.Timestamp last_try = 6;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.sys.WifiSTAEntry.prototype.getLastTry = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 6));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.sys.WifiSTAEntry} returns this
*/
proto.sys.WifiSTAEntry.prototype.setLastTry = function(value) {
  return jspb.Message.setWrapperField(this, 6, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.sys.WifiSTAEntry} returns this
 */
proto.sys.WifiSTAEntry.prototype.clearLastTry = function() {
  return this.setLastTry(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sys.WifiSTAEntry.prototype.hasLastTry = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * optional google.protobuf.Timestamp last_seen = 7;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.sys.WifiSTAEntry.prototype.getLastSeen = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 7));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.sys.WifiSTAEntry} returns this
*/
proto.sys.WifiSTAEntry.prototype.setLastSeen = function(value) {
  return jspb.Message.setWrapperField(this, 7, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.sys.WifiSTAEntry} returns this
 */
proto.sys.WifiSTAEntry.prototype.clearLastSeen = function() {
  return this.setLastSeen(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sys.WifiSTAEntry.prototype.hasLastSeen = function() {
  return jspb.Message.getField(this, 7) != null;
};


/**
 * optional bool connected = 8;
 * @return {boolean}
 */
proto.sys.WifiSTAEntry.prototype.getConnected = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 8, false));
};


/**
 * @param {boolean} value
 * @return {!proto.sys.WifiSTAEntry} returns this
 */
proto.sys.WifiSTAEntry.prototype.setConnected = function(value) {
  return jspb.Message.setProto3BooleanField(this, 8, value);
};


/**
 * optional string password = 9;
 * @return {string}
 */
proto.sys.WifiSTAEntry.prototype.getPassword = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 9, ""));
};


/**
 * @param {string} value
 * @return {!proto.sys.WifiSTAEntry} returns this
 */
proto.sys.WifiSTAEntry.prototype.setPassword = function(value) {
  return jspb.Message.setProto3StringField(this, 9, value);
};


/**
 * optional uint32 rssi = 10;
 * @return {number}
 */
proto.sys.WifiSTAEntry.prototype.getRssi = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 10, 0));
};


/**
 * @param {number} value
 * @return {!proto.sys.WifiSTAEntry} returns this
 */
proto.sys.WifiSTAEntry.prototype.setRssi = function(value) {
  return jspb.Message.setProto3IntField(this, 10, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.sys.WifiAP.prototype.toObject = function(opt_includeInstance) {
  return proto.sys.WifiAP.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.sys.WifiAP} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sys.WifiAP.toObject = function(includeInstance, msg) {
  var f, obj = {
    ip: (f = msg.getIp()) && proto.sys.IP.toObject(includeInstance, f),
    password: jspb.Message.getFieldWithDefault(msg, 2, ""),
    channel: jspb.Message.getFieldWithDefault(msg, 3, 0),
    authMode: jspb.Message.getFieldWithDefault(msg, 4, 0),
    hidden: jspb.Message.getBooleanFieldWithDefault(msg, 5, false),
    maxConnection: jspb.Message.getFieldWithDefault(msg, 6, 0),
    beaconInterval: jspb.Message.getFieldWithDefault(msg, 7, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.sys.WifiAP}
 */
proto.sys.WifiAP.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.sys.WifiAP;
  return proto.sys.WifiAP.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.sys.WifiAP} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.sys.WifiAP}
 */
proto.sys.WifiAP.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.sys.IP;
      reader.readMessage(value,proto.sys.IP.deserializeBinaryFromReader);
      msg.setIp(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setPassword(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setChannel(value);
      break;
    case 4:
      var value = /** @type {!proto.sys.WifiAuthTypeEnum} */ (reader.readEnum());
      msg.setAuthMode(value);
      break;
    case 5:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setHidden(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setMaxConnection(value);
      break;
    case 7:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setBeaconInterval(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.sys.WifiAP.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.sys.WifiAP.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.sys.WifiAP} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sys.WifiAP.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getIp();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.sys.IP.serializeBinaryToWriter
    );
  }
  f = message.getPassword();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getChannel();
  if (f !== 0) {
    writer.writeUint32(
      3,
      f
    );
  }
  f = message.getAuthMode();
  if (f !== 0.0) {
    writer.writeEnum(
      4,
      f
    );
  }
  f = message.getHidden();
  if (f) {
    writer.writeBool(
      5,
      f
    );
  }
  f = message.getMaxConnection();
  if (f !== 0) {
    writer.writeUint32(
      6,
      f
    );
  }
  f = message.getBeaconInterval();
  if (f !== 0) {
    writer.writeUint32(
      7,
      f
    );
  }
};


/**
 * optional IP ip = 1;
 * @return {?proto.sys.IP}
 */
proto.sys.WifiAP.prototype.getIp = function() {
  return /** @type{?proto.sys.IP} */ (
    jspb.Message.getWrapperField(this, proto.sys.IP, 1));
};


/**
 * @param {?proto.sys.IP|undefined} value
 * @return {!proto.sys.WifiAP} returns this
*/
proto.sys.WifiAP.prototype.setIp = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.sys.WifiAP} returns this
 */
proto.sys.WifiAP.prototype.clearIp = function() {
  return this.setIp(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sys.WifiAP.prototype.hasIp = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional string password = 2;
 * @return {string}
 */
proto.sys.WifiAP.prototype.getPassword = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.sys.WifiAP} returns this
 */
proto.sys.WifiAP.prototype.setPassword = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional uint32 channel = 3;
 * @return {number}
 */
proto.sys.WifiAP.prototype.getChannel = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.sys.WifiAP} returns this
 */
proto.sys.WifiAP.prototype.setChannel = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional WifiAuthTypeEnum auth_mode = 4;
 * @return {!proto.sys.WifiAuthTypeEnum}
 */
proto.sys.WifiAP.prototype.getAuthMode = function() {
  return /** @type {!proto.sys.WifiAuthTypeEnum} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {!proto.sys.WifiAuthTypeEnum} value
 * @return {!proto.sys.WifiAP} returns this
 */
proto.sys.WifiAP.prototype.setAuthMode = function(value) {
  return jspb.Message.setProto3EnumField(this, 4, value);
};


/**
 * optional bool hidden = 5;
 * @return {boolean}
 */
proto.sys.WifiAP.prototype.getHidden = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 5, false));
};


/**
 * @param {boolean} value
 * @return {!proto.sys.WifiAP} returns this
 */
proto.sys.WifiAP.prototype.setHidden = function(value) {
  return jspb.Message.setProto3BooleanField(this, 5, value);
};


/**
 * optional uint32 max_connection = 6;
 * @return {number}
 */
proto.sys.WifiAP.prototype.getMaxConnection = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/**
 * @param {number} value
 * @return {!proto.sys.WifiAP} returns this
 */
proto.sys.WifiAP.prototype.setMaxConnection = function(value) {
  return jspb.Message.setProto3IntField(this, 6, value);
};


/**
 * optional uint32 beacon_interval = 7;
 * @return {number}
 */
proto.sys.WifiAP.prototype.getBeaconInterval = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 7, 0));
};


/**
 * @param {number} value
 * @return {!proto.sys.WifiAP} returns this
 */
proto.sys.WifiAP.prototype.setBeaconInterval = function(value) {
  return jspb.Message.setProto3IntField(this, 7, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.sys.Server.prototype.toObject = function(opt_includeInstance) {
  return proto.sys.Server.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.sys.Server} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sys.Server.toObject = function(includeInstance, msg) {
  var f, obj = {
    cport: jspb.Message.getFieldWithDefault(msg, 1, 0),
    port: jspb.Message.getFieldWithDefault(msg, 2, 0),
    ip: jspb.Message.getFieldWithDefault(msg, 3, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.sys.Server}
 */
proto.sys.Server.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.sys.Server;
  return proto.sys.Server.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.sys.Server} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.sys.Server}
 */
proto.sys.Server.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setCport(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setPort(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setIp(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.sys.Server.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.sys.Server.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.sys.Server} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sys.Server.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getCport();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getPort();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
  f = message.getIp();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
};


/**
 * optional int32 cport = 1;
 * @return {number}
 */
proto.sys.Server.prototype.getCport = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.sys.Server} returns this
 */
proto.sys.Server.prototype.setCport = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional int32 port = 2;
 * @return {number}
 */
proto.sys.Server.prototype.getPort = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.sys.Server} returns this
 */
proto.sys.Server.prototype.setPort = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional string ip = 3;
 * @return {string}
 */
proto.sys.Server.prototype.getIp = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.sys.Server} returns this
 */
proto.sys.Server.prototype.setIp = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.sys.NetworkConfig.repeatedFields_ = [3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.sys.NetworkConfig.prototype.toObject = function(opt_includeInstance) {
  return proto.sys.NetworkConfig.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.sys.NetworkConfig} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sys.NetworkConfig.toObject = function(includeInstance, msg) {
  var f, obj = {
    disableDhcp: jspb.Message.getBooleanFieldWithDefault(msg, 1, false),
    manualIp: (f = msg.getManualIp()) && proto.sys.IP.toObject(includeInstance, f),
    credentialsList: jspb.Message.toObjectList(msg.getCredentialsList(),
    proto.sys.WifiSTAEntry.toObject, includeInstance),
    ap: (f = msg.getAp()) && proto.sys.WifiAP.toObject(includeInstance, f),
    staPollingMaxS: jspb.Message.getFieldWithDefault(msg, 5, 0),
    apDurationS: jspb.Message.getFieldWithDefault(msg, 6, 0),
    staPollingMinS: jspb.Message.getFieldWithDefault(msg, 7, 0),
    dhcpTmoutS: jspb.Message.getFieldWithDefault(msg, 8, 0),
    ethBoot: jspb.Message.getBooleanFieldWithDefault(msg, 9, false),
    maxWifiRetry: jspb.Message.getFieldWithDefault(msg, 10, 0),
    maxApNum: jspb.Message.getFieldWithDefault(msg, 11, 0),
    maxSsidSize: jspb.Message.getFieldWithDefault(msg, 12, 0),
    maxPasswordSize: jspb.Message.getFieldWithDefault(msg, 13, 0),
    taskPriority: jspb.Message.getFieldWithDefault(msg, 14, 0),
    powerSaveMode: jspb.Message.getFieldWithDefault(msg, 15, 0),
    maxInitialWifiAttempt: jspb.Message.getFieldWithDefault(msg, 16, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.sys.NetworkConfig}
 */
proto.sys.NetworkConfig.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.sys.NetworkConfig;
  return proto.sys.NetworkConfig.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.sys.NetworkConfig} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.sys.NetworkConfig}
 */
proto.sys.NetworkConfig.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setDisableDhcp(value);
      break;
    case 2:
      var value = new proto.sys.IP;
      reader.readMessage(value,proto.sys.IP.deserializeBinaryFromReader);
      msg.setManualIp(value);
      break;
    case 3:
      var value = new proto.sys.WifiSTAEntry;
      reader.readMessage(value,proto.sys.WifiSTAEntry.deserializeBinaryFromReader);
      msg.addCredentials(value);
      break;
    case 4:
      var value = new proto.sys.WifiAP;
      reader.readMessage(value,proto.sys.WifiAP.deserializeBinaryFromReader);
      msg.setAp(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setStaPollingMaxS(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setApDurationS(value);
      break;
    case 7:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setStaPollingMinS(value);
      break;
    case 8:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setDhcpTmoutS(value);
      break;
    case 9:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setEthBoot(value);
      break;
    case 10:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setMaxWifiRetry(value);
      break;
    case 11:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setMaxApNum(value);
      break;
    case 12:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setMaxSsidSize(value);
      break;
    case 13:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setMaxPasswordSize(value);
      break;
    case 14:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setTaskPriority(value);
      break;
    case 15:
      var value = /** @type {!proto.sys.NetworkConfig.PowerSaveTypeEnum} */ (reader.readEnum());
      msg.setPowerSaveMode(value);
      break;
    case 16:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setMaxInitialWifiAttempt(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.sys.NetworkConfig.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.sys.NetworkConfig.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.sys.NetworkConfig} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sys.NetworkConfig.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getDisableDhcp();
  if (f) {
    writer.writeBool(
      1,
      f
    );
  }
  f = message.getManualIp();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.sys.IP.serializeBinaryToWriter
    );
  }
  f = message.getCredentialsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      3,
      f,
      proto.sys.WifiSTAEntry.serializeBinaryToWriter
    );
  }
  f = message.getAp();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      proto.sys.WifiAP.serializeBinaryToWriter
    );
  }
  f = message.getStaPollingMaxS();
  if (f !== 0) {
    writer.writeUint32(
      5,
      f
    );
  }
  f = message.getApDurationS();
  if (f !== 0) {
    writer.writeUint32(
      6,
      f
    );
  }
  f = message.getStaPollingMinS();
  if (f !== 0) {
    writer.writeUint32(
      7,
      f
    );
  }
  f = message.getDhcpTmoutS();
  if (f !== 0) {
    writer.writeUint32(
      8,
      f
    );
  }
  f = message.getEthBoot();
  if (f) {
    writer.writeBool(
      9,
      f
    );
  }
  f = message.getMaxWifiRetry();
  if (f !== 0) {
    writer.writeUint32(
      10,
      f
    );
  }
  f = message.getMaxApNum();
  if (f !== 0) {
    writer.writeUint32(
      11,
      f
    );
  }
  f = message.getMaxSsidSize();
  if (f !== 0) {
    writer.writeUint32(
      12,
      f
    );
  }
  f = message.getMaxPasswordSize();
  if (f !== 0) {
    writer.writeUint32(
      13,
      f
    );
  }
  f = message.getTaskPriority();
  if (f !== 0) {
    writer.writeUint32(
      14,
      f
    );
  }
  f = message.getPowerSaveMode();
  if (f !== 0.0) {
    writer.writeEnum(
      15,
      f
    );
  }
  f = message.getMaxInitialWifiAttempt();
  if (f !== 0) {
    writer.writeUint32(
      16,
      f
    );
  }
};


/**
 * @enum {number}
 */
proto.sys.NetworkConfig.PowerSaveTypeEnum = {
  WIFI_PS_NONE: 0,
  WIFI_PS_MIN_MODEM: 1,
  WIFI_PS_MAX_MODEM: 2
};

/**
 * optional bool disable_dhcp = 1;
 * @return {boolean}
 */
proto.sys.NetworkConfig.prototype.getDisableDhcp = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 1, false));
};


/**
 * @param {boolean} value
 * @return {!proto.sys.NetworkConfig} returns this
 */
proto.sys.NetworkConfig.prototype.setDisableDhcp = function(value) {
  return jspb.Message.setProto3BooleanField(this, 1, value);
};


/**
 * optional IP manual_ip = 2;
 * @return {?proto.sys.IP}
 */
proto.sys.NetworkConfig.prototype.getManualIp = function() {
  return /** @type{?proto.sys.IP} */ (
    jspb.Message.getWrapperField(this, proto.sys.IP, 2));
};


/**
 * @param {?proto.sys.IP|undefined} value
 * @return {!proto.sys.NetworkConfig} returns this
*/
proto.sys.NetworkConfig.prototype.setManualIp = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.sys.NetworkConfig} returns this
 */
proto.sys.NetworkConfig.prototype.clearManualIp = function() {
  return this.setManualIp(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sys.NetworkConfig.prototype.hasManualIp = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * repeated WifiSTAEntry credentials = 3;
 * @return {!Array<!proto.sys.WifiSTAEntry>}
 */
proto.sys.NetworkConfig.prototype.getCredentialsList = function() {
  return /** @type{!Array<!proto.sys.WifiSTAEntry>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.sys.WifiSTAEntry, 3));
};


/**
 * @param {!Array<!proto.sys.WifiSTAEntry>} value
 * @return {!proto.sys.NetworkConfig} returns this
*/
proto.sys.NetworkConfig.prototype.setCredentialsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 3, value);
};


/**
 * @param {!proto.sys.WifiSTAEntry=} opt_value
 * @param {number=} opt_index
 * @return {!proto.sys.WifiSTAEntry}
 */
proto.sys.NetworkConfig.prototype.addCredentials = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 3, opt_value, proto.sys.WifiSTAEntry, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.sys.NetworkConfig} returns this
 */
proto.sys.NetworkConfig.prototype.clearCredentialsList = function() {
  return this.setCredentialsList([]);
};


/**
 * optional WifiAP ap = 4;
 * @return {?proto.sys.WifiAP}
 */
proto.sys.NetworkConfig.prototype.getAp = function() {
  return /** @type{?proto.sys.WifiAP} */ (
    jspb.Message.getWrapperField(this, proto.sys.WifiAP, 4));
};


/**
 * @param {?proto.sys.WifiAP|undefined} value
 * @return {!proto.sys.NetworkConfig} returns this
*/
proto.sys.NetworkConfig.prototype.setAp = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.sys.NetworkConfig} returns this
 */
proto.sys.NetworkConfig.prototype.clearAp = function() {
  return this.setAp(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sys.NetworkConfig.prototype.hasAp = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional uint32 sta_polling_max_s = 5;
 * @return {number}
 */
proto.sys.NetworkConfig.prototype.getStaPollingMaxS = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.sys.NetworkConfig} returns this
 */
proto.sys.NetworkConfig.prototype.setStaPollingMaxS = function(value) {
  return jspb.Message.setProto3IntField(this, 5, value);
};


/**
 * optional uint32 ap_duration_s = 6;
 * @return {number}
 */
proto.sys.NetworkConfig.prototype.getApDurationS = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/**
 * @param {number} value
 * @return {!proto.sys.NetworkConfig} returns this
 */
proto.sys.NetworkConfig.prototype.setApDurationS = function(value) {
  return jspb.Message.setProto3IntField(this, 6, value);
};


/**
 * optional uint32 sta_polling_min_s = 7;
 * @return {number}
 */
proto.sys.NetworkConfig.prototype.getStaPollingMinS = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 7, 0));
};


/**
 * @param {number} value
 * @return {!proto.sys.NetworkConfig} returns this
 */
proto.sys.NetworkConfig.prototype.setStaPollingMinS = function(value) {
  return jspb.Message.setProto3IntField(this, 7, value);
};


/**
 * optional uint32 dhcp_tmout_s = 8;
 * @return {number}
 */
proto.sys.NetworkConfig.prototype.getDhcpTmoutS = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 8, 0));
};


/**
 * @param {number} value
 * @return {!proto.sys.NetworkConfig} returns this
 */
proto.sys.NetworkConfig.prototype.setDhcpTmoutS = function(value) {
  return jspb.Message.setProto3IntField(this, 8, value);
};


/**
 * optional bool eth_boot = 9;
 * @return {boolean}
 */
proto.sys.NetworkConfig.prototype.getEthBoot = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 9, false));
};


/**
 * @param {boolean} value
 * @return {!proto.sys.NetworkConfig} returns this
 */
proto.sys.NetworkConfig.prototype.setEthBoot = function(value) {
  return jspb.Message.setProto3BooleanField(this, 9, value);
};


/**
 * optional uint32 max_wifi_retry = 10;
 * @return {number}
 */
proto.sys.NetworkConfig.prototype.getMaxWifiRetry = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 10, 0));
};


/**
 * @param {number} value
 * @return {!proto.sys.NetworkConfig} returns this
 */
proto.sys.NetworkConfig.prototype.setMaxWifiRetry = function(value) {
  return jspb.Message.setProto3IntField(this, 10, value);
};


/**
 * optional uint32 max_ap_num = 11;
 * @return {number}
 */
proto.sys.NetworkConfig.prototype.getMaxApNum = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 11, 0));
};


/**
 * @param {number} value
 * @return {!proto.sys.NetworkConfig} returns this
 */
proto.sys.NetworkConfig.prototype.setMaxApNum = function(value) {
  return jspb.Message.setProto3IntField(this, 11, value);
};


/**
 * optional uint32 max_ssid_size = 12;
 * @return {number}
 */
proto.sys.NetworkConfig.prototype.getMaxSsidSize = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 12, 0));
};


/**
 * @param {number} value
 * @return {!proto.sys.NetworkConfig} returns this
 */
proto.sys.NetworkConfig.prototype.setMaxSsidSize = function(value) {
  return jspb.Message.setProto3IntField(this, 12, value);
};


/**
 * optional uint32 max_password_size = 13;
 * @return {number}
 */
proto.sys.NetworkConfig.prototype.getMaxPasswordSize = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 13, 0));
};


/**
 * @param {number} value
 * @return {!proto.sys.NetworkConfig} returns this
 */
proto.sys.NetworkConfig.prototype.setMaxPasswordSize = function(value) {
  return jspb.Message.setProto3IntField(this, 13, value);
};


/**
 * optional uint32 task_priority = 14;
 * @return {number}
 */
proto.sys.NetworkConfig.prototype.getTaskPriority = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 14, 0));
};


/**
 * @param {number} value
 * @return {!proto.sys.NetworkConfig} returns this
 */
proto.sys.NetworkConfig.prototype.setTaskPriority = function(value) {
  return jspb.Message.setProto3IntField(this, 14, value);
};


/**
 * optional PowerSaveTypeEnum power_save_mode = 15;
 * @return {!proto.sys.NetworkConfig.PowerSaveTypeEnum}
 */
proto.sys.NetworkConfig.prototype.getPowerSaveMode = function() {
  return /** @type {!proto.sys.NetworkConfig.PowerSaveTypeEnum} */ (jspb.Message.getFieldWithDefault(this, 15, 0));
};


/**
 * @param {!proto.sys.NetworkConfig.PowerSaveTypeEnum} value
 * @return {!proto.sys.NetworkConfig} returns this
 */
proto.sys.NetworkConfig.prototype.setPowerSaveMode = function(value) {
  return jspb.Message.setProto3EnumField(this, 15, value);
};


/**
 * optional uint32 max_initial_wifi_attempt = 16;
 * @return {number}
 */
proto.sys.NetworkConfig.prototype.getMaxInitialWifiAttempt = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 16, 0));
};


/**
 * @param {number} value
 * @return {!proto.sys.NetworkConfig} returns this
 */
proto.sys.NetworkConfig.prototype.setMaxInitialWifiAttempt = function(value) {
  return jspb.Message.setProto3IntField(this, 16, value);
};


/**
 * @enum {number}
 */
proto.sys.WifiAuthTypeEnum = {
  AUTH_UNKNOWN: 0,
  AUTH_OPEN: 1,
  AUTH_WEP: 2,
  AUTH_WPA_PSK: 3,
  AUTH_WPA2_PSK: 4,
  AUTH_WPA_WPA2_PSK: 5,
  AUTH_WPA2_ENTERPRISE: 6,
  AUTH_WPA3_PSK: 7,
  AUTH_WPA2_WPA3_PSK: 8,
  AUTH_WAPI_PSK: 9
};

/**
 * @enum {number}
 */
proto.sys.WifiRadioTypesEnum = {
  PHY_UNKNOWN: 0,
  PHY_11B: 1,
  PHY_11G: 2,
  PHY_11N: 3,
  PHY_LR: 4,
  PHY_WPS: 5,
  PHY_FTM_RESPONDER: 6,
  PHY_FTM_INITIATOR: 7
};

goog.object.extend(exports, proto.sys);
