// source: Squeezelite.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global =
    (typeof globalThis !== 'undefined' && globalThis) ||
    (typeof window !== 'undefined' && window) ||
    (typeof global !== 'undefined' && global) ||
    (typeof self !== 'undefined' && self) ||
    (function () { return this; }).call(null) ||
    Function('return this')();

var customoptions_pb = require('./customoptions_pb.js');
goog.object.extend(proto, customoptions_pb);
var nanopb_pb = require('./nanopb_pb.js');
goog.object.extend(proto, nanopb_pb);
goog.exportSymbol('proto.sys.BufferOption', null, global);
goog.exportSymbol('proto.sys.CodexEnum', null, global);
goog.exportSymbol('proto.sys.DebugLevelEnum', null, global);
goog.exportSymbol('proto.sys.DebugOptions', null, global);
goog.exportSymbol('proto.sys.OutputBT', null, global);
goog.exportSymbol('proto.sys.OutputTypeEnum', null, global);
goog.exportSymbol('proto.sys.RatesOption', null, global);
goog.exportSymbol('proto.sys.ResampleAlgorithm', null, global);
goog.exportSymbol('proto.sys.ResampleOptions', null, global);
goog.exportSymbol('proto.sys.SampleRate', null, global);
goog.exportSymbol('proto.sys.Squeezelite', null, global);
goog.exportSymbol('proto.sys.SqueezeliteProfile', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.sys.OutputBT = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.sys.OutputBT, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.sys.OutputBT.displayName = 'proto.sys.OutputBT';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.sys.ResampleOptions = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.sys.ResampleOptions, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.sys.ResampleOptions.displayName = 'proto.sys.ResampleOptions';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.sys.RatesOption = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.sys.RatesOption.repeatedFields_, null);
};
goog.inherits(proto.sys.RatesOption, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.sys.RatesOption.displayName = 'proto.sys.RatesOption';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.sys.BufferOption = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.sys.BufferOption, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.sys.BufferOption.displayName = 'proto.sys.BufferOption';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.sys.DebugOptions = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.sys.DebugOptions, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.sys.DebugOptions.displayName = 'proto.sys.DebugOptions';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.sys.Squeezelite = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.sys.Squeezelite.repeatedFields_, null);
};
goog.inherits(proto.sys.Squeezelite, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.sys.Squeezelite.displayName = 'proto.sys.Squeezelite';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.sys.SqueezeliteProfile = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.sys.SqueezeliteProfile, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.sys.SqueezeliteProfile.displayName = 'proto.sys.SqueezeliteProfile';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.sys.OutputBT.prototype.toObject = function(opt_includeInstance) {
  return proto.sys.OutputBT.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.sys.OutputBT} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sys.OutputBT.toObject = function(includeInstance, msg) {
  var f, obj = {
    sinkName: jspb.Message.getFieldWithDefault(msg, 1, ""),
    pin: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.sys.OutputBT}
 */
proto.sys.OutputBT.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.sys.OutputBT;
  return proto.sys.OutputBT.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.sys.OutputBT} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.sys.OutputBT}
 */
proto.sys.OutputBT.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setSinkName(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setPin(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.sys.OutputBT.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.sys.OutputBT.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.sys.OutputBT} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sys.OutputBT.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSinkName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getPin();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional string sink_name = 1;
 * @return {string}
 */
proto.sys.OutputBT.prototype.getSinkName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.sys.OutputBT} returns this
 */
proto.sys.OutputBT.prototype.setSinkName = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string pin = 2;
 * @return {string}
 */
proto.sys.OutputBT.prototype.getPin = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.sys.OutputBT} returns this
 */
proto.sys.OutputBT.prototype.setPin = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.sys.ResampleOptions.prototype.toObject = function(opt_includeInstance) {
  return proto.sys.ResampleOptions.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.sys.ResampleOptions} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sys.ResampleOptions.toObject = function(includeInstance, msg) {
  var f, obj = {
    algorithm: jspb.Message.getFieldWithDefault(msg, 1, 0),
    interpolateFilterCoefficients: jspb.Message.getBooleanFieldWithDefault(msg, 2, false)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.sys.ResampleOptions}
 */
proto.sys.ResampleOptions.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.sys.ResampleOptions;
  return proto.sys.ResampleOptions.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.sys.ResampleOptions} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.sys.ResampleOptions}
 */
proto.sys.ResampleOptions.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.sys.ResampleAlgorithm} */ (reader.readEnum());
      msg.setAlgorithm(value);
      break;
    case 2:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setInterpolateFilterCoefficients(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.sys.ResampleOptions.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.sys.ResampleOptions.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.sys.ResampleOptions} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sys.ResampleOptions.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getAlgorithm();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getInterpolateFilterCoefficients();
  if (f) {
    writer.writeBool(
      2,
      f
    );
  }
};


/**
 * optional ResampleAlgorithm algorithm = 1;
 * @return {!proto.sys.ResampleAlgorithm}
 */
proto.sys.ResampleOptions.prototype.getAlgorithm = function() {
  return /** @type {!proto.sys.ResampleAlgorithm} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {!proto.sys.ResampleAlgorithm} value
 * @return {!proto.sys.ResampleOptions} returns this
 */
proto.sys.ResampleOptions.prototype.setAlgorithm = function(value) {
  return jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * optional bool interpolate_filter_coefficients = 2;
 * @return {boolean}
 */
proto.sys.ResampleOptions.prototype.getInterpolateFilterCoefficients = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 2, false));
};


/**
 * @param {boolean} value
 * @return {!proto.sys.ResampleOptions} returns this
 */
proto.sys.ResampleOptions.prototype.setInterpolateFilterCoefficients = function(value) {
  return jspb.Message.setProto3BooleanField(this, 2, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.sys.RatesOption.repeatedFields_ = [3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.sys.RatesOption.prototype.toObject = function(opt_includeInstance) {
  return proto.sys.RatesOption.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.sys.RatesOption} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sys.RatesOption.toObject = function(includeInstance, msg) {
  var f, obj = {
    min: jspb.Message.getFieldWithDefault(msg, 1, 0),
    max: jspb.Message.getFieldWithDefault(msg, 2, 0),
    listList: (f = jspb.Message.getRepeatedField(msg, 3)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.sys.RatesOption}
 */
proto.sys.RatesOption.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.sys.RatesOption;
  return proto.sys.RatesOption.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.sys.RatesOption} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.sys.RatesOption}
 */
proto.sys.RatesOption.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.sys.SampleRate} */ (reader.readEnum());
      msg.setMin(value);
      break;
    case 2:
      var value = /** @type {!proto.sys.SampleRate} */ (reader.readEnum());
      msg.setMax(value);
      break;
    case 3:
      var values = /** @type {!Array<!proto.sys.SampleRate>} */ (reader.isDelimited() ? reader.readPackedEnum() : [reader.readEnum()]);
      for (var i = 0; i < values.length; i++) {
        msg.addList(values[i]);
      }
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.sys.RatesOption.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.sys.RatesOption.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.sys.RatesOption} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sys.RatesOption.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getMin();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getMax();
  if (f !== 0.0) {
    writer.writeEnum(
      2,
      f
    );
  }
  f = message.getListList();
  if (f.length > 0) {
    writer.writePackedEnum(
      3,
      f
    );
  }
};


/**
 * optional SampleRate min = 1;
 * @return {!proto.sys.SampleRate}
 */
proto.sys.RatesOption.prototype.getMin = function() {
  return /** @type {!proto.sys.SampleRate} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {!proto.sys.SampleRate} value
 * @return {!proto.sys.RatesOption} returns this
 */
proto.sys.RatesOption.prototype.setMin = function(value) {
  return jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * optional SampleRate max = 2;
 * @return {!proto.sys.SampleRate}
 */
proto.sys.RatesOption.prototype.getMax = function() {
  return /** @type {!proto.sys.SampleRate} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {!proto.sys.SampleRate} value
 * @return {!proto.sys.RatesOption} returns this
 */
proto.sys.RatesOption.prototype.setMax = function(value) {
  return jspb.Message.setProto3EnumField(this, 2, value);
};


/**
 * repeated SampleRate list = 3;
 * @return {!Array<!proto.sys.SampleRate>}
 */
proto.sys.RatesOption.prototype.getListList = function() {
  return /** @type {!Array<!proto.sys.SampleRate>} */ (jspb.Message.getRepeatedField(this, 3));
};


/**
 * @param {!Array<!proto.sys.SampleRate>} value
 * @return {!proto.sys.RatesOption} returns this
 */
proto.sys.RatesOption.prototype.setListList = function(value) {
  return jspb.Message.setField(this, 3, value || []);
};


/**
 * @param {!proto.sys.SampleRate} value
 * @param {number=} opt_index
 * @return {!proto.sys.RatesOption} returns this
 */
proto.sys.RatesOption.prototype.addList = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 3, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.sys.RatesOption} returns this
 */
proto.sys.RatesOption.prototype.clearListList = function() {
  return this.setListList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.sys.BufferOption.prototype.toObject = function(opt_includeInstance) {
  return proto.sys.BufferOption.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.sys.BufferOption} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sys.BufferOption.toObject = function(includeInstance, msg) {
  var f, obj = {
    stream: jspb.Message.getFieldWithDefault(msg, 1, 0),
    output: jspb.Message.getFieldWithDefault(msg, 2, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.sys.BufferOption}
 */
proto.sys.BufferOption.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.sys.BufferOption;
  return proto.sys.BufferOption.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.sys.BufferOption} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.sys.BufferOption}
 */
proto.sys.BufferOption.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setStream(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setOutput(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.sys.BufferOption.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.sys.BufferOption.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.sys.BufferOption} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sys.BufferOption.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getStream();
  if (f !== 0) {
    writer.writeUint32(
      1,
      f
    );
  }
  f = message.getOutput();
  if (f !== 0) {
    writer.writeUint32(
      2,
      f
    );
  }
};


/**
 * optional uint32 stream = 1;
 * @return {number}
 */
proto.sys.BufferOption.prototype.getStream = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.sys.BufferOption} returns this
 */
proto.sys.BufferOption.prototype.setStream = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional uint32 output = 2;
 * @return {number}
 */
proto.sys.BufferOption.prototype.getOutput = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.sys.BufferOption} returns this
 */
proto.sys.BufferOption.prototype.setOutput = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.sys.DebugOptions.prototype.toObject = function(opt_includeInstance) {
  return proto.sys.DebugOptions.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.sys.DebugOptions} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sys.DebugOptions.toObject = function(includeInstance, msg) {
  var f, obj = {
    output: jspb.Message.getFieldWithDefault(msg, 1, 0),
    stream: jspb.Message.getFieldWithDefault(msg, 2, 0),
    decode: jspb.Message.getFieldWithDefault(msg, 3, 0),
    slimproto: jspb.Message.getFieldWithDefault(msg, 4, 0),
    ir: jspb.Message.getFieldWithDefault(msg, 5, 0),
    all: jspb.Message.getFieldWithDefault(msg, 6, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.sys.DebugOptions}
 */
proto.sys.DebugOptions.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.sys.DebugOptions;
  return proto.sys.DebugOptions.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.sys.DebugOptions} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.sys.DebugOptions}
 */
proto.sys.DebugOptions.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.sys.DebugLevelEnum} */ (reader.readEnum());
      msg.setOutput(value);
      break;
    case 2:
      var value = /** @type {!proto.sys.DebugLevelEnum} */ (reader.readEnum());
      msg.setStream(value);
      break;
    case 3:
      var value = /** @type {!proto.sys.DebugLevelEnum} */ (reader.readEnum());
      msg.setDecode(value);
      break;
    case 4:
      var value = /** @type {!proto.sys.DebugLevelEnum} */ (reader.readEnum());
      msg.setSlimproto(value);
      break;
    case 5:
      var value = /** @type {!proto.sys.DebugLevelEnum} */ (reader.readEnum());
      msg.setIr(value);
      break;
    case 6:
      var value = /** @type {!proto.sys.DebugLevelEnum} */ (reader.readEnum());
      msg.setAll(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.sys.DebugOptions.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.sys.DebugOptions.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.sys.DebugOptions} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sys.DebugOptions.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getOutput();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getStream();
  if (f !== 0.0) {
    writer.writeEnum(
      2,
      f
    );
  }
  f = message.getDecode();
  if (f !== 0.0) {
    writer.writeEnum(
      3,
      f
    );
  }
  f = message.getSlimproto();
  if (f !== 0.0) {
    writer.writeEnum(
      4,
      f
    );
  }
  f = message.getIr();
  if (f !== 0.0) {
    writer.writeEnum(
      5,
      f
    );
  }
  f = message.getAll();
  if (f !== 0.0) {
    writer.writeEnum(
      6,
      f
    );
  }
};


/**
 * optional DebugLevelEnum output = 1;
 * @return {!proto.sys.DebugLevelEnum}
 */
proto.sys.DebugOptions.prototype.getOutput = function() {
  return /** @type {!proto.sys.DebugLevelEnum} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {!proto.sys.DebugLevelEnum} value
 * @return {!proto.sys.DebugOptions} returns this
 */
proto.sys.DebugOptions.prototype.setOutput = function(value) {
  return jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * optional DebugLevelEnum stream = 2;
 * @return {!proto.sys.DebugLevelEnum}
 */
proto.sys.DebugOptions.prototype.getStream = function() {
  return /** @type {!proto.sys.DebugLevelEnum} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {!proto.sys.DebugLevelEnum} value
 * @return {!proto.sys.DebugOptions} returns this
 */
proto.sys.DebugOptions.prototype.setStream = function(value) {
  return jspb.Message.setProto3EnumField(this, 2, value);
};


/**
 * optional DebugLevelEnum decode = 3;
 * @return {!proto.sys.DebugLevelEnum}
 */
proto.sys.DebugOptions.prototype.getDecode = function() {
  return /** @type {!proto.sys.DebugLevelEnum} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {!proto.sys.DebugLevelEnum} value
 * @return {!proto.sys.DebugOptions} returns this
 */
proto.sys.DebugOptions.prototype.setDecode = function(value) {
  return jspb.Message.setProto3EnumField(this, 3, value);
};


/**
 * optional DebugLevelEnum slimproto = 4;
 * @return {!proto.sys.DebugLevelEnum}
 */
proto.sys.DebugOptions.prototype.getSlimproto = function() {
  return /** @type {!proto.sys.DebugLevelEnum} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {!proto.sys.DebugLevelEnum} value
 * @return {!proto.sys.DebugOptions} returns this
 */
proto.sys.DebugOptions.prototype.setSlimproto = function(value) {
  return jspb.Message.setProto3EnumField(this, 4, value);
};


/**
 * optional DebugLevelEnum ir = 5;
 * @return {!proto.sys.DebugLevelEnum}
 */
proto.sys.DebugOptions.prototype.getIr = function() {
  return /** @type {!proto.sys.DebugLevelEnum} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {!proto.sys.DebugLevelEnum} value
 * @return {!proto.sys.DebugOptions} returns this
 */
proto.sys.DebugOptions.prototype.setIr = function(value) {
  return jspb.Message.setProto3EnumField(this, 5, value);
};


/**
 * optional DebugLevelEnum all = 6;
 * @return {!proto.sys.DebugLevelEnum}
 */
proto.sys.DebugOptions.prototype.getAll = function() {
  return /** @type {!proto.sys.DebugLevelEnum} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/**
 * @param {!proto.sys.DebugLevelEnum} value
 * @return {!proto.sys.DebugOptions} returns this
 */
proto.sys.DebugOptions.prototype.setAll = function(value) {
  return jspb.Message.setProto3EnumField(this, 6, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.sys.Squeezelite.repeatedFields_ = [13,14];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.sys.Squeezelite.prototype.toObject = function(opt_includeInstance) {
  return proto.sys.Squeezelite.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.sys.Squeezelite} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sys.Squeezelite.toObject = function(includeInstance, msg) {
  var f, obj = {
    outputType: jspb.Message.getFieldWithDefault(msg, 1, 0),
    rates: (f = msg.getRates()) && proto.sys.RatesOption.toObject(includeInstance, f),
    ampGpioTimeout: jspb.Message.getFieldWithDefault(msg, 3, 0),
    wavAiffHeaderParsing: jspb.Message.getBooleanFieldWithDefault(msg, 4, false),
    serverNameIp: jspb.Message.getFieldWithDefault(msg, 5, ""),
    serverPort: jspb.Message.getFieldWithDefault(msg, 6, 0),
    enabled: jspb.Message.getBooleanFieldWithDefault(msg, 7, false),
    outputBt: (f = msg.getOutputBt()) && proto.sys.OutputBT.toObject(includeInstance, f),
    log: (f = msg.getLog()) && proto.sys.DebugOptions.toObject(includeInstance, f),
    maxRate: jspb.Message.getFieldWithDefault(msg, 10, 0),
    buffers: (f = msg.getBuffers()) && proto.sys.BufferOption.toObject(includeInstance, f),
    resample: jspb.Message.getFieldWithDefault(msg, 12, ""),
    includedCodexList: (f = jspb.Message.getRepeatedField(msg, 13)) == null ? undefined : f,
    excludedCodexList: (f = jspb.Message.getRepeatedField(msg, 14)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.sys.Squeezelite}
 */
proto.sys.Squeezelite.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.sys.Squeezelite;
  return proto.sys.Squeezelite.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.sys.Squeezelite} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.sys.Squeezelite}
 */
proto.sys.Squeezelite.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.sys.OutputTypeEnum} */ (reader.readEnum());
      msg.setOutputType(value);
      break;
    case 2:
      var value = new proto.sys.RatesOption;
      reader.readMessage(value,proto.sys.RatesOption.deserializeBinaryFromReader);
      msg.setRates(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setAmpGpioTimeout(value);
      break;
    case 4:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setWavAiffHeaderParsing(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setServerNameIp(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setServerPort(value);
      break;
    case 7:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setEnabled(value);
      break;
    case 8:
      var value = new proto.sys.OutputBT;
      reader.readMessage(value,proto.sys.OutputBT.deserializeBinaryFromReader);
      msg.setOutputBt(value);
      break;
    case 9:
      var value = new proto.sys.DebugOptions;
      reader.readMessage(value,proto.sys.DebugOptions.deserializeBinaryFromReader);
      msg.setLog(value);
      break;
    case 10:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setMaxRate(value);
      break;
    case 11:
      var value = new proto.sys.BufferOption;
      reader.readMessage(value,proto.sys.BufferOption.deserializeBinaryFromReader);
      msg.setBuffers(value);
      break;
    case 12:
      var value = /** @type {string} */ (reader.readString());
      msg.setResample(value);
      break;
    case 13:
      var values = /** @type {!Array<!proto.sys.CodexEnum>} */ (reader.isDelimited() ? reader.readPackedEnum() : [reader.readEnum()]);
      for (var i = 0; i < values.length; i++) {
        msg.addIncludedCodex(values[i]);
      }
      break;
    case 14:
      var values = /** @type {!Array<!proto.sys.CodexEnum>} */ (reader.isDelimited() ? reader.readPackedEnum() : [reader.readEnum()]);
      for (var i = 0; i < values.length; i++) {
        msg.addExcludedCodex(values[i]);
      }
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.sys.Squeezelite.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.sys.Squeezelite.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.sys.Squeezelite} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sys.Squeezelite.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getOutputType();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getRates();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.sys.RatesOption.serializeBinaryToWriter
    );
  }
  f = message.getAmpGpioTimeout();
  if (f !== 0) {
    writer.writeInt32(
      3,
      f
    );
  }
  f = message.getWavAiffHeaderParsing();
  if (f) {
    writer.writeBool(
      4,
      f
    );
  }
  f = message.getServerNameIp();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getServerPort();
  if (f !== 0) {
    writer.writeUint32(
      6,
      f
    );
  }
  f = message.getEnabled();
  if (f) {
    writer.writeBool(
      7,
      f
    );
  }
  f = message.getOutputBt();
  if (f != null) {
    writer.writeMessage(
      8,
      f,
      proto.sys.OutputBT.serializeBinaryToWriter
    );
  }
  f = message.getLog();
  if (f != null) {
    writer.writeMessage(
      9,
      f,
      proto.sys.DebugOptions.serializeBinaryToWriter
    );
  }
  f = message.getMaxRate();
  if (f !== 0) {
    writer.writeUint32(
      10,
      f
    );
  }
  f = message.getBuffers();
  if (f != null) {
    writer.writeMessage(
      11,
      f,
      proto.sys.BufferOption.serializeBinaryToWriter
    );
  }
  f = message.getResample();
  if (f.length > 0) {
    writer.writeString(
      12,
      f
    );
  }
  f = message.getIncludedCodexList();
  if (f.length > 0) {
    writer.writePackedEnum(
      13,
      f
    );
  }
  f = message.getExcludedCodexList();
  if (f.length > 0) {
    writer.writePackedEnum(
      14,
      f
    );
  }
};


/**
 * optional OutputTypeEnum output_type = 1;
 * @return {!proto.sys.OutputTypeEnum}
 */
proto.sys.Squeezelite.prototype.getOutputType = function() {
  return /** @type {!proto.sys.OutputTypeEnum} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {!proto.sys.OutputTypeEnum} value
 * @return {!proto.sys.Squeezelite} returns this
 */
proto.sys.Squeezelite.prototype.setOutputType = function(value) {
  return jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * optional RatesOption rates = 2;
 * @return {?proto.sys.RatesOption}
 */
proto.sys.Squeezelite.prototype.getRates = function() {
  return /** @type{?proto.sys.RatesOption} */ (
    jspb.Message.getWrapperField(this, proto.sys.RatesOption, 2));
};


/**
 * @param {?proto.sys.RatesOption|undefined} value
 * @return {!proto.sys.Squeezelite} returns this
*/
proto.sys.Squeezelite.prototype.setRates = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.sys.Squeezelite} returns this
 */
proto.sys.Squeezelite.prototype.clearRates = function() {
  return this.setRates(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sys.Squeezelite.prototype.hasRates = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional int32 amp_gpio_timeout = 3;
 * @return {number}
 */
proto.sys.Squeezelite.prototype.getAmpGpioTimeout = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.sys.Squeezelite} returns this
 */
proto.sys.Squeezelite.prototype.setAmpGpioTimeout = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional bool wav_aiff_header_parsing = 4;
 * @return {boolean}
 */
proto.sys.Squeezelite.prototype.getWavAiffHeaderParsing = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 4, false));
};


/**
 * @param {boolean} value
 * @return {!proto.sys.Squeezelite} returns this
 */
proto.sys.Squeezelite.prototype.setWavAiffHeaderParsing = function(value) {
  return jspb.Message.setProto3BooleanField(this, 4, value);
};


/**
 * optional string server_name_ip = 5;
 * @return {string}
 */
proto.sys.Squeezelite.prototype.getServerNameIp = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.sys.Squeezelite} returns this
 */
proto.sys.Squeezelite.prototype.setServerNameIp = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional uint32 server_port = 6;
 * @return {number}
 */
proto.sys.Squeezelite.prototype.getServerPort = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/**
 * @param {number} value
 * @return {!proto.sys.Squeezelite} returns this
 */
proto.sys.Squeezelite.prototype.setServerPort = function(value) {
  return jspb.Message.setProto3IntField(this, 6, value);
};


/**
 * optional bool enabled = 7;
 * @return {boolean}
 */
proto.sys.Squeezelite.prototype.getEnabled = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 7, false));
};


/**
 * @param {boolean} value
 * @return {!proto.sys.Squeezelite} returns this
 */
proto.sys.Squeezelite.prototype.setEnabled = function(value) {
  return jspb.Message.setProto3BooleanField(this, 7, value);
};


/**
 * optional OutputBT output_bt = 8;
 * @return {?proto.sys.OutputBT}
 */
proto.sys.Squeezelite.prototype.getOutputBt = function() {
  return /** @type{?proto.sys.OutputBT} */ (
    jspb.Message.getWrapperField(this, proto.sys.OutputBT, 8));
};


/**
 * @param {?proto.sys.OutputBT|undefined} value
 * @return {!proto.sys.Squeezelite} returns this
*/
proto.sys.Squeezelite.prototype.setOutputBt = function(value) {
  return jspb.Message.setWrapperField(this, 8, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.sys.Squeezelite} returns this
 */
proto.sys.Squeezelite.prototype.clearOutputBt = function() {
  return this.setOutputBt(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sys.Squeezelite.prototype.hasOutputBt = function() {
  return jspb.Message.getField(this, 8) != null;
};


/**
 * optional DebugOptions log = 9;
 * @return {?proto.sys.DebugOptions}
 */
proto.sys.Squeezelite.prototype.getLog = function() {
  return /** @type{?proto.sys.DebugOptions} */ (
    jspb.Message.getWrapperField(this, proto.sys.DebugOptions, 9));
};


/**
 * @param {?proto.sys.DebugOptions|undefined} value
 * @return {!proto.sys.Squeezelite} returns this
*/
proto.sys.Squeezelite.prototype.setLog = function(value) {
  return jspb.Message.setWrapperField(this, 9, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.sys.Squeezelite} returns this
 */
proto.sys.Squeezelite.prototype.clearLog = function() {
  return this.setLog(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sys.Squeezelite.prototype.hasLog = function() {
  return jspb.Message.getField(this, 9) != null;
};


/**
 * optional uint32 max_rate = 10;
 * @return {number}
 */
proto.sys.Squeezelite.prototype.getMaxRate = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 10, 0));
};


/**
 * @param {number} value
 * @return {!proto.sys.Squeezelite} returns this
 */
proto.sys.Squeezelite.prototype.setMaxRate = function(value) {
  return jspb.Message.setProto3IntField(this, 10, value);
};


/**
 * optional BufferOption buffers = 11;
 * @return {?proto.sys.BufferOption}
 */
proto.sys.Squeezelite.prototype.getBuffers = function() {
  return /** @type{?proto.sys.BufferOption} */ (
    jspb.Message.getWrapperField(this, proto.sys.BufferOption, 11));
};


/**
 * @param {?proto.sys.BufferOption|undefined} value
 * @return {!proto.sys.Squeezelite} returns this
*/
proto.sys.Squeezelite.prototype.setBuffers = function(value) {
  return jspb.Message.setWrapperField(this, 11, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.sys.Squeezelite} returns this
 */
proto.sys.Squeezelite.prototype.clearBuffers = function() {
  return this.setBuffers(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sys.Squeezelite.prototype.hasBuffers = function() {
  return jspb.Message.getField(this, 11) != null;
};


/**
 * optional string resample = 12;
 * @return {string}
 */
proto.sys.Squeezelite.prototype.getResample = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 12, ""));
};


/**
 * @param {string} value
 * @return {!proto.sys.Squeezelite} returns this
 */
proto.sys.Squeezelite.prototype.setResample = function(value) {
  return jspb.Message.setProto3StringField(this, 12, value);
};


/**
 * repeated CodexEnum included_codex = 13;
 * @return {!Array<!proto.sys.CodexEnum>}
 */
proto.sys.Squeezelite.prototype.getIncludedCodexList = function() {
  return /** @type {!Array<!proto.sys.CodexEnum>} */ (jspb.Message.getRepeatedField(this, 13));
};


/**
 * @param {!Array<!proto.sys.CodexEnum>} value
 * @return {!proto.sys.Squeezelite} returns this
 */
proto.sys.Squeezelite.prototype.setIncludedCodexList = function(value) {
  return jspb.Message.setField(this, 13, value || []);
};


/**
 * @param {!proto.sys.CodexEnum} value
 * @param {number=} opt_index
 * @return {!proto.sys.Squeezelite} returns this
 */
proto.sys.Squeezelite.prototype.addIncludedCodex = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 13, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.sys.Squeezelite} returns this
 */
proto.sys.Squeezelite.prototype.clearIncludedCodexList = function() {
  return this.setIncludedCodexList([]);
};


/**
 * repeated CodexEnum excluded_codex = 14;
 * @return {!Array<!proto.sys.CodexEnum>}
 */
proto.sys.Squeezelite.prototype.getExcludedCodexList = function() {
  return /** @type {!Array<!proto.sys.CodexEnum>} */ (jspb.Message.getRepeatedField(this, 14));
};


/**
 * @param {!Array<!proto.sys.CodexEnum>} value
 * @return {!proto.sys.Squeezelite} returns this
 */
proto.sys.Squeezelite.prototype.setExcludedCodexList = function(value) {
  return jspb.Message.setField(this, 14, value || []);
};


/**
 * @param {!proto.sys.CodexEnum} value
 * @param {number=} opt_index
 * @return {!proto.sys.Squeezelite} returns this
 */
proto.sys.Squeezelite.prototype.addExcludedCodex = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 14, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.sys.Squeezelite} returns this
 */
proto.sys.Squeezelite.prototype.clearExcludedCodexList = function() {
  return this.setExcludedCodexList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.sys.SqueezeliteProfile.prototype.toObject = function(opt_includeInstance) {
  return proto.sys.SqueezeliteProfile.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.sys.SqueezeliteProfile} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sys.SqueezeliteProfile.toObject = function(includeInstance, msg) {
  var f, obj = {
    name: jspb.Message.getFieldWithDefault(msg, 1, ""),
    profile: (f = msg.getProfile()) && proto.sys.Squeezelite.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.sys.SqueezeliteProfile}
 */
proto.sys.SqueezeliteProfile.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.sys.SqueezeliteProfile;
  return proto.sys.SqueezeliteProfile.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.sys.SqueezeliteProfile} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.sys.SqueezeliteProfile}
 */
proto.sys.SqueezeliteProfile.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 2:
      var value = new proto.sys.Squeezelite;
      reader.readMessage(value,proto.sys.Squeezelite.deserializeBinaryFromReader);
      msg.setProfile(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.sys.SqueezeliteProfile.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.sys.SqueezeliteProfile.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.sys.SqueezeliteProfile} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sys.SqueezeliteProfile.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getProfile();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.sys.Squeezelite.serializeBinaryToWriter
    );
  }
};


/**
 * optional string name = 1;
 * @return {string}
 */
proto.sys.SqueezeliteProfile.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.sys.SqueezeliteProfile} returns this
 */
proto.sys.SqueezeliteProfile.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional Squeezelite profile = 2;
 * @return {?proto.sys.Squeezelite}
 */
proto.sys.SqueezeliteProfile.prototype.getProfile = function() {
  return /** @type{?proto.sys.Squeezelite} */ (
    jspb.Message.getWrapperField(this, proto.sys.Squeezelite, 2));
};


/**
 * @param {?proto.sys.Squeezelite|undefined} value
 * @return {!proto.sys.SqueezeliteProfile} returns this
*/
proto.sys.SqueezeliteProfile.prototype.setProfile = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.sys.SqueezeliteProfile} returns this
 */
proto.sys.SqueezeliteProfile.prototype.clearProfile = function() {
  return this.setProfile(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sys.SqueezeliteProfile.prototype.hasProfile = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * @enum {number}
 */
proto.sys.OutputTypeEnum = {
  OUTPUT_UNKNOWN: 0,
  OUTPUT_I2S: 1,
  OUTPUT_SPDIF: 2,
  OUTPUT_BLUETOOTH: 3
};

/**
 * @enum {number}
 */
proto.sys.ResampleAlgorithm = {
  RA_DISABLED: 0,
  RA_BASIC_LINEAR: 1,
  RA_THIRTEEN_TAPS: 2,
  RA_TWENTY_ONE_TAPS: 3
};

/**
 * @enum {number}
 */
proto.sys.SampleRate = {
  SAMPLE_RATE_UNSPECIFIED: 0,
  SAMPLE_RATE_8000: 8000,
  SAMPLE_RATE_11025: 11025,
  SAMPLE_RATE_12000: 12000,
  SAMPLE_RATE_16000: 16000,
  SAMPLE_RATE_22050: 22050,
  SAMPLE_RATE_24000: 24000,
  SAMPLE_RATE_32000: 32000,
  SAMPLE_RATE_44100: 44100,
  SAMPLE_RATE_48000: 48000,
  SAMPLE_RATE_88200: 88200,
  SAMPLE_RATE_96000: 96000,
  SAMPLE_RATE_176400: 176400,
  SAMPLE_RATE_192000: 192000,
  SAMPLE_RATE_352800: 352800,
  SAMPLE_RATE_384000: 384000,
  SAMPLE_RATE_705600: 705600,
  SAMPLE_RATE_768000: 768000
};

/**
 * @enum {number}
 */
proto.sys.DebugLevelEnum = {
  DEFAULT: 0,
  ERROR: 1,
  WARN: 2,
  INFO: 3,
  DEBUG: 4,
  SDEBUG: 5
};

/**
 * @enum {number}
 */
proto.sys.CodexEnum = {
  C_UNDEFINED: 0,
  C_ALAC: 1,
  C_OGG: 2,
  C_OPS: 3,
  C_FLAC: 4,
  C_PCM: 5,
  C_MP3: 6,
  C_MAD: 7,
  C_MPG: 8
};

goog.object.extend(exports, proto.sys);
