// source: Status.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global =
    (typeof globalThis !== 'undefined' && globalThis) ||
    (typeof window !== 'undefined' && window) ||
    (typeof global !== 'undefined' && global) ||
    (typeof self !== 'undefined' && self) ||
    (function () { return this; }).call(null) ||
    Function('return this')();

var Network_pb = require('./Network_pb.js');
goog.object.extend(proto, Network_pb);
var nanopb_pb = require('./nanopb_pb.js');
goog.object.extend(proto, nanopb_pb);
goog.exportSymbol('proto.sys.AV_STATE', null, global);
goog.exportSymbol('proto.sys.BT', null, global);
goog.exportSymbol('proto.sys.CONNECTED_IF', null, global);
goog.exportSymbol('proto.sys.ESP_AVRC_CT', null, global);
goog.exportSymbol('proto.sys.EthStates', null, global);
goog.exportSymbol('proto.sys.HW', null, global);
goog.exportSymbol('proto.sys.MEDIA_STATE', null, global);
goog.exportSymbol('proto.sys.NET', null, global);
goog.exportSymbol('proto.sys.NetworkStates', null, global);
goog.exportSymbol('proto.sys.PLATFORM', null, global);
goog.exportSymbol('proto.sys.Status', null, global);
goog.exportSymbol('proto.sys.UPDATE_REASONS', null, global);
goog.exportSymbol('proto.sys.WIFI', null, global);
goog.exportSymbol('proto.sys.WifiState', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.sys.WIFI = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.sys.WIFI.repeatedFields_, null);
};
goog.inherits(proto.sys.WIFI, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.sys.WIFI.displayName = 'proto.sys.WIFI';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.sys.NET = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.sys.NET, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.sys.NET.displayName = 'proto.sys.NET';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.sys.BT = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.sys.BT, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.sys.BT.displayName = 'proto.sys.BT';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.sys.PLATFORM = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.sys.PLATFORM, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.sys.PLATFORM.displayName = 'proto.sys.PLATFORM';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.sys.HW = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.sys.HW, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.sys.HW.displayName = 'proto.sys.HW';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.sys.Status = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.sys.Status, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.sys.Status.displayName = 'proto.sys.Status';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.sys.WIFI.repeatedFields_ = [4];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.sys.WIFI.prototype.toObject = function(opt_includeInstance) {
  return proto.sys.WIFI.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.sys.WIFI} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sys.WIFI.toObject = function(includeInstance, msg) {
  var f, obj = {
    connectedSta: (f = msg.getConnectedSta()) && Network_pb.WifiSTAEntry.toObject(includeInstance, f),
    disconnectCount: jspb.Message.getFieldWithDefault(msg, 2, 0),
    avgConnTime: jspb.Message.getFloatingPointFieldWithDefault(msg, 3, 0.0),
    scanResultList: jspb.Message.toObjectList(msg.getScanResultList(),
    Network_pb.WifiSTAEntry.toObject, includeInstance),
    wifiState: jspb.Message.getFieldWithDefault(msg, 5, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.sys.WIFI}
 */
proto.sys.WIFI.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.sys.WIFI;
  return proto.sys.WIFI.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.sys.WIFI} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.sys.WIFI}
 */
proto.sys.WIFI.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new Network_pb.WifiSTAEntry;
      reader.readMessage(value,Network_pb.WifiSTAEntry.deserializeBinaryFromReader);
      msg.setConnectedSta(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setDisconnectCount(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setAvgConnTime(value);
      break;
    case 4:
      var value = new Network_pb.WifiSTAEntry;
      reader.readMessage(value,Network_pb.WifiSTAEntry.deserializeBinaryFromReader);
      msg.addScanResult(value);
      break;
    case 5:
      var value = /** @type {!proto.sys.WifiState} */ (reader.readEnum());
      msg.setWifiState(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.sys.WIFI.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.sys.WIFI.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.sys.WIFI} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sys.WIFI.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getConnectedSta();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      Network_pb.WifiSTAEntry.serializeBinaryToWriter
    );
  }
  f = message.getDisconnectCount();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
  f = message.getAvgConnTime();
  if (f !== 0.0) {
    writer.writeFloat(
      3,
      f
    );
  }
  f = message.getScanResultList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      4,
      f,
      Network_pb.WifiSTAEntry.serializeBinaryToWriter
    );
  }
  f = message.getWifiState();
  if (f !== 0.0) {
    writer.writeEnum(
      5,
      f
    );
  }
};


/**
 * optional WifiSTAEntry connected_sta = 1;
 * @return {?proto.sys.WifiSTAEntry}
 */
proto.sys.WIFI.prototype.getConnectedSta = function() {
  return /** @type{?proto.sys.WifiSTAEntry} */ (
    jspb.Message.getWrapperField(this, Network_pb.WifiSTAEntry, 1));
};


/**
 * @param {?proto.sys.WifiSTAEntry|undefined} value
 * @return {!proto.sys.WIFI} returns this
*/
proto.sys.WIFI.prototype.setConnectedSta = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.sys.WIFI} returns this
 */
proto.sys.WIFI.prototype.clearConnectedSta = function() {
  return this.setConnectedSta(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sys.WIFI.prototype.hasConnectedSta = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional int32 disconnect_count = 2;
 * @return {number}
 */
proto.sys.WIFI.prototype.getDisconnectCount = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.sys.WIFI} returns this
 */
proto.sys.WIFI.prototype.setDisconnectCount = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional float avg_conn_time = 3;
 * @return {number}
 */
proto.sys.WIFI.prototype.getAvgConnTime = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 3, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.sys.WIFI} returns this
 */
proto.sys.WIFI.prototype.setAvgConnTime = function(value) {
  return jspb.Message.setProto3FloatField(this, 3, value);
};


/**
 * repeated WifiSTAEntry scan_result = 4;
 * @return {!Array<!proto.sys.WifiSTAEntry>}
 */
proto.sys.WIFI.prototype.getScanResultList = function() {
  return /** @type{!Array<!proto.sys.WifiSTAEntry>} */ (
    jspb.Message.getRepeatedWrapperField(this, Network_pb.WifiSTAEntry, 4));
};


/**
 * @param {!Array<!proto.sys.WifiSTAEntry>} value
 * @return {!proto.sys.WIFI} returns this
*/
proto.sys.WIFI.prototype.setScanResultList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 4, value);
};


/**
 * @param {!proto.sys.WifiSTAEntry=} opt_value
 * @param {number=} opt_index
 * @return {!proto.sys.WifiSTAEntry}
 */
proto.sys.WIFI.prototype.addScanResult = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 4, opt_value, proto.sys.WifiSTAEntry, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.sys.WIFI} returns this
 */
proto.sys.WIFI.prototype.clearScanResultList = function() {
  return this.setScanResultList([]);
};


/**
 * optional WifiState wifi_state = 5;
 * @return {!proto.sys.WifiState}
 */
proto.sys.WIFI.prototype.getWifiState = function() {
  return /** @type {!proto.sys.WifiState} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {!proto.sys.WifiState} value
 * @return {!proto.sys.WIFI} returns this
 */
proto.sys.WIFI.prototype.setWifiState = function(value) {
  return jspb.Message.setProto3EnumField(this, 5, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.sys.NET.prototype.toObject = function(opt_includeInstance) {
  return proto.sys.NET.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.sys.NET} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sys.NET.toObject = function(includeInstance, msg) {
  var f, obj = {
    wifi: (f = msg.getWifi()) && proto.sys.WIFI.toObject(includeInstance, f),
    ip: (f = msg.getIp()) && Network_pb.IP.toObject(includeInstance, f),
    networkState: jspb.Message.getFieldWithDefault(msg, 5, 0),
    ethState: jspb.Message.getFieldWithDefault(msg, 6, 0),
    ethUp: jspb.Message.getBooleanFieldWithDefault(msg, 7, false),
    updtReason: jspb.Message.getFieldWithDefault(msg, 8, 0),
    pb_interface: jspb.Message.getFieldWithDefault(msg, 9, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.sys.NET}
 */
proto.sys.NET.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.sys.NET;
  return proto.sys.NET.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.sys.NET} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.sys.NET}
 */
proto.sys.NET.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.sys.WIFI;
      reader.readMessage(value,proto.sys.WIFI.deserializeBinaryFromReader);
      msg.setWifi(value);
      break;
    case 2:
      var value = new Network_pb.IP;
      reader.readMessage(value,Network_pb.IP.deserializeBinaryFromReader);
      msg.setIp(value);
      break;
    case 5:
      var value = /** @type {!proto.sys.NetworkStates} */ (reader.readEnum());
      msg.setNetworkState(value);
      break;
    case 6:
      var value = /** @type {!proto.sys.EthStates} */ (reader.readEnum());
      msg.setEthState(value);
      break;
    case 7:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setEthUp(value);
      break;
    case 8:
      var value = /** @type {!proto.sys.UPDATE_REASONS} */ (reader.readEnum());
      msg.setUpdtReason(value);
      break;
    case 9:
      var value = /** @type {!proto.sys.CONNECTED_IF} */ (reader.readEnum());
      msg.setInterface(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.sys.NET.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.sys.NET.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.sys.NET} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sys.NET.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getWifi();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.sys.WIFI.serializeBinaryToWriter
    );
  }
  f = message.getIp();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      Network_pb.IP.serializeBinaryToWriter
    );
  }
  f = message.getNetworkState();
  if (f !== 0.0) {
    writer.writeEnum(
      5,
      f
    );
  }
  f = message.getEthState();
  if (f !== 0.0) {
    writer.writeEnum(
      6,
      f
    );
  }
  f = message.getEthUp();
  if (f) {
    writer.writeBool(
      7,
      f
    );
  }
  f = message.getUpdtReason();
  if (f !== 0.0) {
    writer.writeEnum(
      8,
      f
    );
  }
  f = message.getInterface();
  if (f !== 0.0) {
    writer.writeEnum(
      9,
      f
    );
  }
};


/**
 * optional WIFI wifi = 1;
 * @return {?proto.sys.WIFI}
 */
proto.sys.NET.prototype.getWifi = function() {
  return /** @type{?proto.sys.WIFI} */ (
    jspb.Message.getWrapperField(this, proto.sys.WIFI, 1));
};


/**
 * @param {?proto.sys.WIFI|undefined} value
 * @return {!proto.sys.NET} returns this
*/
proto.sys.NET.prototype.setWifi = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.sys.NET} returns this
 */
proto.sys.NET.prototype.clearWifi = function() {
  return this.setWifi(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sys.NET.prototype.hasWifi = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional IP ip = 2;
 * @return {?proto.sys.IP}
 */
proto.sys.NET.prototype.getIp = function() {
  return /** @type{?proto.sys.IP} */ (
    jspb.Message.getWrapperField(this, Network_pb.IP, 2));
};


/**
 * @param {?proto.sys.IP|undefined} value
 * @return {!proto.sys.NET} returns this
*/
proto.sys.NET.prototype.setIp = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.sys.NET} returns this
 */
proto.sys.NET.prototype.clearIp = function() {
  return this.setIp(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sys.NET.prototype.hasIp = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional NetworkStates network_state = 5;
 * @return {!proto.sys.NetworkStates}
 */
proto.sys.NET.prototype.getNetworkState = function() {
  return /** @type {!proto.sys.NetworkStates} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {!proto.sys.NetworkStates} value
 * @return {!proto.sys.NET} returns this
 */
proto.sys.NET.prototype.setNetworkState = function(value) {
  return jspb.Message.setProto3EnumField(this, 5, value);
};


/**
 * optional EthStates eth_state = 6;
 * @return {!proto.sys.EthStates}
 */
proto.sys.NET.prototype.getEthState = function() {
  return /** @type {!proto.sys.EthStates} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/**
 * @param {!proto.sys.EthStates} value
 * @return {!proto.sys.NET} returns this
 */
proto.sys.NET.prototype.setEthState = function(value) {
  return jspb.Message.setProto3EnumField(this, 6, value);
};


/**
 * optional bool eth_up = 7;
 * @return {boolean}
 */
proto.sys.NET.prototype.getEthUp = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 7, false));
};


/**
 * @param {boolean} value
 * @return {!proto.sys.NET} returns this
 */
proto.sys.NET.prototype.setEthUp = function(value) {
  return jspb.Message.setProto3BooleanField(this, 7, value);
};


/**
 * optional UPDATE_REASONS updt_reason = 8;
 * @return {!proto.sys.UPDATE_REASONS}
 */
proto.sys.NET.prototype.getUpdtReason = function() {
  return /** @type {!proto.sys.UPDATE_REASONS} */ (jspb.Message.getFieldWithDefault(this, 8, 0));
};


/**
 * @param {!proto.sys.UPDATE_REASONS} value
 * @return {!proto.sys.NET} returns this
 */
proto.sys.NET.prototype.setUpdtReason = function(value) {
  return jspb.Message.setProto3EnumField(this, 8, value);
};


/**
 * optional CONNECTED_IF interface = 9;
 * @return {!proto.sys.CONNECTED_IF}
 */
proto.sys.NET.prototype.getInterface = function() {
  return /** @type {!proto.sys.CONNECTED_IF} */ (jspb.Message.getFieldWithDefault(this, 9, 0));
};


/**
 * @param {!proto.sys.CONNECTED_IF} value
 * @return {!proto.sys.NET} returns this
 */
proto.sys.NET.prototype.setInterface = function(value) {
  return jspb.Message.setProto3EnumField(this, 9, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.sys.BT.prototype.toObject = function(opt_includeInstance) {
  return proto.sys.BT.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.sys.BT} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sys.BT.toObject = function(includeInstance, msg) {
  var f, obj = {
    btStatus: jspb.Message.getFieldWithDefault(msg, 1, 0),
    btSubStatus: jspb.Message.getFieldWithDefault(msg, 2, 0),
    btMediaState: jspb.Message.getFieldWithDefault(msg, 3, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.sys.BT}
 */
proto.sys.BT.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.sys.BT;
  return proto.sys.BT.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.sys.BT} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.sys.BT}
 */
proto.sys.BT.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.sys.AV_STATE} */ (reader.readEnum());
      msg.setBtStatus(value);
      break;
    case 2:
      var value = /** @type {!proto.sys.ESP_AVRC_CT} */ (reader.readEnum());
      msg.setBtSubStatus(value);
      break;
    case 3:
      var value = /** @type {!proto.sys.MEDIA_STATE} */ (reader.readEnum());
      msg.setBtMediaState(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.sys.BT.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.sys.BT.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.sys.BT} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sys.BT.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getBtStatus();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getBtSubStatus();
  if (f !== 0.0) {
    writer.writeEnum(
      2,
      f
    );
  }
  f = message.getBtMediaState();
  if (f !== 0.0) {
    writer.writeEnum(
      3,
      f
    );
  }
};


/**
 * optional AV_STATE bt_status = 1;
 * @return {!proto.sys.AV_STATE}
 */
proto.sys.BT.prototype.getBtStatus = function() {
  return /** @type {!proto.sys.AV_STATE} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {!proto.sys.AV_STATE} value
 * @return {!proto.sys.BT} returns this
 */
proto.sys.BT.prototype.setBtStatus = function(value) {
  return jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * optional ESP_AVRC_CT bt_sub_status = 2;
 * @return {!proto.sys.ESP_AVRC_CT}
 */
proto.sys.BT.prototype.getBtSubStatus = function() {
  return /** @type {!proto.sys.ESP_AVRC_CT} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {!proto.sys.ESP_AVRC_CT} value
 * @return {!proto.sys.BT} returns this
 */
proto.sys.BT.prototype.setBtSubStatus = function(value) {
  return jspb.Message.setProto3EnumField(this, 2, value);
};


/**
 * optional MEDIA_STATE bt_media_state = 3;
 * @return {!proto.sys.MEDIA_STATE}
 */
proto.sys.BT.prototype.getBtMediaState = function() {
  return /** @type {!proto.sys.MEDIA_STATE} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {!proto.sys.MEDIA_STATE} value
 * @return {!proto.sys.BT} returns this
 */
proto.sys.BT.prototype.setBtMediaState = function(value) {
  return jspb.Message.setProto3EnumField(this, 3, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.sys.PLATFORM.prototype.toObject = function(opt_includeInstance) {
  return proto.sys.PLATFORM.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.sys.PLATFORM} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sys.PLATFORM.toObject = function(includeInstance, msg) {
  var f, obj = {
    project: jspb.Message.getFieldWithDefault(msg, 1, ""),
    version: jspb.Message.getFieldWithDefault(msg, 2, ""),
    recovery: jspb.Message.getBooleanFieldWithDefault(msg, 3, false),
    target: jspb.Message.getFieldWithDefault(msg, 4, ""),
    depth: jspb.Message.getFieldWithDefault(msg, 5, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.sys.PLATFORM}
 */
proto.sys.PLATFORM.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.sys.PLATFORM;
  return proto.sys.PLATFORM.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.sys.PLATFORM} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.sys.PLATFORM}
 */
proto.sys.PLATFORM.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setProject(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setVersion(value);
      break;
    case 3:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setRecovery(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setTarget(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setDepth(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.sys.PLATFORM.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.sys.PLATFORM.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.sys.PLATFORM} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sys.PLATFORM.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getProject();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getVersion();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getRecovery();
  if (f) {
    writer.writeBool(
      3,
      f
    );
  }
  f = message.getTarget();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getDepth();
  if (f !== 0) {
    writer.writeInt32(
      5,
      f
    );
  }
};


/**
 * optional string project = 1;
 * @return {string}
 */
proto.sys.PLATFORM.prototype.getProject = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.sys.PLATFORM} returns this
 */
proto.sys.PLATFORM.prototype.setProject = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string version = 2;
 * @return {string}
 */
proto.sys.PLATFORM.prototype.getVersion = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.sys.PLATFORM} returns this
 */
proto.sys.PLATFORM.prototype.setVersion = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional bool recovery = 3;
 * @return {boolean}
 */
proto.sys.PLATFORM.prototype.getRecovery = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 3, false));
};


/**
 * @param {boolean} value
 * @return {!proto.sys.PLATFORM} returns this
 */
proto.sys.PLATFORM.prototype.setRecovery = function(value) {
  return jspb.Message.setProto3BooleanField(this, 3, value);
};


/**
 * optional string target = 4;
 * @return {string}
 */
proto.sys.PLATFORM.prototype.getTarget = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.sys.PLATFORM} returns this
 */
proto.sys.PLATFORM.prototype.setTarget = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional int32 depth = 5;
 * @return {number}
 */
proto.sys.PLATFORM.prototype.getDepth = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.sys.PLATFORM} returns this
 */
proto.sys.PLATFORM.prototype.setDepth = function(value) {
  return jspb.Message.setProto3IntField(this, 5, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.sys.HW.prototype.toObject = function(opt_includeInstance) {
  return proto.sys.HW.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.sys.HW} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sys.HW.toObject = function(includeInstance, msg) {
  var f, obj = {
    jackInserted: jspb.Message.getBooleanFieldWithDefault(msg, 1, false),
    battVoltage: jspb.Message.getFloatingPointFieldWithDefault(msg, 2, 0.0),
    hasJackInserted: jspb.Message.getBooleanFieldWithDefault(msg, 3, false),
    spkFault: jspb.Message.getBooleanFieldWithDefault(msg, 4, false),
    hasSpkFault: jspb.Message.getBooleanFieldWithDefault(msg, 5, false)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.sys.HW}
 */
proto.sys.HW.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.sys.HW;
  return proto.sys.HW.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.sys.HW} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.sys.HW}
 */
proto.sys.HW.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setJackInserted(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setBattVoltage(value);
      break;
    case 3:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setHasJackInserted(value);
      break;
    case 4:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setSpkFault(value);
      break;
    case 5:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setHasSpkFault(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.sys.HW.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.sys.HW.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.sys.HW} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sys.HW.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getJackInserted();
  if (f) {
    writer.writeBool(
      1,
      f
    );
  }
  f = message.getBattVoltage();
  if (f !== 0.0) {
    writer.writeFloat(
      2,
      f
    );
  }
  f = message.getHasJackInserted();
  if (f) {
    writer.writeBool(
      3,
      f
    );
  }
  f = message.getSpkFault();
  if (f) {
    writer.writeBool(
      4,
      f
    );
  }
  f = message.getHasSpkFault();
  if (f) {
    writer.writeBool(
      5,
      f
    );
  }
};


/**
 * optional bool jack_inserted = 1;
 * @return {boolean}
 */
proto.sys.HW.prototype.getJackInserted = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 1, false));
};


/**
 * @param {boolean} value
 * @return {!proto.sys.HW} returns this
 */
proto.sys.HW.prototype.setJackInserted = function(value) {
  return jspb.Message.setProto3BooleanField(this, 1, value);
};


/**
 * optional float batt_voltage = 2;
 * @return {number}
 */
proto.sys.HW.prototype.getBattVoltage = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 2, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.sys.HW} returns this
 */
proto.sys.HW.prototype.setBattVoltage = function(value) {
  return jspb.Message.setProto3FloatField(this, 2, value);
};


/**
 * optional bool supports_jack_inserted = 3;
 * @return {boolean}
 */
proto.sys.HW.prototype.getHasJackInserted = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 3, false));
};


/**
 * @param {boolean} value
 * @return {!proto.sys.HW} returns this
 */
proto.sys.HW.prototype.setHasJackInserted = function(value) {
  return jspb.Message.setProto3BooleanField(this, 3, value);
};


/**
 * optional bool spk_fault = 4;
 * @return {boolean}
 */
proto.sys.HW.prototype.getSpkFault = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 4, false));
};


/**
 * @param {boolean} value
 * @return {!proto.sys.HW} returns this
 */
proto.sys.HW.prototype.setSpkFault = function(value) {
  return jspb.Message.setProto3BooleanField(this, 4, value);
};


/**
 * optional bool supports_spk_fault = 5;
 * @return {boolean}
 */
proto.sys.HW.prototype.getHasSpkFault = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 5, false));
};


/**
 * @param {boolean} value
 * @return {!proto.sys.HW} returns this
 */
proto.sys.HW.prototype.setHasSpkFault = function(value) {
  return jspb.Message.setProto3BooleanField(this, 5, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.sys.Status.prototype.toObject = function(opt_includeInstance) {
  return proto.sys.Status.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.sys.Status} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sys.Status.toObject = function(includeInstance, msg) {
  var f, obj = {
    platform: (f = msg.getPlatform()) && proto.sys.PLATFORM.toObject(includeInstance, f),
    hw: (f = msg.getHw()) && proto.sys.HW.toObject(includeInstance, f),
    bt: (f = msg.getBt()) && proto.sys.BT.toObject(includeInstance, f),
    lms: (f = msg.getLms()) && Network_pb.Server.toObject(includeInstance, f),
    net: (f = msg.getNet()) && proto.sys.NET.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.sys.Status}
 */
proto.sys.Status.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.sys.Status;
  return proto.sys.Status.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.sys.Status} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.sys.Status}
 */
proto.sys.Status.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.sys.PLATFORM;
      reader.readMessage(value,proto.sys.PLATFORM.deserializeBinaryFromReader);
      msg.setPlatform(value);
      break;
    case 2:
      var value = new proto.sys.HW;
      reader.readMessage(value,proto.sys.HW.deserializeBinaryFromReader);
      msg.setHw(value);
      break;
    case 3:
      var value = new proto.sys.BT;
      reader.readMessage(value,proto.sys.BT.deserializeBinaryFromReader);
      msg.setBt(value);
      break;
    case 4:
      var value = new Network_pb.Server;
      reader.readMessage(value,Network_pb.Server.deserializeBinaryFromReader);
      msg.setLms(value);
      break;
    case 5:
      var value = new proto.sys.NET;
      reader.readMessage(value,proto.sys.NET.deserializeBinaryFromReader);
      msg.setNet(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.sys.Status.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.sys.Status.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.sys.Status} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sys.Status.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPlatform();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.sys.PLATFORM.serializeBinaryToWriter
    );
  }
  f = message.getHw();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.sys.HW.serializeBinaryToWriter
    );
  }
  f = message.getBt();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.sys.BT.serializeBinaryToWriter
    );
  }
  f = message.getLms();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      Network_pb.Server.serializeBinaryToWriter
    );
  }
  f = message.getNet();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      proto.sys.NET.serializeBinaryToWriter
    );
  }
};


/**
 * optional PLATFORM platform = 1;
 * @return {?proto.sys.PLATFORM}
 */
proto.sys.Status.prototype.getPlatform = function() {
  return /** @type{?proto.sys.PLATFORM} */ (
    jspb.Message.getWrapperField(this, proto.sys.PLATFORM, 1));
};


/**
 * @param {?proto.sys.PLATFORM|undefined} value
 * @return {!proto.sys.Status} returns this
*/
proto.sys.Status.prototype.setPlatform = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.sys.Status} returns this
 */
proto.sys.Status.prototype.clearPlatform = function() {
  return this.setPlatform(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sys.Status.prototype.hasPlatform = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional HW hw = 2;
 * @return {?proto.sys.HW}
 */
proto.sys.Status.prototype.getHw = function() {
  return /** @type{?proto.sys.HW} */ (
    jspb.Message.getWrapperField(this, proto.sys.HW, 2));
};


/**
 * @param {?proto.sys.HW|undefined} value
 * @return {!proto.sys.Status} returns this
*/
proto.sys.Status.prototype.setHw = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.sys.Status} returns this
 */
proto.sys.Status.prototype.clearHw = function() {
  return this.setHw(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sys.Status.prototype.hasHw = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional BT bt = 3;
 * @return {?proto.sys.BT}
 */
proto.sys.Status.prototype.getBt = function() {
  return /** @type{?proto.sys.BT} */ (
    jspb.Message.getWrapperField(this, proto.sys.BT, 3));
};


/**
 * @param {?proto.sys.BT|undefined} value
 * @return {!proto.sys.Status} returns this
*/
proto.sys.Status.prototype.setBt = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.sys.Status} returns this
 */
proto.sys.Status.prototype.clearBt = function() {
  return this.setBt(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sys.Status.prototype.hasBt = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional Server LMS = 4;
 * @return {?proto.sys.Server}
 */
proto.sys.Status.prototype.getLms = function() {
  return /** @type{?proto.sys.Server} */ (
    jspb.Message.getWrapperField(this, Network_pb.Server, 4));
};


/**
 * @param {?proto.sys.Server|undefined} value
 * @return {!proto.sys.Status} returns this
*/
proto.sys.Status.prototype.setLms = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.sys.Status} returns this
 */
proto.sys.Status.prototype.clearLms = function() {
  return this.setLms(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sys.Status.prototype.hasLms = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional NET net = 5;
 * @return {?proto.sys.NET}
 */
proto.sys.Status.prototype.getNet = function() {
  return /** @type{?proto.sys.NET} */ (
    jspb.Message.getWrapperField(this, proto.sys.NET, 5));
};


/**
 * @param {?proto.sys.NET|undefined} value
 * @return {!proto.sys.Status} returns this
*/
proto.sys.Status.prototype.setNet = function(value) {
  return jspb.Message.setWrapperField(this, 5, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.sys.Status} returns this
 */
proto.sys.Status.prototype.clearNet = function() {
  return this.setNet(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sys.Status.prototype.hasNet = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * @enum {number}
 */
proto.sys.CONNECTED_IF = {
  IF_UNKNOWN: 0,
  IF_WIFI: 1,
  IF_ETHERNET: 2
};

/**
 * @enum {number}
 */
proto.sys.AV_STATE = {
  A_IDLE: 0,
  A_DISCOVERING: 1,
  A_DISCOVERED: 2,
  A_UNCONNECTED: 3,
  A_CONNECTING: 4,
  A_CONNECTED: 5,
  A_DISCONNECTING: 6
};

/**
 * @enum {number}
 */
proto.sys.MEDIA_STATE = {
  M_IDLE: 0,
  M_STARTING: 1,
  M_STARTED: 2,
  M_STOPPING: 3,
  M_WAIT_DISCONNECT: 4
};

/**
 * @enum {number}
 */
proto.sys.UPDATE_REASONS = {
  R_UNKNOWN: 0,
  R_CONNECTION_OK: 1,
  R_FAILED_ATTEMPT: 2,
  R_USER_DISCONNECT: 3,
  R_LOST_CONNECTION: 4,
  R_FAILED_ATTEMPT_AND_RESTORE: 5,
  R_ETHERNET_CONNECTED: 6
};

/**
 * @enum {number}
 */
proto.sys.ESP_AVRC_CT = {
  ESP_AVRC_CT_CONNECTION_STATE_EVT: 0,
  ESP_AVRC_CT_PASSTHROUGH_RSP_EVT: 1,
  ESP_AVRC_CT_METADATA_RSP_EVT: 2,
  ESP_AVRC_CT_PLAY_STATUS_RSP_EVT: 3,
  ESP_AVRC_CT_CHANGE_NOTIFY_EVT: 4,
  ESP_AVRC_CT_REMOTE_FEATURES_EVT: 5,
  ESP_AVRC_CT_GET_RN_CAPABILITIES_RSP_EVT: 6,
  ESP_AVRC_CT_SET_ABSOLUTE_VOLUME_RSP_EVT: 7
};

/**
 * @enum {number}
 */
proto.sys.NetworkStates = {
  NET_UNKNOWN: 0,
  NET_INSTANTIATED: 1,
  NET_INITIALIZING: 2,
  NET_ETH_ACTIVE: 3,
  NET_WIFI_ACTIVE: 4,
  NET_WIFI_CONFIGURING_ACTIVE: 5
};

/**
 * @enum {number}
 */
proto.sys.EthStates = {
  ETH_UNKNOWN: 0,
  ETH_STARTING: 1,
  ETH_ACTIVE_LINKUP: 2,
  ETH_ACTIVE_LINKDOWN: 3,
  ETH_ACTIVE_CONNECTED: 4,
  ETH_CONNECTING_NEW: 5
};

/**
 * @enum {number}
 */
proto.sys.WifiState = {
  WIFI_UNKNOWN: 0,
  WIFI_INITIALIZING: 1,
  WIFI_CONNECTING: 2,
  WIFI_CONNECTING_NEW: 3,
  WIFI_CONNECTING_NEW_FAILED: 4,
  WIFI_CONNECTED: 5,
  WIFI_USER_DISCONNECTED: 6,
  WIFI_LOST_CONNECTION: 7
};

goog.object.extend(exports, proto.sys);
