#!/bin/bash

# This file gets executed to build the image on the Docker Hub.
# See https://docs.docker.com/docker-hub/builds/advanced/#build-hook-examples for details.

set -euo pipefail

echo "Building the Dockerfile-pinned ESP-IDF image"

docker build \
    -f $DOCKERFILE_PATH \
    -t $IMAGE_NAME .
