syntax = "proto3";

package sys;

import "Services.proto";
import "GPIO.proto";
import "Devices.proto";
import "Names.proto";
import "Network.proto";
import "customoptions.proto";
import "nanopb.proto";


// Main configuration structure
message Config   {

  // Provides the global name for the pointer to
  // protoc plugins
  option (cust_msg).global_name  = "platform->";
  option (nanopb_msgopt).msgid  = 1000;
  
  // GPIO structure definition with leds, etc
  Gpios gpios = 1;

  // Device tree with SPI, I2C, SPDIF, Display, etc
  Dev dev = 2;

  // Platform services definition with options
  Services services = 3 ;

  // Main device name used for networking, etc. Services which 
  // need a name typically  has the option to overwrite its own name 
  Names names = 4;

  // Hardware platform (e.g. SqueezeAMP, MUSE, etc.)
  string platform = 5 [(nanopb).type = FT_POINTER];

  NetworkConfig net = 6;
  string target = 7 [(nanopb).max_length = 55];
  
}

