syntax = "proto3";

package sys;
import "GPIO.proto";
import "DacControlSet.proto";
import "I2CBus.proto";
import "customoptions.proto";
import "nanopb.proto";
option (nanopb_fileopt).enum_to_string = true;

enum DACModelEnum {
  UNSPECIFIED_MODEL = 0;
  TAS57xx = 1;
  TAS5713 = 2;
  AC101 = 3;
  WM8978 = 4;
  ES8388 = 5;
  I2S = 6;
  CS4265 = 7;
}
enum MCKEnum {
  UNSPECIFIED_MCK = 0;
  MCK0 = 1;
  MCK1 = 2;
  MCK2 = 3;
}

message DAC {
  option (nanopb_msgopt).msgid  = 10008;
  GPIO bck = 1 [(cust_field).read_only = true] ;
  GPIO ws = 2;
  GPIO dout = 3;
  MCKEnum mck = 4;
  GPIO mute = 5;
  DACModelEnum model = 6;
  I2CBus i2c = 7;
  DacControlSet daccontrolset = 8;
  bool jack_mutes_amp = 9;
}