syntax = "proto3";

package sys.i2c;
import "nanopb.proto";
import "customoptions.proto";

option (nanopb_fileopt).enum_to_string = true;

enum port {
  UNSPECIFIED = 0;
  PORT0 = 1;
  PORT1 = 2;
}
message bus {
  option (nanopb_msgopt).packed_struct  = true;
  option (nanopb_msgopt).msgid  = 10034;
  port port = 1 ;
  int64 speed = 2  [(cust_field).v_int64 = 400000];
  int32 sda = 3 [(nanopb).int_size=IS_16, (cust_field).v_int32=-1];
  int32 scl = 4 [(nanopb).int_size=IS_16, (cust_field).v_int32=-1];
}
message device {
  option (nanopb_msgopt).packed_struct  = true;
  option (nanopb_msgopt).msgid  = 10021;
  int32 address = 1  [(nanopb).int_size = IS_8];
}