syntax = "proto3";

package sys.services;

import "AirPlay.proto";
import "Equalizer.proto";
import "Metadata.proto";
import "Sleep.proto";
import "Spotify.proto";
import "Squeezelite.proto";
import "Telnet.proto";

import "nanopb.proto";
import "customoptions.proto";


  
  message bt_sink {
    option (nanopb_msgopt).packed_struct  = true;
    bool enabled = 1 [(cust_field).v_bool = true];
    uint32 volume =  2;
    string pin= 3 [(nanopb).max_length = 16,(cust_field).v_string = "0000" ];
  }

  message config {
    option (nanopb_msgopt).packed_struct  = true;
    option (nanopb_msgopt).msgid  = 10037;
    metadata.config metadata = 1;
    sleep.config sleep = 2;
    spotify.config cspot = 4;
    airplay.config airplay = 5;
    repeated squeezelite.profile squeezelite_profiles = 6 [(nanopb).max_count = 5, 
                                                          (cust_field).v_msg = '[{"name":"i2s","profile":{"output_type":"I2S","log":{"output":"DEBUG","stream":"DEBUG","decode":"DEBUG","slimproto":"DEBUG","ir":"DEBUG"},"buffers":{"stream":500,"output":2000},"max_rate":96000,"enabled":true,"amp_gpio_timeout":30,"wav_aiff_header_parsing":true}},{"name":"spdif","profile":{"output_type":"SPDIF","log":{"output":"DEBUG","stream":"DEBUG","decode":"DEBUG","slimproto":"DEBUG","ir":"DEBUG"},"buffers":{"stream":500,"output":2000},"max_rate":48000,"enabled":true,"amp_gpio_timeout":30,"wav_aiff_header_parsing":true}},{"name":"bluetooth","profile":{"output_type":"BT","log":{"output":"DEBUG","stream":"DEBUG","decode":"DEBUG","slimproto":"DEBUG","ir":"DEBUG"},"buffers":{"stream":500,"output":2000},"max_rate":44100,"enabled":true,"amp_gpio_timeout":30,"wav_aiff_header_parsing":true}}]'] ;
    string release_url = 7 [(nanopb).max_length = 256, (cust_field).v_string = "https://api.github.com/repos/sle118/squeezelite-esp32/releases"];
    bt_sink bt_sink = 8;
    bool statistics = 9 [(cust_field).v_bool = false];
    telnet.config telnet = 10;
    equalizer.config equalizer = 11;
    string current_profile = 12 [(nanopb).type = FT_POINTER, (cust_field).v_string = "i2s"];
    // default time zone is Montreal.
    // see https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
    // or for a handy list: https://gist.github.com/alwynallan/24d96091655391107939
    string timezone = 13 [(nanopb).type = FT_POINTER, (cust_field).v_string = "EST5EDT,M3.2.0,M11.1.0"];
  } 