syntax = "proto3";
package sys.status;
import "Network.proto";
import "nanopb.proto";

option (nanopb_fileopt).enum_to_string = true;
// Enum for APP_AV_STATE
enum interfaces {
  IF_UNKNOWN = 0;
  IF_WIFI = 1;
  IF_ETHERNET = 2;
}
enum av_states {
    A_IDLE = 0;
    A_DISCOVERING = 1;
    A_DISCOVERED = 2;
    A_UNCONNECTED = 3;
    A_CONNECTING = 4;
    A_CONNECTED = 5;
    A_DISCONNECTING = 6;
  }
  enum media_states {
    M_IDLE = 0;
    M_STARTING = 1;
    M_STARTED = 2;
    M_STOPPING = 3;
	  M_WAIT_DISCONNECT = 4;
  }
  enum reasons {
    R_UNKNOWN = 0;
    R_CONNECTION_OK = 1;
    R_FAILED_ATTEMPT = 2;
    R_USER_DISCONNECT = 3;
    R_LOST_CONNECTION = 4;
    R_FAILED_ATTEMPT_AND_RESTORE = 5;
    R_ETHERNET_CONNECTED = 6; 
   }
  // Enum for ESP_AVRC_CT
  enum avrc_ct {
    ESP_AVRC_CT_CONNECTION_STATE_EVT = 0;
    ESP_AVRC_CT_PASSTHROUGH_RSP_EVT = 1;
    ESP_AVRC_CT_METADATA_RSP_EVT = 2;
    ESP_AVRC_CT_PLAY_STATUS_RSP_EVT = 3;
    ESP_AVRC_CT_CHANGE_NOTIFY_EVT = 4;
    ESP_AVRC_CT_REMOTE_FEATURES_EVT = 5;
    ESP_AVRC_CT_GET_RN_CAPABILITIES_RSP_EVT = 6;
    ESP_AVRC_CT_SET_ABSOLUTE_VOLUME_RSP_EVT = 7;
  }
  enum net_states {
    NET_UNKNOWN = 0;
    NET_INSTANTIATED = 1;
    NET_INITIALIZING = 2;
    NET_ETH_ACTIVE = 3;
    NET_WIFI_ACTIVE = 4;
    NET_WIFI_CONFIGURING_ACTIVE = 5;
  }
  enum eth_states {
    ETH_UNKNOWN = 0;
    ETH_STARTING = 1;
    ETH_ACTIVE_LINKUP = 2;
    ETH_ACTIVE_LINKDOWN = 3;
    ETH_ACTIVE_CONNECTED = 4;
    ETH_CONNECTING_NEW = 5;
  }
 enum wifi_States {
  WIFI_UNKNOWN = 0;
  WIFI_INITIALIZING = 1;
  WIFI_CONNECTING = 2;
  WIFI_CONNECTING_NEW = 3;
  WIFI_CONNECTING_NEW_FAILED = 4;
  WIFI_CONNECTED = 5;
  WIFI_USER_DISCONNECTED = 6;
  WIFI_LOST_CONNECTION = 7;
 }


message wifi {
  option (nanopb_msgopt).packed_struct  = true;
  option (nanopb_msgopt).msgid  = 10052;
  sys.net.wifi_entry connected_sta = 1;
  int32 disconnect_count = 2;
  float avg_conn_time = 3;
  repeated sys.net.wifi_entry scan_result = 4 [(nanopb).type = FT_CALLBACK, (nanopb).callback_datatype = "sys_net_wifi_entry*"];
  wifi_States wifi_state = 5;
}
message net {
  option (nanopb_msgopt).packed_struct  = true;
  option (nanopb_msgopt).msgid  = 10053;
  wifi wifi = 1;
  sys.net.ip ip = 2;
  net_states network_state = 5;
  eth_states eth_state = 6;
  bool eth_up = 7;
  reasons updt_reason = 8;
  interfaces interface = 9;
  
}
message bt {
  option (nanopb_msgopt).packed_struct  = true;
  option (nanopb_msgopt).msgid  = 10054;
  av_states bt_status = 1;
  avrc_ct bt_sub_status = 2;
  media_states bt_media_state = 3;
}
message platform {
  option (nanopb_msgopt).packed_struct  = true;
  option (nanopb_msgopt).msgid  = 10055;
  string project = 1 [(nanopb).max_length = 128];
  string version   = 2 [(nanopb).max_length = 25];
  bool recovery = 3;
  string target = 4 [(nanopb).type = FT_POINTER];
  int32 depth = 5;
}
message hw {
  option (nanopb_msgopt).packed_struct  = true;
  option (nanopb_msgopt).msgid  = 10056;
  bool jack_inserted = 1;
  float batt_voltage = 2;
  bool supports_jack_inserted = 3;
  bool spk_fault = 4;
  bool supports_spk_fault = 5;
}
message data {
  option (nanopb_msgopt).packed_struct  = true;
  option (nanopb_msgopt).msgid  = 10057;
  platform platform = 1;
  hw hw = 2;
  bt bt = 3;
  sys.net.server LMS = 4;
  net net = 5;
  

}
