syntax = "proto3";
package sys;
import "Network.proto";
import "nanopb.proto";

option (nanopb_fileopt).enum_to_string = true;
// Enum for APP_AV_STATE
enum CONNECTED_IF {
  IF_UNKNOWN = 0;
  IF_WIFI = 1;
  IF_ETHERNET = 2;
}
enum AV_STATE {
    A_IDLE = 0;
    A_DISCOVERING = 1;
    A_DISCOVERED = 2;
    A_UNCONNECTED = 3;
    A_CONNECTING = 4;
    A_CONNECTED = 5;
    A_DISCONNECTING = 6;
  }
  enum MEDIA_STATE {
    M_IDLE = 0;
    M_STARTING = 1;
    M_STARTED = 2;
    M_STOPPING = 3;
	  M_WAIT_DISCONNECT = 4;
  }
  enum UPDATE_REASONS {
    R_UNKNOWN = 0;
    R_CONNECTION_OK = 1;
    R_FAILED_ATTEMPT = 2;
    R_USER_DISCONNECT = 3;
    R_LOST_CONNECTION = 4;
    R_FAILED_ATTEMPT_AND_RESTORE = 5;
    R_ETHERNET_CONNECTED = 6; 
   }
  // Enum for ESP_AVRC_CT
  enum ESP_AVRC_CT {
    ESP_AVRC_CT_CONNECTION_STATE_EVT = 0;
    ESP_AVRC_CT_PASSTHROUGH_RSP_EVT = 1;
    ESP_AVRC_CT_METADATA_RSP_EVT = 2;
    ESP_AVRC_CT_PLAY_STATUS_RSP_EVT = 3;
    ESP_AVRC_CT_CHANGE_NOTIFY_EVT = 4;
    ESP_AVRC_CT_REMOTE_FEATURES_EVT = 5;
    ESP_AVRC_CT_GET_RN_CAPABILITIES_RSP_EVT = 6;
    ESP_AVRC_CT_SET_ABSOLUTE_VOLUME_RSP_EVT = 7;
  }
  enum NetworkStates {
    NET_UNKNOWN = 0;
    NET_INSTANTIATED = 1;
    NET_INITIALIZING = 2;
    NET_ETH_ACTIVE = 3;
    NET_WIFI_ACTIVE = 4;
    NET_WIFI_CONFIGURING_ACTIVE = 5;
  }
  enum EthStates {
    ETH_UNKNOWN = 0;
    ETH_STARTING = 1;
    ETH_ACTIVE_LINKUP = 2;
    ETH_ACTIVE_LINKDOWN = 3;
    ETH_ACTIVE_CONNECTED = 4;
    ETH_CONNECTING_NEW = 5;
  }
 enum WifiState {
  WIFI_UNKNOWN = 0;
  WIFI_INITIALIZING = 1;
  WIFI_CONNECTING = 2;
  WIFI_CONNECTING_NEW = 3;
  WIFI_CONNECTING_NEW_FAILED = 4;
  WIFI_CONNECTED = 5;
  WIFI_USER_DISCONNECTED = 6;
  WIFI_LOST_CONNECTION = 7;
 }


message WIFI {
  option (nanopb_msgopt).msgid  = 10052;
  WifiSTAEntry connected_sta = 1;
  int32 disconnect_count = 2;
  float avg_conn_time = 3;
  repeated WifiSTAEntry scan_result = 4 [ (nanopb).type = FT_POINTER  ];
  WifiState wifi_state = 5;
}
message NET {
  option (nanopb_msgopt).msgid  = 10053;
  WIFI wifi = 1;
  IP ip = 2;
  NetworkStates network_state = 5;
  EthStates eth_state = 6;
  bool eth_up = 7;
  UPDATE_REASONS updt_reason = 8;
  CONNECTED_IF interface = 9;
  
}
message BT {
  option (nanopb_msgopt).msgid  = 10054;
  AV_STATE bt_status = 1;
  ESP_AVRC_CT bt_sub_status = 2;
  MEDIA_STATE bt_media_state = 3;
}
message PLATFORM {
  option (nanopb_msgopt).msgid  = 10055;
  string project = 1 [(nanopb).max_length = 128];
  string version   = 2 [(nanopb).max_length = 25];
  bool recovery = 3;
  string name = 4 [(nanopb).max_length = 55];
  int32 depth = 5;
}
message HW {
  option (nanopb_msgopt).msgid  = 10056;
  bool jack_inserted = 1;
  float batt_voltage = 2;
  bool has_jack_inserted = 3;
  bool spk_fault = 4;
  bool has_spk_fault = 5;
}
message Status {
  option (nanopb_msgopt).msgid  = 10057;
  PLATFORM platform = 1;
  HW hw = 2;
  BT bt = 3;
  Server LMS = 4;
  NET net = 5;
}
